### ISSUE TITLE
同一个recycler设置多个adapter时候切换数据源报错

### ISSUE THREAD

**Issue by AngelBo** [CymChad/BaseRecyclerViewAdapterHelper#1033]
Process: com.tengw.aicairen, PID: 15935
                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List com.chad.library.adapter.base.entity.IExpandable.getSubItems()' on a null object reference
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.hasSubItems(BaseQuickAdapter.java:1640)
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.expandAll(BaseQuickAdapter.java:1517)
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.expandAll(BaseQuickAdapter.java:1557)
                                                                        at com.tengw.aicairen.ui.activity.FootBallActivity.initUIData(FootBallActivity.java:129)
                                                                        at com.tengw.aicairen.ui.activity.FootBallActivity.access$300(FootBallActivity.java:48)
                                                                        at com.tengw.aicairen.ui.activity.FootBallActivity$3.onClick(FootBallActivity.java:280)
                                                                        at android.view.View.performClick(View.java:4811)
                                                                        at android.view.View$PerformClick.run(View.java:20136)
                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.13'
