### ISSUE TITLE
StaggeredGridLayoutManager实现表格列表，会出现崩溃

### ISSUE THREAD

**Issue by xianchuangwu** [CymChad/BaseRecyclerViewAdapterHelper#1084]
版本号：2.9.15

我是完全按照PullToRefreshUseActivity来实现我的需求的，只有setLayoutManager设置的是StaggeredGridLayoutManager，会出现上滑崩溃bug，期待大神修复。

错误日志：
05-02 18:20:31.976 22389-22389/com.chad.five E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.chad.five, PID: 22389
                                                               java.lang.IllegalArgumentException: Pixel distance must be non-negative
                                                                   at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.addPosition(GapWorker.java:110)
                                                                   at android.support.v7.widget.StaggeredGridLayoutManager.collectAdjacentPrefetchPositions(StaggeredGridLayoutManager.java:2109)
                                                                   at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:94)
                                                                   at android.support.v7.widget.GapWorker.buildTaskList(GapWorker.java:213)
                                                                   at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:343)
                                                                   at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by 1109993488** [comment]
你的应该和 #1069 类似，你可以检查下support包版本
