### ISSUE TITLE
三星盖世三安卓4.1.2系统报错

### ISSUE THREAD

**Issue by whb7762300** [CymChad/BaseRecyclerViewAdapterHelper#1088]
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1359)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:881)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:877)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:675)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:67)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
                                                       at android.view.View.layout(View.java:14055)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:4604)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                       at android.view.View.layout(View.java:14055)
                                                   	at

**Comment by CymChad** [comment]
#906

**Comment by whb7762300** [comment]
额,我犯二了,我这边布局的一个引用问题,抱歉
