### ISSUE TITLE
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0 	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(SourceFile:7106)

### ISSUE THREAD

**Issue by rongdongliu** [CymChad/BaseRecyclerViewAdapterHelper#1092]
新奔溃

```

Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(SourceFile:7106)
                                                         addViewInt
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(SourceFile:7070)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1430)
	at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1377)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:588)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3315)
	at android.support.v7.widget.RecyclerView.onMeasure(SourceFile:2843)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6427)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6427)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6427)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6427)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6427)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3140)
	at android.view.View.measure(View.java:20236)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2712)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1656)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7616)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:622)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Back traces ends.
```

**Comment by CymChad** [comment]
版本，复现方式

**Comment by rongdongliu** [comment]
大概半个月前的代码，我是直接导入源码去项目的，奔溃场景未知，这个是奔溃平台反馈的数据。奔溃1/10000.
Mobile Information: 'model: SM-G532F/version: 6.0.1/sdk: 23'
我需要额外把lib的传给你吗，大神？

**Comment by CymChad** [comment]
先更新最新的版本，需要提供具体复现场景我才找到解决办法。否者我这边无法复现也没办法解决bug。

**Comment by rongdongliu** [comment]
好的，convert方法，可以增加一个position 回调吗，我每次使用都是自己修改接口，增加position回调的，因为有需要用到position。
至于具体的复现场景，我这边也是很苦恼，奔溃都是从用户那边反馈的，而且奔溃的用户非常少。我使用过其他的加载框架，也是遇到这样的问题。然而产品又非常看重奔溃率。。。。。。╮(╯▽╰)╭

**Comment by CymChad** [comment]
convert 可以通过viewholder.getLayoutPosition里面获取。

**Comment by syp520syp** [comment]
我也遇到相同的问题

**Comment by syp520syp** [comment]
FATAL EXCEPTION: main
                                                         java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:1
                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7869)
                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7833)
                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7821)
                                                             at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:579)
                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                             at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1325)
                                                             at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
                                                             at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
                                                             at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4734)
                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:567)
                                                             at android.view.Choreographer.doFrame(Choreographer.java:535)
                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
                                                             at android.os.Handler.handleCallback(Handler.java:615)
                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                             at android.os.Looper.loop(Looper.java:153)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5014)
                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by syp520syp** [comment]
RecyclerView 自定义了Adapter增加了头部和底部
