### ISSUE TITLE
这种情况下， 是要直接依赖jar包的节奏吗还是

### ISSUE THREAD

**Issue by cervy** [CymChad/BaseRecyclerViewAdapterHelper#1096]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.acadsoc.learn, PID: 2224
                                                                 java.lang.NoSuchMethodError: No virtual method getLayoutPosition()I in class Lcom/chad/library/adapter/base/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.BaseViewHolder' appears in /data/app/com.xxxxx-1/split_lib_dependencies_apk.apk:classes7.dex)
                                                                     at com.chad.library.adapter.base.BaseSectionQuickAdapter.onBindViewHolder(BaseSectionQuickAdapter.java:49)
                                                                     at com.chad.library.adapter.base.BaseSectionQuickAdapter.onBindViewHolder(BaseSectionQuickAdapter.java:12)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15714)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2104)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1861)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1079)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5914)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5275)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by CymChad** [comment]
#906

**Comment by CymChad** [comment]
请描述详细些

**Comment by CymChad** [comment]
getLayoutPosition 这个方法是原生的方法，应该是你的jar包引入问题。
