### ISSUE TITLE
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0 	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(RecyclerView.java:7106) 

### ISSUE THREAD

**Issue by rongdongliu** [CymChad/BaseRecyclerViewAdapterHelper#1125]
Mobile Information: 'model: F103/version: 5.0/sdk: 21'

Runtime Information: 'start: 20170513202748/maxheap: 134217728'

```
Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(RecyclerView.java:7106)
	                                                        addViewInt
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7070)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1430)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:588)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2666)
	at android.view.View.measure(View.java:17820)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2374)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1389)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1613)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1267)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5537)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Back traces ends.
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
```
使用场景一个应用墙，显示APP图标，和一些版本，大小，下载按钮==
sdk版本最新版
无法提供demo，也不知道如何复现，4w更新奔溃1/10000，应该是极端操作，但是无法复现粗来。
不知道使用sdk的其他同学有没有遇到过呢。

**Comment by CymChad** [comment]
http://blog.csdn.net/aaawqqq/article/details/51930834  有没有可能是这样？

**Comment by rongdongliu** [comment]
目前的列表，是没有做下拉刷新的，只有分页上啦加载
