### ISSUE TITLE
ShimmerAdapter cannot be cast to BaseQuickAdapter

### ISSUE THREAD

**Issue by alouanemed** [CymChad/BaseRecyclerViewAdapterHelper#1167]
When using SwhimmerView (com.cooltechworks.views. shimmer) with BRVAH while data is loading and an event click is made it causes an error : 

 ```
ShimmerRecyclerView mRecyclerView;
..
 mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
      @Override public void onSimpleItemClick(final BaseQuickAdapter adapter, final View view,
          final int position) {
        switch (view.getId()) {
          case R.id.card:
            startActivity(new Intent(getActivity(), ProfileActivity.class));
        }
      }
    });
```

```
 java.lang.ClassCastException: com.cooltechworks.views.shimmer.ShimmerAdapter cannot be cast to com.chad.library.adapter.base.BaseQuickAdapter
                                                                                     at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:44)
                                                                                     at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2689)
                                                                                     at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2735)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
                                                                                     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
                                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                                                     at android.view.View.dispatchPointerEvent(View.java:10243)
                                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
                                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
                                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
                                                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
                                                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
                                                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
                                                                                 	at android.view.InputEventReceiver.dispatchInpu
```

**Comment by CymChad** [comment]
You use so give it a try
 ```java
adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d(TAG, "onItemClick: ");
                Toast.makeText(ItemClickActivity.this, "onItemClick" + position, Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by alouanemed** [comment]
It works! Thanks 👍
