### ISSUE TITLE
BaseMultiItemQuickAdapter ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by chiragdigi** [CymChad/BaseRecyclerViewAdapterHelper#1179]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=18; index=-1
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getDefItemViewType(BaseMultiItemQuickAdapter.java:35)
       at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:462)
       at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:267)
       at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:32)
       at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SimpleClickListener.java:106)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:651)
       at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
       at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
       at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:51)
       at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2612)
       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2740)
       at android.view.View.dispatchTouchEvent(View.java:10018)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2833)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
       at android.view.View.dispatchPointerEvent(View.java:10253)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5527)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5363)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4968)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5025)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7529)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7397)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7358)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7639)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:7410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by CymChad** [comment]
版本，复现操作。

**Comment by chiragdigi** [comment]
I am using library version 2.4.7

Not getting crash of my java class so not able to debug or re produce it.
Here i am attaching log, may be it will help you to find out issue.
![capture](https://cloud.githubusercontent.com/assets/15996952/26781387/d544c924-4a0b-11e7-80d6-ca64b0da6565.PNG)

**Comment by Y-JH** [comment]
使用这个适配的话，前期在调用显示数据到列表之前 要保证多布局类型type 已经确定，否则就报错的!!

**Comment by chiragdigi** [comment]
Not getting what are you saying?

**Comment by CymChad** [comment]
Try the update to the latest version
