### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by xicong** [CymChad/BaseRecyclerViewAdapterHelper#1205]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:11
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1325)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
                                                                       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4726)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                       at dalvik.system.NativeStart.main(Native Method)

这个问题有什么好的办法处理或者避免吗？？？

**Comment by FrankKwok** [comment]
#590

**Comment by xicong** [comment]
![image](https://user-images.githubusercontent.com/11675597/27827465-031a591e-60ea-11e7-8f04-c23885316cdb.png)
处理之后还是会出现啊特别在三星s7 edge上出现频率很高，
