### ISSUE TITLE
Item Swipe 删除问题

### ISSUE THREAD

**Issue by yinzhijia** [CymChad/BaseRecyclerViewAdapterHelper#1222]
当页面加载完数据后，再次向RecyclerView 的adapter填充数据刷新，这时滑动删除新增的数据有问题，提示IndexOutOfBoundsException。

**Comment by elfman** [comment]
@yinzhijia 请贴下详细的log

**Comment by yinzhijia** [comment]
com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.chad.baserecyclerviewadapterhelper, PID: 4327
                                                                                      java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                          at java.util.ArrayList.remove(ArrayList.java:503)
                                                                                          at com.chad.library.adapter.base.BaseItemDraggableAdapter.onItemSwiped(BaseItemDraggableAdapter.java:246)
                                                                                          at com.chad.library.adapter.base.callback.ItemDragAndSwipeCallback.onSwiped(ItemDragAndSwipeCallback.java:100)
                                                                                          at android.support.v7.widget.helper.ItemTouchHelper$4.run(ItemTouchHelper.java:686)
                                                                                          at android.os.Handler.handleCallback(Handler.java:769)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by yinzhijia** [comment]
com.chad.baserecyclerviewadapterhelper E/ItemDragAndSwipeUseActivity: mData size: 5
com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.chad.baserecyclerviewadapterhelper, PID: 7073
                                                                                      java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                          at java.util.ArrayList.remove(ArrayList.java:503)
                                                                                          at com.chad.library.adapter.base.BaseItemDraggableAdapter.onItemSwiped(BaseItemDraggableAdapter.java:246)
                                                                                          at com.chad.library.adapter.base.callback.ItemDragAndSwipeCallback.onSwiped(ItemDragAndSwipeCallback.java:100)
                                                                                          at android.support.v7.widget.helper.ItemTouchHelper$4.run(ItemTouchHelper.java:686)
                                                                                          at android.os.Handler.handleCallback(Handler.java:769)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                      
                                                                                      
                                                                                      --------- beginning of system

**Comment by CymChad** [comment]
你的数据源用的是哪一个？

**Comment by yinzhijia** [comment]
刷新数据后用的同一个数据源

**Comment by CymChad** [comment]
恩，我这边复现一下试试

**Comment by CymChad** [comment]
你删除数据的时候调用了那个方法？

**Comment by CymChad** [comment]
添加延迟加载即可
```java
 public void onItemSwiped(RecyclerView.ViewHolder viewHolder, int pos) {
                Log.d(TAG, "View Swiped: " + pos);
                --size;
                new Handler().postAtTime(new Runnable() {
                    @Override
                    public void run() {
                        if (size == 0)
                            mAdapter.replaceData(generateData(5));
                    }
                },2000);

            }
```

**Comment by CymChad** [comment]
因为源码是先回调onItemSwiped再删除数据的，如果在删除数据之前填充了数据，那么index肯定会变化，所以会出现下标越界。
