### ISSUE TITLE
fragment中使用，刚创建layout就报错了，求助

### ISSUE THREAD

**Issue by hanfeng1982** [CymChad/BaseRecyclerViewAdapterHelper#1224]
1:自己的fragment继承了android.app.Fragment
2：自己的fragment的onCreateView方法中直接用setlayoutManager，然后就报了空指针异常。
      mRecyclerView.setLayoutManager(new StaggeredGridLayoutManager(2,             StaggeredGridLayoutManager.VERTICAL));
        mData = getSampleData();
        SectionAdapter sectionAdapter = new SectionAdapter(R.layout.item_section_content, R.layout.def_section_head, mData);
   
        mRecyclerView.setAdapter(sectionAdapter);

错误信息：
       java.lang.RuntimeException: Unable to start activity ComponentInfo{******Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference

请高手指教下哈，android超级菜鸟来着。

**Comment by hanfeng1982** [comment]
sorry，是我傻了，犯了个不好意思说的低级错误。问题已经解决。
