### ISSUE TITLE
添加header和footer的时候，layout布局问题

### ISSUE THREAD

**Issue by fengwei23** [CymChad/BaseRecyclerViewAdapterHelper#1237]
大佬，我使用2.9.18版本的时候，在添加header和footer的时候，看源码的话，在方向为HORIZONTAL的时候，footer和header是height是MATCH_PARENT，width是WRAP_CONTENT，在方向为VERTICAL是footer和header是height是WRAP_CONTENT，width是MATCH_PARENT。
我的问题：目前我添加了footer，但是我的recylerview要支持横竖屏切换，如果刚开始是HORIZONTAL，切换到VERTICAL的时候，footer就会占一个recylerview的height，我希望就是footer自己原始的大小，请问需要怎么做？谢谢

**Comment by AllenCoder** [comment]
切换横竖屏之后，调用removeFooterView(footView)和removeHeaderView(View header)，再重新添加一次footview和headerView

**Comment by fengwei23** [comment]
我有按照您说的，尝试了一下，如果我在removeFooterView(footView)后，去调用addFooterView（footView），会出现
   Process: com.chad.baserecyclerviewadapterhelper, PID: 10469
      java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{f1dcb4a position=4 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)}
                                                                                            at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:748)
                                                                                            at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
                                                                                            at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1259)
                                                                                            at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3765)
                                                                                            at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:514)
                                                                                            at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:244)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3607)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
                                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                            at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                                            at android.view.View.layout(View.java:17641)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-22 14:07:22.733 10469-10469/com.chad.baserecyclerviewadapterhelper E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by fengwei23** [comment]
我尝试把源码的布局改了，增加了一个新的addFooterView方法，
  public int addFooterView(View footer, int index, int orientation, int width, int height) {
        if (mFooterLayout == null) {
            mFooterLayout = new LinearLayout(footer.getContext());
            if (orientation == LinearLayout.VERTICAL) {
                mFooterLayout.setOrientation(LinearLayout.VERTICAL);
                mFooterLayout.setLayoutParams(new LayoutParams(width, height));
            } else {
                mFooterLayout.setOrientation(LinearLayout.HORIZONTAL);
                mFooterLayout.setLayoutParams(new LayoutParams(width, height));
            }
        }
        final int childCount = mFooterLayout.getChildCount();
        if (index < 0 || index > childCount) {
            index = childCount;
        }
        mFooterLayout.addView(footer, index);
        if (mFooterLayout.getChildCount() == 1) {
            int position = getFooterViewPosition();
            if (position != -1) {
                notifyItemInserted(position);
            }
        }
        return index;
    }
 这样看起来比较像我想要的效果了
