### ISSUE TITLE
在自定义viewholder中 嵌套 recyclerview 时会出现 findviewbyid(R.id.recyclerview) 为空的情况，而且点击加载更多会报ClassCastException

### ISSUE THREAD

**Issue by MirkoWu** [CymChad/BaseRecyclerViewAdapterHelper#1240]
在自定义viewholder中 嵌套 recyclerview 时会出现 findviewbyid(R.id.recyclerview) 为空的情况，
public class ViewHolder extends BaseRVHolder {
    public ChildCommentAdapter childAdapter;
    public RecyclerView childRcyclerView;

    public ViewHolder(View itemView) {
        super(itemView);
        childRcyclerView = getView(R.id.childRecyclerView);
        childAdapter = new ChildCommentAdapter(itemView.getContext(), R.layout.item_child_comment, isDetail);
        L.d("ViewHolder", " childRcyclerView " + (childRcyclerView == null) );//上拉列表时 childRcyclerView 会出现空指针 
        childRcyclerView.setAdapter(childAdapter);
    }
}
此时会有异常如下：
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at com.mirkowu.baserecyclerviewadapterlibrary.BaseRVAdapter.createGenericKInstance(BaseRVAdapter.java:555)
    at com.mirkowu.baserecyclerviewadapterlibrary.BaseRVAdapter.createBaseViewHolder(BaseRVAdapter.java:533)
    at com.mirkowu.baserecyclerviewadapterlibrary.BaseRVAdapter.creatLoadingViewHolder(BaseRVAdapter.java:498)
    at com.mirkowu.baserecyclerviewadapterlibrary.BaseRVAdapter.onCreateViewHolder(BaseRVAdapter.java:277)
    at com.mirkowu.baserecyclerviewadapterlibrary.BaseRVAdapter.onCreateViewHolder(BaseRVAdapter.java:55)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2748)
    at android.view.View.layout(View.java:16754)
    at android.view.ViewGroup.layout(ViewGroup.java:5462)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2226)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1983)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6238)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
    at android.view.Choreographer.doCallbacks(Choreographer.java:696)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5621)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
    at com.softgarden.moduo.ui.comment.ViewHolder.<init>(ViewHolder.java:25)

虽然报了异常 但程序还是可以正常运行的，
但问题在点击  底部的 加载更多item时（开启了上拉加载），就会报viewholder 转换异常 如下
  java.lang.ClassCastException: com.mirkowu.baserecyclerviewadapterlibrary.BaseRVHolder cannot be cast to com.softgarden.moduo.ui.comment.ViewHolder

**Comment by MirkoWu** [comment]
用的是楼主最新的版本测试的，可以试试
public class TestAdapter extends BaseQuickAdapter<String, TestAdapter.ViewHolder> {

    public TestAdapter(@LayoutRes int layoutResId, @Nullable List<String> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(ViewHolder helper, String item) {
        helper.mChildAdapter.setNewData(DataServer.getStrData());
    }

    @Override
    protected ViewHolder createBaseViewHolder(View view) {

        return new ViewHolder(view);
    }

    public class ViewHolder extends BaseViewHolder {
        public RecyclerView mRecyclerView;
        public ChildAdapter mChildAdapter;

        public ViewHolder(View view) {
            super(view);
            mRecyclerView = getView(R.id.mRecyclerView);
            mChildAdapter = new ChildAdapter(R.layout.item_image_view);
            mRecyclerView.setAdapter(mChildAdapter);
        }
    }

    public class ChildAdapter extends BaseQuickAdapter<String, BaseViewHolder> {


        public ChildAdapter(@LayoutRes int layoutResId) {
            super(layoutResId);
        }

        @Override
        protected void convert(BaseViewHolder helper, String item) {

        }
    }
}

**Comment by FrankKwok** [comment]
为什么要复写createBaseViewHolder这个方法？

**Comment by MirkoWu** [comment]
@FrankKwok  复写是为了写databinding 
@Override
    protected ViewHolder createBaseViewHolder(ViewGroup parent, int layoutResId) {
        ViewDataBinding binding = DataBindingUtil.inflate(LayoutInflater.from(parent.getContext()), layoutResId, parent, false);
        View view = binding.getRoot();
        view.setTag(R.id.BaseRVAdapter_databinding_support, binding);
        return createBaseViewHolder(view);
    }

我试过只要复写了 createBaseViewHolder(view) 内容什么都不改，只写一个super,都会crash

**Comment by MirkoWu** [comment]
我觉得实际上是有可能出现重新该方法的情况，比较每个人的用途不同，而且你自己也标注了 if you want to use subclass of BaseViewHolder in the adapter, you must override the method to create new ViewHolder。出现问题不可怕，问题是怎么解决。

**Comment by FrankKwok** [comment]
@MirkoWu 复写了 createBaseViewHolder(view) 内容什么都不改，只写一个super,都会crash，这里crash的错误能贴出来吗

**Comment by MirkoWu** [comment]
@FrankKwok  java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter$ViewHolder
    at com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter.createBaseViewHolder(TestAdapter.java:32)
    at com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter.createBaseViewHolder(TestAdapter.java:19)
    at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:769)
    at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:747)
    at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
    at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
    at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
    at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
    at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
    at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5621)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by MirkoWu** [comment]
@FrankKwok   而且发现了
//只要重写第一个这个方法 不管改不改都会carsh 报上面那个错误---- 而后面二个却不会

  @Override
 protected ViewHolder createBaseViewHolder(View view) {
     return super.createBaseViewHolder(view);
 }

   @Override
   protected ViewHolder createBaseViewHolder(ViewGroup parent, int layoutResId) {
       return super.createBaseViewHolder(parent, layoutResId);
   }
   @Override
   protected ViewHolder onCreateDefViewHolder(ViewGroup parent, int viewType) {
       return super.onCreateDefViewHolder(parent, viewType);
   }

但是三个都会报都这个异常
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1024)
    at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1005)
    at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:769)
    at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:747)
    at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
    at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
    at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
    at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
    at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
    at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5621)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setAdapter(android.support.v7.widget.RecyclerView$Adapter)' on a null object reference
    at com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter$ViewHolder.<init>(TestAdapter.java:54)
	... 20 more

**Comment by FrankKwok** [comment]
好的，我写个demo试一下

**Comment by FrankKwok** [comment]
@MirkoWu 为什么我这里没问题呢

**Comment by FrankKwok** [comment]
@MirkoWu 修改了一下，都复现了。。。

**Comment by MirkoWu** [comment]
我就说。。。，我都折腾一天了，实在解决不了没办法才来问你们

**Comment by MirkoWu** [comment]
而且我试过 即使不重写creatBaseViewholder ，我把databinding 的设置放到你写的那样里
 @Override
    protected View getItemView(int layoutResId, ViewGroup parent) {
        ViewDataBinding binding = DataBindingUtil.inflate(mLayoutInflater, layoutResId, parent, false);
        if (binding == null) {
            return super.getItemView(layoutResId, parent);
        }
        View view = binding.getRoot();
        view.setTag(R.id.BaseQuickAdapter_databinding_support, binding);
        return view;
    }
还是会出现 java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter$ViewHolder  上面提到的异常

**Comment by FrankKwok** [comment]
@MirkoWu 这个异常java.lang.reflect.InvocationTargetException我已经知道原因了，是因为，复写方法后LoadingView用的也是ViewHolder，从LoadingView里是找不到R.id.mRecyclerView的，会触发NPE，引起这个异常

**Comment by FrankKwok** [comment]
@MirkoWu 这些个异常全是因为从LoadingView里是找不到R.id.mRecyclerView引起的

**Comment by MirkoWu** [comment]
@FrankKwok  嗯嗯，这里的异常虽说被catch到了，一般情况是不会出现问题的，除了重写才会暴露出来

**Comment by 1109993488** [comment]
@MirkoWu 你可以把需要做的操作方onCreateDefViewHolder这里，这里只是data集合的Item，不包含header、footer、loadMore

**Comment by MirkoWu** [comment]
@FrankKwok  我试过，但是onCreateDefViewHolder 里的参数获取不到layout,因为它是private

**Comment by MirkoWu** [comment]
@FrankKwok 要不然就得重写getDefItemViewType()，还是可以的，但感觉这只是零时的解决办法

**Comment by 1109993488** [comment]
```
@Override
    protected BaseViewHolder onCreateDefViewHolder(ViewGroup parent, int viewType) {
        BaseViewHolder holder = super.onCreateDefViewHolder(parent, viewType);
        //能从holder中拿到view
        return holder;
    }
```

**Comment by 1109993488** [comment]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.chad.baserecyclerviewadapterhelper.adapter.TestAdapter$ViewHolder 这个是因为你的TestAdapter泛型还是BaseViewHolder，需要改为TestAdapter.ViewHolder

**Comment by FrankKwok** [comment]
@1109993488 他的泛型是对的，```protected K createBaseViewHolder(View view) {
        Class temp = getClass();
        Class z = null;
        while (z == null && null != temp) {
            z = getInstancedGenericKClass(temp);
            temp = temp.getSuperclass();
        }
        K k = createGenericKInstance(z, view);
        return null != k ? k : (K) new BaseViewHolder(view);
    }```,是因为创建LoadingView的时候出了NPE,所以K是null了，执行了(K) new BaseViewHolder(view)这里出现的转型异常

**Comment by MirkoWu** [comment]
@1109993488   这样确实是可以的，但是我要使用databinding 
 ViewDataBinding binding = DataBindingUtil.inflate(LayoutInflater.from(parent.getContext()), layoutResId, parent, false);
        View view = binding.getRoot();
        view.setTag(R.id.BaseRVAdapter_databinding_support, binding);
就要获取layoutResId,这里不行
觉得还是用你demo里的，在
 protected View getItemView(int layoutResId, ViewGroup parent) {
        ViewDataBinding binding = DataBindingUtil.inflate(LayoutInflater.from(parent.getContext()), layoutResId, parent, false);
        if (binding == null) {
            return super.getItemView(layoutResId, parent);
        }
        View view = binding.getRoot();
        view.setTag(R.id.BaseRVAdapter_databinding_support, binding);
        return view;
    }
处理是不是更好点

**Comment by MirkoWu** [comment]
@FrankKwok  是的，所以目前的逻辑来讲，只要重写了viewholder，并且用了loadingview 就一定会出现转型异常

**Comment by FrankKwok** [comment]
@MirkoWu 复写getItemView方法设置DataBinding是可行的

**Comment by CymChad** [comment]
我在想是不是可以在执行代码之前先判断一下itemview的type类型

**Comment by MirkoWu** [comment]
@FrankKwok  嗯嗯，我目前就是这么处理的，但是那个类型转换异常的还是存在的

**Comment by MirkoWu** [comment]
@CymChad  在哪个方法前判断？

**Comment by CymChad** [comment]
`super(itemView); `之后

**Comment by MirkoWu** [comment]
@ChadCym 你这个是不是想偏了，这个问题在于转换异常，为什么会有这个异常，为什么headerview、footerview,emptyView没有这个问题，是因为你把loadingview的holder当成了自定义那个，不信你看下源码
 /**
     * return the loading viewholder
     */
    private VH creatLoadingViewHolder(ViewGroup parent) {
        View view = getItemView(mLoadMoreView.getLayoutId(), parent);
        return createBaseViewHolder(view);
    }
 @Override
    public void onBindViewHolder(VH holder, final int position) {
        int viewType = holder.getItemViewType();
        switch (viewType) {
            case LOADING_VIEW:
                mLoadMoreView.convert(holder);
                break;
            case HEADER_VIEW:
                break;
            case EMPTY_VIEW:
                break;
            case FOOTER_VIEW:
                break;
            case 0://0即为默认
            default:
                onBindVH(holder, getItem(position), position);
        }
    }

**Comment by MirkoWu** [comment]
你这个是不是想偏了，这个问题在于转换异常，为什么会有这个异常，是因为你把loadingview的holder当成了自定义那个，不信你看下源码,明明这些类型的holder就是BaseViewholder 你却要转成泛型的。
 @Override
    public VH onCreateViewHolder(ViewGroup parent, int viewType) {
        this.mContext = parent.getContext();
        this.mLayoutInflater = LayoutInflater.from(mContext);
        VH vh = null;
        switch (viewType) {
            case EMPTY_VIEW:
                vh = createBaseViewHolder(mEmptyLayout);
                break;
            case HEADER_VIEW:
                vh = createBaseViewHolder(mHeaderLayout);
                break;
            case FOOTER_VIEW:
                vh = createBaseViewHolder(mFooterLayout);
                break;
            case LOADING_VIEW:
                vh = creatLoadingViewHolder(parent);
                break;
            default:
                vh = onCreateDefViewHolder(parent, viewType);
       
        }
/**
* return the loading viewholder
*/
private VH creatLoadingViewHolder(ViewGroup parent) {
View view = getItemView(mLoadMoreView.getLayoutId(), parent);
return createBaseViewHolder(view);
}

**Comment by FrankKwok** [comment]
不复写方法是没有转换异常的

**Comment by FrankKwok** [comment]
不复写这个方法createBaseViewHolder是没有转换异常的

**Comment by FrankKwok** [comment]
@MirkoWu 不要再构造方法里面获取子RecyclerView，在convert方法里获取

**Comment by MirkoWu** [comment]
@FrankKwok 在holder中获取RecyclerView  是为了缓存adapter ，在convert方法里每一次都要setAdapter

**Comment by FrankKwok** [comment]
@MirkoWu 这样是不对的，你创建ViewHolder的时候并不知道要绑定哪个Adapter？如果不在convert里调用setAdapter，会导致视图错乱的

**Comment by MirkoWu** [comment]
@FrankKwok 一个holder对应一个recycler 和adapter 怎么会错乱呢？我的问题目前已经解决了。

**Comment by FrankKwok** [comment]
@MirkoWu holder是会被复用的，里面的recycler和adapter复用的时候没有做处理
