### ISSUE TITLE
关于滑动删除，重新获取数据setNewData()的时候，数组越界问题

### ISSUE THREAD

**Issue by wenlonghe340067** [CymChad/BaseRecyclerViewAdapterHelper#1259]
FATAL EXCEPTION: main
                                                                            Process: cn.nutritionworld.liaoning, PID: 31862
                                                                            java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                at java.util.ArrayList.get(ArrayList.java:413)
                                                                                at com.chad.library.adapter.base.BaseSectionQuickAdapter.getDefItemViewType(BaseSectionQuickAdapter.java:33)
                                                                                at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:464)
                                                                                at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:226)
                                                                                at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:31)
                                                                                at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onLongPress(SimpleClickListener.java:153)
                                                                                at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:776)
                                                                                at android.view.GestureDetector.-wrap0(GestureDetector.java)
                                                                                at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:296)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by wenlonghe340067** [comment]
依赖版本：compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.0'
集成EasySwipeMenuLayout后，点击删除按钮后，请求服务端数据，删除成功后，请求列表数据后，setNewData(),直接报上面的错误。

**Comment by wenlonghe340067** [comment]
将依赖工程更换到最新版后，BUG暂时消失，会持续关注后续的测试，如再次发现，在请教作者~！
