### ISSUE TITLE
添加了HeaderView时,当网络请求错误时setEmptyView，发现java.lang.IndexOutOfBoundsException。。。。。。。有谁碰到过的吗

### ISSUE THREAD

**Issue by xiaobaoCat** [CymChad/BaseRecyclerViewAdapterHelper#1280]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2fa89b76 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                               at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:260)
                                                               at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:229)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                               at android.view.View.layout(View.java:15695)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5048)
                                                           	at android.view.ViewRootImp

**Comment by FrankKwok** [comment]
可能是使用方式不对，参考#1105

**Comment by FrankKwok** [comment]
这个方法不是在发生错误的时候才使用的，而是先配置好setEmptyView，没有数据就会显示emptyView

**Comment by FrankKwok** [comment]
@xiaobaoCat 你是怎么用的，能不能看下你的代码？

**Comment by xiaobaoCat** [comment]
public void getTaskType(){
        OKHttpUtil.GetTaskType(new StringCallback() {
            @Override
            public void onSuccess(Response<String> response) {
                mError=false;
                Log.e("获取任务类型onSuccess", response.body()+"");
                TaskTypeList TaskTypeList=GsonUtils.parseJSON(response.body(),TaskTypeList.class);
                if (ptr != 2) {//不是上拉加载跟多则先清空数据
                    taskTypeDatas.clear();
                }
                if (TaskTypeList!=null&&TaskTypeList.getTask_data()!=null&&TaskTypeList.getTask_data().size()>0){
                    taskTypeDatas.addAll(TaskTypeList.getTask_data());
                }
            }
            @Override
            public void onError(Response<String> response) {
                super.onError(response);
                mError = true;
                Log.e("获取任务类型onError", response.getException().getMessage()+ "");
            }
            @Override
            public void onFinish() {
                super.onFinish();
                Log.e("获取过往消息", "onComplete");
                if (ptr==1){//下拉刷新
                    ptrClassicFrameLayout.refreshComplete();
                }
                if (mError) {
                    mAdapter.setEmptyView(errorView);
                } else {
                    if (taskTypeDatas.size()> 0){
                        mAdapter.setNewData(taskTypeDatas);
                    } else {
                        mAdapter.setEmptyView(notDataView);
                    }
                }
            }
        });
    }



看你的demo好像差不多这样用的？？

**Comment by xiaobaoCat** [comment]
public void getTaskType(){
    OKHttpUtil.GetTaskType(new StringCallback() {
        @Override
        public void onSuccess(Response<String> response) {
            mError=false;
            Log.e("获取任务类型onSuccess", response.body()+"");
            TaskTypeList TaskTypeList=GsonUtils.parseJSON(response.body(),TaskTypeList.class);
            if (ptr != 2) {//不是上拉加载跟多则先清空数据
                taskTypeDatas.clear();
            }
            if (TaskTypeList!=null&&TaskTypeList.getTask_data()!=null&&TaskTypeList.getTask_data().size()>0){
                taskTypeDatas.addAll(TaskTypeList.getTask_data());
            }
        }
        @Override
        public void onError(Response<String> response) {
            super.onError(response);
            mError = true;
            Log.e("获取任务类型onError", response.getException().getMessage()+ "");
        }
        @Override
        public void onFinish() {
            super.onFinish();
            Log.e("获取过往消息", "onComplete");
            if (ptr==1){//下拉刷新
                ptrClassicFrameLayout.refreshComplete();
            }
            if (mError) {
                mAdapter.setEmptyView(errorView);
            } else {
                if (taskTypeDatas.size()> 0){
                    mAdapter.setNewData(taskTypeDatas);
                } else {
                    mAdapter.setEmptyView(notDataView);
                }
            }
        }
    });
}

这排版好看点

**Comment by xiaobaoCat** [comment]
额，怎么还是一样的排版

**Comment by FrankKwok** [comment]
@xiaobaoCat 要调用setNewData(null)的，没有数据才会显示emptyView

**Comment by xiaobaoCat** [comment]
@Override
    public void onClick(View v) {
        mError = true;
        mNoData = true;
        mQuickAdapter.setNewData(null);
        onRefresh();
    }
少看了这边的方法，感谢！！！提个建议，这边的空数据可不可以别覆盖header布局？

**Comment by FrankKwok** [comment]
@xiaobaoCat 这个也有相关的方法的setHeaderAndEmpty，可以多看看文档

**Comment by CymChad** [comment]
@FrankKwok 👍

**Comment by joker-fu** [comment]
@xiaobaoCat  我现象跟你这个一样 没理解怎么解决
