### ISSUE TITLE
如果item中有多个view 只给某一个view添加长按监听，然后长按其他View 就报错了

### ISSUE THREAD

**Issue by monkey-** [CymChad/BaseRecyclerViewAdapterHelper#1286]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPressed(boolean)' on a null object reference
                                                                  at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onLongPress(SimpleClickListener.java:215)
                                                                  at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
                                                                  at android.view.GestureDetector.-wrap0(GestureDetector.java)
                                                                  at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:160)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by FrankKwok** [comment]
哪个版本？调用代码？

**Comment by monkey-** [comment]
@FrankKwok com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.23'
