### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder  这个bug有解决的办法吗？ 用了emptyView后出现的。

### ISSUE THREAD

**Issue by MirkoWu** [CymChad/BaseRecyclerViewAdapterHelper#1305]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8dfce92 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2748)
                                                                          at android.view.View.layout(View.java:16754)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5462)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2226)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1983)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6238)
                                                                      	at android.vie

**Comment by FrankKwok** [comment]
调用代码与版本？

**Comment by manza7014** [comment]
i meet the same issue
