### ISSUE TITLE
公司的项目中有XUtils，集成了这个后本来不报错的开始报空指针了

### ISSUE THREAD

**Issue by wanglu1209** [CymChad/BaseRecyclerViewAdapterHelper#1306]

**Comment by wanglu1209** [comment]
目前测试小米和魅族有这个事情

**Comment by FrankKwok** [comment]
版本与报错信息？

**Comment by wanglu1209** [comment]
java.lang.NoClassDefFoundError: okhttp3.MediaType
                                                       at com.lidroid.mutils.network.OkHttpUtil.<clinit>(OkHttpUtil.java:48)
                                                       at com.lidroid.mutils.MUtils.info(MUtils.java:207)
                                                       at com.lidroid.mutils.MUtils.getPath(MUtils.java:126)
                                                       at com.zhihuidanji.smarterlayer.MyApplication.onCreate(MyApplication.java:69)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by wanglu1209** [comment]
小米1s Android4.4

**Comment by FrankKwok** [comment]
这个com.lidroid.mutils.network.OkHttpUtil和本库没关系吧

**Comment by wanglu1209** [comment]
按照常理来说是的，但是引入库后就报错了，我也是不知道为什么

**Comment by FrankKwok** [comment]
这个代码是哪个库的？

**Comment by wanglu1209** [comment]
XUtils 里面的 MUtils

**Comment by FrankKwok** [comment]
那就是这个库的错误，只是以前没被发现而已

**Comment by wanglu1209** [comment]
我试着改一下吧，谢谢你
