### ISSUE TITLE
recyclerview嵌套recyclerview时使用adapter报android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c

### ISSUE THREAD

**Issue by chaoDream** [CymChad/BaseRecyclerViewAdapterHelper#1308]
`android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
                                                                            at android.content.res.Resources.getValue(Resources.java:1048)
                                                                            at android.content.res.Resources.loadXmlResourceParser(Resources.java:2222)
                                                                            at android.content.res.Resources.getLayout(Resources.java:887)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1458)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:975)
                                                                            at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:49)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:747)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                            at android.view.View.layout(View.java:14273)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4507)
                                                                        	at `

**Comment by CymChad** [comment]
你看看你的布局，错误显示没有找到。

**Comment by CymChad** [comment]
这个和嵌套没关系，demo里面有嵌套recyclerview的实例。

**Comment by chaoDream** [comment]
恩恩，好的，我检查下！

**Comment by wangqingnan** [comment]
我也报了这个错误，最后检查了半天原来是        addItemType()两个参数写反了，建议添加自定义Exception告诉使用者哪里错了

**Comment by CymChad** [comment]
@wangqingnan 恩 好的，感谢建议，我会添加的。

**Comment by CymChad** [comment]
已更新http://www.jianshu.com/p/b343fcff51b0

**Comment by rigortek** [comment]
其实你根据 Resource ID #0xfffffe6c 去R文件中查找是哪个资源的问题,很快就可以定位到问题

**Comment by yangkun19921001** [comment]
@wangqingnan 有可能是同一个 Bean 共用然后 addItemType（，）第一个参数写的不一样也会导致报 Resources$NotFoundException: Resource ID #0xfffffe6c   我就是这样￣□￣｜｜

**Comment by Vander-liu** [comment]
#0xfffffe6c 这个ID 应该就是-404吧 就是资源ID未找到.

**Comment by imknown** [comment]
@yangkun19921001 确实啊...

**Comment by eggcaker** [comment]
@yangkun19921001 有解决吗？
