### ISSUE TITLE
多布局问题：API返回的数据的type没有定义，会崩溃？

### ISSUE THREAD

**Issue by kbq670554802** [CymChad/BaseRecyclerViewAdapterHelper#1327]
BaseMultiItemQuickAdapter 多布局问题：  比如我们只约定了type等于1或者2，但是api返回的数据中type有3的情况，app会崩溃。这时该怎么处理？
catch exception when loading tinker:java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                       at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:52)
                                                                       at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:48)
                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:675)
                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:67)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:614)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1766)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                       at android.view.View.layout(View.java:15677)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2110)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1867)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)

**Comment by FrankKwok** [comment]
API违反了约定怎么处理，应该看你们的产品啊

**Comment by kbq670554802** [comment]
可是也不应该让app崩溃啊

**Comment by FrankKwok** [comment]
到了这个层面库已经不能替你做了，你要自己考虑怎么处理，比如添加默认type

**Comment by FrankKwok** [comment]
或者过滤掉type为3的数据

**Comment by kbq670554802** [comment]
好吧，谢啦
