### ISSUE TITLE
下载demo.apk报错，顺便问一下可以实现下拉刷新吗？自定义下拉刷新布局呢？

### ISSUE THREAD

**Issue by xiangjava** [CymChad/BaseRecyclerViewAdapterHelper#134]
07-07 09:53:13.336 21821-21821/com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.chad.baserecyclerviewadapterhelper, PID: 21821
                                                                                        java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.chad.baserecyclerviewadapterhelper-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chad.baserecyclerviewadapterhelper-1, /vendor/lib, /system/lib]]
                                                                                            at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4395)
                                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:138)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.chad.baserecyclerviewadapterhelper-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.chad.baserecyclerviewadapterhelper-1, /vendor/lib, /system/lib]]
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                            at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                                            at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4395) 
                                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:138) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095) 
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by CymChad** [comment]
下拉刷新，是组合第三方的控件使用，这个adapter是不能提供下拉刷新的。

**Comment by xiangjava** [comment]
下载的demo.apk，启动报错可以看下么

**Comment by CymChad** [comment]
我这边无法重现。要不你下个工程直接运行一下？

**Comment by xiangjava** [comment]
好吧，我以为可以从Log看出来

**Comment by CymChad** [comment]
log的提示，是android内部的东西。
