### ISSUE TITLE
convert 方法获取控件导致空指针异常

### ISSUE THREAD

**Issue by FeatherZhong** [CymChad/BaseRecyclerViewAdapterHelper#1352]
07-26 15:33:53.069 19548-19548/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ycu.giligili.myapplication, PID: 19548
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                       at com.chad.library.adapter.base.BaseViewHolder.setText(BaseViewHolder.java:120)
                                                       at com.ycu.giligili.myapplication.Fragment1Adapter.convert(Fragment1Adapter.java:18)
                                                       at com.ycu.giligili.myapplication.Fragment1Adapter.convert(Fragment1Adapter.java:10)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:925)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java

`public class Fragment1Adapter extends BaseQuickAdapter<Exhibition, BaseViewHolder> {
    public Fragment1Adapter() {
        super(R.layout.fragment_fragment1);
    }

    @Override
    protected void convert(BaseViewHolder viewHolder, Exhibition item) {
        viewHolder.setText(R.id.exhibitionidView, "this is id");
        viewHolder.setText(R.id.exhibitionnameView, "this is name");
    }
}`
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center">

        <ImageView
            android:id="@+id/exhibitionimageView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:layout_gravity="center" />

        <TextView
            android:id="@+id/exhibitionidView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/exhibitionimageView" />

        <TextView
            android:id="@+id/exhibitionnameView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/exhibitionidView"
            android:textSize="20sp" />
    </RelativeLayout>
</LinearLayout>
`
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </android.support.v4.widget.SwipeRefreshLayout>

</android.support.design.widget.CoordinatorLayout>`
对fragment中的控件获取ID的时候出现空指针异常

**Comment by FrankKwok** [comment]
你这个构造器调用有误`super(R.layout.fragment_fragment1);`

**Comment by FeatherZhong** [comment]
谢谢，问题解决了。
