### ISSUE TITLE
createGenericKInstance 时 z.isMemberClass() 空指针

### ISSUE THREAD

**Issue by pdog18** [CymChad/BaseRecyclerViewAdapterHelper#1379]
https://github.com/pdog18/GradleForAndroidPdog/tree/master/app 我的代码在这，

 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isMemberClass()' on a null object reference
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1020)
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1004)
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:986)
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:982)
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:759)
                                                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)

**Comment by FrankKwok** [comment]
是最新的版本吗？

**Comment by FrankKwok** [comment]
下面这段代码擦除了泛型信息，所以无法通过反射找到ViewHolder的类型，`public RefreshLoadmoreAdapter build() {
        return new RefreshLoadmoreAdapter(convert, refresh, loadmore);
    }
`

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.26'
