### ISSUE TITLE
Demo伸缩列表点击移除item报错，快速点击就会报错

### ISSUE THREAD

**Issue by YY007H** [CymChad/BaseRecyclerViewAdapterHelper#1404]
08-07 17:01:36.010 26482-26482/com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.chad.baserecyclerviewadapterhelper, PID: 26482
                                                                                        java.lang.ArrayIndexOutOfBoundsException: length=213; index=-1
                                                                                            at java.util.ArrayList.get(ArrayList.java:310)
                                                                                            at com.chad.baserecyclerviewadapterhelper.adapter.ExpandableItemAdapter$3.onClick(ExpandableItemAdapter.java:103)
                                                                                            at android.view.View.performClick(View.java:4792)
                                                                                            at android.view.View$PerformClick.run(View.java:19938)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5601)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by FrankKwok** [comment]
没有复现错误

**Comment by YY007H** [comment]
[screencapture-1502097406641.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/1204386/screencapture-1502097406641.zip)


这是视频截图，你看看还能复现吗

**Comment by FrankKwok** [comment]
复现了，快速点击同一项会崩溃

**Comment by FrankKwok** [comment]
点击到了已经删除的项目，position为-1

**Comment by YY007H** [comment]
数据还没反应过来么 (☄⊙ω⊙)☄

**Comment by FrankKwok** [comment]
前置条件没做判断，
`if (pos != -1) {
  删除
}`，这样写应该就好了

**Comment by YY007H** [comment]
嗯 这样可以  动画还没消失 就又点击了一下

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.27'
