### ISSUE TITLE
使用多布局时出现android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c

### ISSUE THREAD

**Issue by hejun311** [CymChad/BaseRecyclerViewAdapterHelper#1449]
同这个[Issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1400)出现一样的问题
没有得到解决

初始化
`GoodsAdapter goodsAdapter = new GoodsAdapter(goodses);`

`class GoodsAdapter extends BaseMultiItemQuickAdapter<Goods,BaseViewHolder> {

        public GoodsAdapter(List<Goods> data) {
            super(data);
            addItemType(Goods.just_text,R.layout.item_product_type_text);
            addItemType(Goods.sigle,R.layout.item_product_manager);
            addItemType(Goods.two,R.layout.item_product_type2);
            addItemType(Goods.three,R.layout.item_product_type3);
            addItemType(Goods.four,R.layout.item_product_type4);
        }
。。。。
}`

**Comment by hejun311** [comment]
`android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
                                                                          at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                                                          at android.content.res.Resources.loadXmlResourceParser(Resources.java:2094)
                                                                          at android.content.res.Resources.getLayout(Resources.java:1111)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1475)
                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:986)
                                                                          at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:50)
                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:759)
                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)`

**Comment by hejun311** [comment]
后面发现时数据的问题 不好意思  项目是没有问题的

**Comment by zhuzheng1991** [comment]
你好 具体是什么样的数据会导致这样的问题能具体说说么

**Comment by 13641285636** [comment]
求指点，遇到同样的问题

**Comment by weikjblue** [comment]
老哥 什么样的数据出现的呢  同求

**Comment by CymChad** [comment]
1.要么绑定的数据中type没有一一对应。
2.要么数据填充的时候内容有int类型的。

**Comment by dawangzai** [comment]
数据里的有的 Type，要在
`class GoodsAdapter extends BaseMultiItemQuickAdapter<Goods,BaseViewHolder> {

    public GoodsAdapter(List<Goods> data) {
        super(data);
        addItemType(Goods.just_text,R.layout.item_product_type_text);
        addItemType(Goods.sigle,R.layout.item_product_manager);
        addItemType(Goods.two,R.layout.item_product_type2);
        addItemType(Goods.three,R.layout.item_product_type3);
        addItemType(Goods.four,R.layout.item_product_type4);
    }
。。。。
}`
这里找到对应的布局。

**Comment by GavinTvs** [comment]
也遇到了这种问题，最后发现数据的viewType没有对应上

**Comment by TomGarden** [comment]
今天我出现了这个异常最终定位到问题原因如下：
```java
public class MyEntity implements MultiItemEntity {
    public int getItemType() {
          return errVal;
    }
}

//异常原因就是上面代码中的 errValue 与下面代码中的 value1、value2、value3 均不匹配

public class MyAdapter extends BaseMultiItemQuickAdapter<MyEntity, BaseViewHolder> {

    public LessonAdapter(List<MyEntity> data) {
        super(data);
        addItemType(value1, R.layout.1);
        addItemType(value2, R.layout.2);
        addItemType(value3, R.layout.3);
    }
}

```
