### ISSUE TITLE
在fragment中recycleView添加headView跟下拉刷新后再此切换后报错

### ISSUE THREAD

**Issue by ZhenQian1** [CymChad/BaseRecyclerViewAdapterHelper#1475]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                    at android.view.ViewGroup.addViewInner(ViewGroup.java:3564)
                                                                    at android.view.ViewGroup.addView(ViewGroup.java:3417)
                                                                    at android.view.ViewGroup.addView(ViewGroup.java:3362)
                                                                    at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:711)
                                                                    at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                    at android.view.View.layout(View.java:14828)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4633)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2081)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1838)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1094)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5708)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)

**Comment by CymChad** [comment]
你可以通过“ You must call removeView() ”关键字搜索历史issues会找到你答案的。
