### ISSUE TITLE
你好, 有两个问题麻烦解决下! 

### ISSUE THREAD

**Issue by OpenSourceMIUI** [CymChad/BaseRecyclerViewAdapterHelper#1512]
1. 在fragment 跳转 activity的时候报出以下错误
PersonalBusinessDetailsActivity我已经配置到清单文件中了, 而且保证写的没什么问题, 因为我用其他activity成功跳转到此页面

 
E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.ebuy.shop, PID: 22648
                                                               android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ebuy.shop/com.ebuy.shop.ui.activity.PersonalBusinessDetailsActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1788)
                                                                   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                                                                   at android.app.Activity.startActivityForResult(Activity.java:3856)
                                                                   at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                                   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                   at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:28)
                                                                   at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:143)
                                                                   at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:781)
                                                                   at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:896)
                                                                   at android.support.v4.app.Fragment.startActivity(Fragment.java:981)
                                                                   at android.support.v4.app.Fragment.startActivity(Fragment.java:970)
                                                                   at com.ebuy.shop.ui.fragment.PersonalBusinessFragment$2.onItemClick(PersonalBusinessFragment.java:95)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter$5.onClick(BaseQuickAdapter.java:956)
                                                                   at android.view.View.performClick(View.java:4848)
                                                                   at android.view.View$PerformClick.run(View.java:20300)
                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

2.这是第二个问题
在build.gradle 配置好以后,偶尔报出这个错误, 不过能够正常运行
E/ActivityThread: Performing stop of activity that is not resumed: {com.chad.baserecyclerviewadapterhelper/com.chad.baserecyclerviewadapterhelper.HomeActivity}
                                                                                      java.lang.RuntimeException: Performing stop of    activity that is not resumed: {com.chad.baserecyclerviewadapterhelper/com.chad.baserecyclerviewadapterhelper.HomeActivity}at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3633)
                                                                                          at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3722)
                                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:182)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1522)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                                          at

**Comment by CymChad** [comment]
ActivityNotFoundException的问题和adapter没啥关系吧？

**Comment by OpenSourceMIUI** [comment]
第一个问题解决了, RecyclerView 的 item 跳转到指定activity的时候, 必须指定全包名! 全包名! 全包名!  
重要的事说三遍
例如: 包名为: com.baidu.app
而你所写的activity的所在全包名为:  com.baidu.app.ui.activity      而不要这样写:  .ui.activity

**Comment by CymChad** [comment]
👍 @OpenSourceMIUI
