### ISSUE TITLE
如果列表太多了,出现这个异常会卡顿NoSuchMethodException,麻烦看一下

### ISSUE THREAD

**Issue by luxiao0314** [CymChad/BaseRecyclerViewAdapterHelper#1536]
这个问题现在还有吗,没使用内部类,我这边出现了,也是最新的包,如果列表太多了,出现这个异常会卡顿
java.lang.NoSuchMethodException: [class android.view.View]
at java.lang.Class.getConstructor(Class.java:528)
at java.lang.Class.getDeclaredConstructor(Class.java:507)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1034)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1012)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:989)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:985)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:762)
at com.mvvm.lux.framework.manager.recycler.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:70)

**Comment by CymChad** [comment]
你的版本，以及复现的方式是？

**Comment by CymChad** [comment]
你先更新一下版本试一下，然后还有问题，请信息描述复现场景，这样便于我们更快的找到问题从而解决问题。
