### ISSUE TITLE
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>

### ISSUE THREAD

**Issue by Arvin3377** [CymChad/BaseRecyclerViewAdapterHelper#1548]
使用版本是2.9.22。目前出现在4.2和4.4的手机上，5.0以上的手机没有出现过这个问题。下面是具体错误信息，多谢指导。
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1470)
	at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:987)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:983)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:759)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
	at android.view.View.measure(View.java:16532)
	at android.widget.RelativeLayout.measureChild(RelativeLayout.java:689)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:473)
	at android.view.View.measure(View.java:16532)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16532)
	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2341)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1919)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5713)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5120)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 80 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ripple_list_item.xml from drawable resource ID #0x7f0200a8
	at android.content.res.Resources.loadDrawable(Resources.java:2233)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.<init>(View.java:3554)
	at android.view.View.<init>(View.java:3484)
	at android.view.ViewGroup.<init>(ViewGroup.java:464)
	at android.widget.RelativeLayout.<init>(RelativeLayout.java:236)
	... 83 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag ripple
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2229)
	... 88 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1470)
	at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:987)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:983)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:759)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
	at android.view.View.measure(View.java:16532)
	at android.widget.RelativeLayout.measureChild(RelativeLayout.java:689)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:473)
	at android.view.View.measure(View.java:16532)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5136)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16532)
	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
	at android.view.View.measure(View.java:16532)
	at android.view.ViewGroup.me

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/441
