### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sungerk** [CymChad/BaseRecyclerViewAdapterHelper#1554]
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:413)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItem(BaseQuickAdapter.java:608)
	at $3.onItemChildClick(BatchInboundActivity.java:173)
	at com.chad.library.adapter.base.BaseViewHolder$1.onClick(BaseViewHolder.java:374)

**Comment by CymChad** [comment]
版本号，复现场景？
