### ISSUE TITLE
使用了onCreateViewHolder 多布局，getOnItemChildClickListener()' on a null object reference

### ISSUE THREAD

**Issue by oyxygbd** [CymChad/BaseRecyclerViewAdapterHelper#1572]
java.lang.NullPointerException: Attempt to invoke virtual method 'com.chad.library.adapter.base.BaseQuickAdapter$OnItemChildClickListener com.chad.library.adapter.base.BaseQuickAdapter.getOnItemChildClickListener()' on a null object reference
                                                                 at com.chad.library.adapter.base.BaseViewHolder$1.onClick(BaseViewHolder.java:389)
                                                                 at android.view.View.performClick(View.java:5611)
                                                                 at android.view.View$PerformClick.run(View.java:22276)
                                                                 at android.os.Handler.handleCallback(Handler.java:754)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:160)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by AllenCoder** [comment]
请提供更详细的代码，以及BaseRecyclerViewAdapterHelper 版本号？最好有复现Demo ,方便排查问题

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1591  提问请看这个，如果还有问题请重新提一个issues。
