### ISSUE TITLE
popup menu not working

### ISSUE THREAD

**Issue by creativelabsofficial** [CymChad/BaseRecyclerViewAdapterHelper#1617]
I trued to create popup menu but its not working ? 

My Code for Popup menu

`mAdaptorRecycleViewAdaptor.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {

                PopupMenu popupmenu = new PopupMenu(virtual_location_select.this.getApplicationContext(),view);
                //popupmenu.getMenuInflater().inflate(R.menu.location_menu,popupmenu.getMenu());
                popupmenu.inflate(R.menu.location_menu);
                popupmenu.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener(){

                    @Override
                    public boolean onMenuItemClick(MenuItem item) {
                        switch (item.getItemId()) {
                            case R.id.LM_DefaultLocation:
                                // your first action code
                                Toast.makeText(virtual_location_select.this, "Default Location", Toast.LENGTH_SHORT).show();
                                return true;
                            case R.id.LM_CustomLocation:
                                // your second action code
                                Toast.makeText(virtual_location_select.this, "Custom Location", Toast.LENGTH_LONG).show();
                                return true;
                            default:
                                return false;
                        }
                    }
                });

                popupmenu.show();

            }
        });
`

Here is Stack Trace 

`10-09 12:46:51.766 9065-9065/com.creationlabs.secondspace.secondspace E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.creationlabs.secondspace.secondspace, PID: 9065
                                                                                        android.view.InflateException: Binary XML file line #17: Failed to resolve attribute at index 6: TypedValue{t=0x1d/d=0xffff4081 a=5 r=0x7f0c0017}
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                            at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:93)
                                                                                            at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:160)
                                                                                            at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:153)
                                                                                            at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187)
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290)
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:175)
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:141)
                                                                                            at android.support.v7.widget.PopupMenu.show(PopupMenu.java:233)
                                                                                            at com.creationlabs.secondspace.secondspace.location.virtual_location_select$1.onItemClick(virtual_location_select.java:91)
                                                                                            at com.chad.library.adapter.base.BaseQuickAdapter$5.onClick(BaseQuickAdapter.java:956)
                                                                                            at android.view.View.performClick(View.java:5207)
                                                                                            at android.view.View$PerformClick.run(View.java:21177)
                                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                                         Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x1d/d=0xffff4081 a=5 r=0x7f0c0017}
                                                                                            at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:707)
                                                                                            at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6891)
                                                                                            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7072)
                                                                                            at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:446)
                                                                                            at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:386)
                                                                                            at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:59)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:506)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                            at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:93) 
                                                                                            at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:160) 
                                                                                            at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:153) 
                                                                                            at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187) 
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290) 
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:175) 
                                                                                            at android.support.v7.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:141) 
                                                                                            at android.support.v7.widget.PopupMenu.show(PopupMenu.java:233) 
                                                                                            at com.creationlabs.secondspace.secondspace.location.virtual_location_select$1.onItemClick(virtual_location_select.java:91) 
                                                                                            at com.chad.library.adapter.base.BaseQuickAdapter$5.onClick(BaseQuickAdapter.java:956) 
                                                                                            at android.view.View.performClick(View.java:5207) 
                                                                                            at android.view.View$PerformClick.run(View.java:21177) 
                                                                                            at android.os.Handler.handleCallback(Handler.java:742) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5527) `

**Comment by CymChad** [comment]
Please check your MenuAdapter. Java: 93 And your layout problem
