### ISSUE TITLE
和XRecyclerView有冲突

### ISSUE THREAD

**Issue by STGing** [CymChad/BaseRecyclerViewAdapterHelper#1629]
最近开始新增下拉刷新和上拉加载，将原来项目中的RecyclerView替换为XRecyclerView，结果app一打开就奔溃。

当前使用版本：2.9.22

奔溃日志如下：（主要是XRecyclerView$WrapAdapter$SimpleViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolder 这一句。）

java.lang.ClassCastException: com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter$SimpleViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolder
                                                                                               at com.chad.library.adapter.base.BaseQuickAdapter.onViewAttachedToWindow(BaseQuickAdapter.java:68)
                                                                                               at datang.lianzhonghulian.com.datang_android.ui.tangstore.adapter.TangStoreRVAdapter.onViewAttachedToWindow(TangStoreRVAdapter.java:65531)
                                                                                               at com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onViewAttachedToWindow(XRecyclerView.java:515)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6789)
                                                                                               at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:706)
                                                                                               at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7728)
                                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7686)
                                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7674)
                                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1547)
                                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                               at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                               at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                               at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                               at android.view.View.layout(View.java:17548)
10-12 17:34:07.588 25917-25917/datang.lianzhonghulian.com.datang_android E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                               at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                                                               at android.view.View.layout(View.java:17548)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5614)
                                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2388)
                                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2115)
                                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
                                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6368)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                                               at android.os.Handler.handleCallback(Handler.java:754)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:163)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by CymChad** [comment]
这个库并做过任何兼容XRecyclerView的适配，因为XRecyclerView已经放弃更新了。我看了下XRecyclerView有200+个issues。建议换掉XRecyclerView

**Comment by STGing** [comment]
好的，谢谢！
