### ISSUE TITLE
在添加了头布局,如果返回的列表数据为空的时候,调用 mBaseQuickAdapter.setEmptyView(R.layout.empty_comment_view);会报错!

### ISSUE THREAD

**Issue by keaitao0321** [CymChad/BaseRecyclerViewAdapterHelper#1655]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1d9366f1 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

**Comment by CymChad** [comment]
setEmptyView应该一开始初始化就设置，不需要为空时才设置。

**Comment by keaitao0321** [comment]
在哪里初始化?

**Comment by CymChad** [comment]
设置adapter的设置

**Comment by keaitao0321** [comment]
没找到在哪里设置?
还有怎么显示空布局

**Comment by CymChad** [comment]
你可以看下demo源码，一开始设置了空布局，它自动会检测没有数据则自动显示。

**Comment by keaitao0321** [comment]
找到了,谢谢.
我还想知道我只更新列表一条数据要怎么操作

**Comment by CymChad** [comment]
可以你可以查查rv 局部更新的函数，这个是原始自带的。

**Comment by Jiiiiiin** [comment]
那如何根据不同的错误显示不同的提示界面呢？
@CymChad

**Comment by Jiiiiiin** [comment]
看了 demo中也是动态设置的呀？

```java

    private void onRefresh() {
        mQuickAdapter.setEmptyView(R.layout.loading_view, (ViewGroup) mRecyclerView.getParent());
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                if (mError) {
                    mQuickAdapter.setEmptyView(errorView);
                    mError = false;
                } else {
                    if (mNoData) {
                        mQuickAdapter.setEmptyView(notDataView);
                        mNoData = false;
                    } else {
                        mQuickAdapter.setNewData(DataServer.getSampleData(10));
                    }
                }
            }
        }, 1000);
    }
```

**Comment by Jiiiiiin** [comment]
```bash
roidRuntime: Shutting down VM
06-14 21:06:55.710 3198-3335/com.csii.mobilebank D/JIGUANG-JCore: [HttpHelper] status code:200
06-14 21:06:55.712 3198-3198/com.csii.mobilebank E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.csii.mobilebank, PID: 3198
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1a3e7286 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{3cb3889d VFED.... ......ID 0,0-1440,1994 #7f080281 app:id/rv_list}, adapter:com.csii.mobilebank.ynrcc.delegate.personal.PersonalCenterDelegateAdapter@127f3112, layout:android.support.v7.widget.LinearLayoutManager@270790e3, context:com.csii.mobilebank.MainActivity@a278db6
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:676)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1644)
        at android.support.v7.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1498)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
    	at android.widg
```


```java

    private void _initAdapter(BaseQuickAdapter.OnItemClickListener onItemClickListener) {
        mPersonalCenterDelegateAdapter = new PersonalCenterDelegateAdapter(this, R.layout.item_section_content, R.layout.include_comm_split);
        mPersonalCenterDelegateAdapter.openLoadAnimation();
        mDelegatePersonalCenterTopView = getLayoutInflater().inflate(R.layout.delegate_personal_center_header_view, (ViewGroup) mRecyclerView.getParent(), false);
        mPersonalCenterDelegateAdapter.addHeaderView(mDelegatePersonalCenterTopView);
        mPersonalCenterDelegateAdapter.setOnItemClickListener(onItemClickListener);
        mNotDataView = getLayoutInflater().inflate(R.layout.empty_view, (ViewGroup) mRecyclerView.getParent(), false);
        mNotDataView.setOnClickListener(v -> _getData(mSmartRefreshLayout));
        mErrorView = getLayoutInflater().inflate(R.layout.error_view, (ViewGroup) mRecyclerView.getParent(), false);
        mErrorView.setOnClickListener(v -> _getData(mSmartRefreshLayout));

        mRecyclerView.setAdapter(mPersonalCenterDelegateAdapter);
    }


    private void _getData(RefreshLayout refreshLayout) {
        RestOkHttpUtilsClient.builder(_mActivity)
                .url(ViewPlus.getConfiguration(ConfigKeys.WEB_HOST).toString().concat("static/AppHomeData/MeFuncData.jsonn"))
                .success(res -> {
                    try {
                        mPersonalCenterDelegateAdapter.setNewData(PersonalCenterListItemSection.convert(res));
                        refreshLayout.finishRefresh();
                    } catch (ViewPlusException e) {
                        LoggerProxy.e(e, "解析PersonalCenterListItemSection.convert出错");
                        // 没有数据的时候默认显示该布局
                        mPersonalCenterDelegateAdapter.setEmptyView(getView());
                        ToastUtils.showLong(e.getMessage());
                    }
                })
                .failure(() -> this._finishLoadData(null))
                .error(this::_finishLoadData)
                .build()
                .get();
    }

    private void _finishLoadData(String err) {
        if (StringUtils.isTrimEmpty(err)) {
            mPersonalCenterDelegateAdapter.setEmptyView(mNotDataView);
        } else {
            mPersonalCenterDelegateAdapter.setEmptyView(mNotDataView);
        }
        mSmartRefreshLayout.finishRefresh();
    }

```

直接copy了demo中对应的用法 还是一样报错

**Comment by Jiiiiiin** [comment]
解决了，如下：
![](https://ws3.sinaimg.cn/large/006tNc79gy1fsk236bzyvj318i18q4na.jpg)
不使用addHeaderView添加头部，就不会报上面的问题

**Comment by squareBQ** [comment]
有`headerView`时刷新数据，根据`headerView`的情况来刷新 ：[solution link](https://github.com/wasabeef/recyclerview-animators/issues/12#issuecomment-238452269)

```java
adapter.replaceData(list);
adapter.notifyItemRangeChanged(adapter.getHeaderLayoutCount(), list.size());
```

**Comment by XuMengren** [comment]
> 看了 demo中也是动态设置的呀？
> 
> ```java
>     private void onRefresh() {
>         mQuickAdapter.setEmptyView(R.layout.loading_view, (ViewGroup) mRecyclerView.getParent());
>         new Handler().postDelayed(new Runnable() {
>             @Override
>             public void run() {
>                 if (mError) {
>                     mQuickAdapter.setEmptyView(errorView);
>                     mError = false;
>                 } else {
>                     if (mNoData) {
>                         mQuickAdapter.setEmptyView(notDataView);
>                         mNoData = false;
>                     } else {
>                         mQuickAdapter.setNewData(DataServer.getSampleData(10));
>                     }
>                 }
>             }
>         }, 1000);
>     }
> ```

这是动态设置特殊的布局，你看名称一个是error，一个是noData
