### ISSUE TITLE
2.3.3版本 ArrayIndexOutOfBoundsException: length=14; index=-2

### ISSUE THREAD

**Issue by yuxinLi** [CymChad/BaseRecyclerViewAdapterHelper#1663]
java.lang.ArrayIndexOutOfBoundsException: length=14; index=-2
	at java.util.ArrayList.get(ArrayList.java:413)
	at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getDefItemViewType(BaseMultiItemQuickAdapter.java:35)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:467)
	at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:233)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$002(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$102(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$100(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$402(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SimpleClickListener.java:112)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:638)
	at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
	at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
	at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:50)
	at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2658)
	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2786)
	at android.view.View.dispatchTouchEvent(View.java:10012)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)

**Comment by yuxinLi** [comment]
OnItemChildClickListener.SimpleOnItemChildClick  这个方法 index 也会有个 -2 冒出来

**Comment by AllenCoder** [comment]
点击事件版本切换到 adapter.setOnItemClickListener(listener) 
//注释掉原来的recyclerview.addItemTouchListener(listener)接口试试

**Comment by yuxinLi** [comment]
1.    
2.3.3 版本没有 BaseItemDraggableAdapter.setOnItemClickListener 方法

2. 
getDefItemViewType 返回-2 。

**Comment by CymChad** [comment]
请更新版本在尝试一下。
