### ISSUE TITLE
RecyclerView内部出现IndexOutOfBoundsException

### ISSUE THREAD

**Issue by cc365774016** [CymChad/BaseRecyclerViewAdapterHelper#1664]
1.出现BUG版本2.9.30
2.当有下拉刷新和加载更多的时候，反复快速的下拉，上拉重复大概几次10多次后出现 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:9).state:10
3.DEMO百度网盘地址：https://pan.baidu.com/s/1dESO3UL  提取码 k4kr 
4.manifest忘记给activity加屏幕方向是横屏的限制了。需要加哈
  Process: ysy.recyclerviewtestdemo, PID: 14864
                                                                          java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:9).state:10
                                                                              at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5458)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                              at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                              at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1313)
                                                                              at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1058)
                                                                              at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:381)
                                                                              at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4680)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:899)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:701)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:633)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:885)
                                                                              at android.os.Handler.handleCallback(Handler.java:815)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                              at android.os.Looper.loop(Looper.java:207)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5966)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by androidscx** [comment]
我也 是2.9.30 同样的问题

**Comment by cc365774016** [comment]
我当时出现这个问题，是因为我自己用法问题。

**Comment by cc365774016** [comment]
你有QQ吗，我们可以QQ上聊，你加我QQ，我当时出现这个问题是因为我是老版本，换新版本，然后用法出现问题，所以出现了这个错


------------------ 原始邮件 ------------------
发件人: "androidscx";<notifications@github.com>;
发送时间: 2017年12月12日(星期二) 中午1:51
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "﹎熌喨ζ﹎蹬"<365774016@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] RecyclerView内部出现IndexOutOfBoundsException (#1664)




我也 是2.9.30 同样的问题

**Comment by FriendLin** [comment]
我换上了2.9.34  这个问题还是出现 我的是 有headview的时候反复的下拉 上拉出现的这个java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position  21(offset: 21).state:22

**Comment by zhengjieAdriod** [comment]
@FriendLin  现在解决了吗

**Comment by FriendLin** [comment]
@zhengjieAdriod 记得是，当时我的代码编写有误。现在没问题了
public class LoadMoreHelper {
     // 处理成功的数据 
   public static <L, A extends BaseQuickAdapter<L, BaseViewHolder>> int handleSuccessData(int start_page, A adapter, List<L> dataList) {
      if (start_page == 1) {
            //设置新数据
            adapter.setNewData(dataList);
            if (dataList.size() < 10) {
                adapter.loadMoreEnd();
            } else {
                start_page++;
                adapter.loadMoreComplete();
                adapter.setEnableLoadMore(true);
            }
        } else {
            if (dataList.size() == 0) {
                adapter.setEnableLoadMore(false);
            } else {
                adapter.addData(dataList);
                if (dataList.size() < 10) {
                    adapter.loadMoreEnd();
                    adapter.setEnableLoadMore(false);
                } else {
                    start_page++;
                    adapter.loadMoreComplete();
                }
            }

       }
        return start_page;
    }

    /**
     * 处理失败的数据
     */
    public static <A extends BaseQuickAdapter> void handleFailedData(int page, A adapter) {
        if (page > 1) {
            adapter.loadMoreFail();
        }
    }

**Comment by axkza** [comment]
> @zhengjieAdriod 记得是，当时我的代码编写有误。现在没问题了
> 
> public class LoadMoreHelper {
> 
> ```
> /**
>  * 处理成功的数据
>  */
> 
> public static <L, A extends BaseQuickAdapter<L, BaseViewHolder>> int handleSuccessData(int start_page, A adapter, List<L> dataList) {
> 
>     if (start_page == 1) {
>         //设置新数据
>         adapter.setNewData(dataList);
>         if (dataList.size() < 10) {
>             adapter.loadMoreEnd();
>         } else {
>             start_page++;
>             adapter.loadMoreComplete();
>             adapter.setEnableLoadMore(true);
>         }
> 
>     } else {
>         if (dataList.size() == 0) {
>             adapter.setEnableLoadMore(false);
>         } else {
>             adapter.addData(dataList);
>             if (dataList.size() < 10) {
>                 adapter.loadMoreEnd();
>                 adapter.setEnableLoadMore(false);
>             } else {
>                 start_page++;
>                 adapter.loadMoreComplete();
>             }
>         }
> 
>     }
>     return start_page;
> }
> 
> /**
>  * 处理失败的数据
>  */
> public static <A extends BaseQuickAdapter> void handleFailedData(int page, A adapter) {
>     if (page > 1) {
>         adapter.loadMoreFail();
>     }
> }
> ```
> }

你好，你用了这个代码之后就没再出现过IndexOutOfBoundsException的问题了吗？

**Comment by FriendLin** [comment]
> > @zhengjieAdriod 记得是，当时我的代码编写有误。现在没问题了
> > public class LoadMoreHelper {
> > ```
> > /**
> >  * 处理成功的数据
> >  */
> > 
> > public static <L, A extends BaseQuickAdapter<L, BaseViewHolder>> int handleSuccessData(int start_page, A adapter, List<L> dataList) {
> > 
> >     if (start_page == 1) {
> >         //设置新数据
> >         adapter.setNewData(dataList);
> >         if (dataList.size() < 10) {
> >             adapter.loadMoreEnd();
> >         } else {
> >             start_page++;
> >             adapter.loadMoreComplete();
> >             adapter.setEnableLoadMore(true);
> >         }
> > 
> >     } else {
> >         if (dataList.size() == 0) {
> >             adapter.setEnableLoadMore(false);
> >         } else {
> >             adapter.addData(dataList);
> >             if (dataList.size() < 10) {
> >                 adapter.loadMoreEnd();
> >                 adapter.setEnableLoadMore(false);
> >             } else {
> >                 start_page++;
> >                 adapter.loadMoreComplete();
> >             }
> >         }
> > 
> >     }
> >     return start_page;
> > }
> > 
> > /**
> >  * 处理失败的数据
> >  */
> > public static <A extends BaseQuickAdapter> void handleFailedData(int page, A adapter) {
> >     if (page > 1) {
> >         adapter.loadMoreFail();
> >     }
> > }
> > ```
> > }
> 
> 你好，你用了这个代码之后就没再出现过IndexOutOfBoundsException的问题了吗？

现在一直用，没什么问题
