### ISSUE TITLE
加载更多的时候没有设置延时会报IllegalStateException

### ISSUE THREAD

**Issue by cs1151355296** [CymChad/BaseRecyclerViewAdapterHelper#1731]
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView
                                                                        at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2663)
                                                                        at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5074)
                                                                        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11564)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6905)
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.addData(BaseQuickAdapter.java:560)

**Comment by CymChad** [comment]
恩 是的 因为加载太快了，设置加载更多监听有一个重载方法就是多传入一个rv对象，你可以使用这个重载方法做了处理。
