### ISSUE TITLE
有关多类型内部Rv嵌套事件冲突

### ISSUE THREAD

**Issue by Troll4it** [CymChad/BaseRecyclerViewAdapterHelper#1738]
@AllenCoder  你好，这是我项目中的报的错，请问在什么情况报，有那些解决方法，谢谢

1-14 16:58:12.597 11298-11298/? E/InputEventReceiver: Exception dispatching input event.
11-14 16:58:12.598 11298-11298/? D/AndroidRuntime: Shutting down VM
11-14 16:58:12.602 11298-11298/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.xxxxx.xxxxxxx, PID: 11298
                                                   android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
                                                       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
                                                       at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
                                                       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2153)
                                                       at android.content.res.Resources.getLayout(Resources.java:1159)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:428)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1483)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:989)
                                                       at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:51)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:762)
                                                       at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1313)
                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1058)
                                                       at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1680)
                                                       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2837)
                                                       at android.view.View.dispatchTouchEvent(View.java:9955)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3196)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
                                                       at android.view.View.dispatchPointerEvent(View.java:10177)
11-14 16:58:12.603 11298-11298/? E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4497)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4362)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3902)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3955)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3921)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4048)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3929)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4105)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3902)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3955)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3921)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3929)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3902)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6273)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6247)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6208)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6379)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
                                                       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6347)
                                                       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6402)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:615)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                       at android.os.Handler.handleCallback(Handler.java:754)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by Troll4it** [comment]
已经找到这个BUG为什么出现了，但是不解的是：在多类型是，当某一类型有数据时但是没有没有此类型的布局就会出现这个问题，为什么会这样

**Comment by CymChad** [comment]
因为是一一对应的关系，如果你在adapter构造注册了这个type和layout的绑定关系，原理就会更具数据的type值去找相关的layoutid，没有就会出现找不到的问题。
