### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by XTaoWang** [CymChad/BaseRecyclerViewAdapterHelper#18]
Process: com.chad.baserecyclerviewadapterhelper, PID: 3219
                                                                                      java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{110301db position=13 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4505)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                          at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
                                                                                          at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
                                                                                          at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1529)
                                                                                          at android.support.v7.widget.RecyclerView.onGenericMotionEvent(RecyclerView.java:2578)
                                                                                          at android.view.View.dispatchGenericMotionEventInternal(View.java:8493)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8474)
                                                                                          at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2024)
                                                                                          at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1975)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8467)
                                                                                          at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2024)
                                                                                          at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1975)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8467)
                                                                                          at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2024)
                                                                                          at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1975)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8467)
                                                                                          at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2024)
                                                                                          at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1975)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8467)
                                                                                          at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2024)
                                                                                          at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1975)
                                                                                          at android.view.View.dispatchGenericMotionEvent(View.java:8467)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2322)
                                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1702)
                                                                                          at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2775)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2289)
                                                                                          at android.view.View.dispatchPointerEvent(View.java:8580)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
                                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
                                                                                      	at android.view.ViewRootImpl.doProcessInputEvents(ViewRo

**Comment by CymChad** [comment]
这个bug和 #16  一样，你可以参考一下 里面的解决方案。
