### ISSUE TITLE
自定义ViewHolder 继承于BaseViewHolder 出现  ClassCastException异常

### ISSUE THREAD

**Issue by papastar** [CymChad/BaseRecyclerViewAdapterHelper#1829]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to org.redcross.data.common.CommonViewHolder
                                                     at org.redcross.ui.activity.ItemListActivity$1.convert(ItemListActivity.java:37)
                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:927)
                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                     at android.support.v7.widget.RecyclerView$a.onBindViewHolder(RecyclerView.java:6356)
                                                     at android.support.v7.widget.RecyclerView$a.bindViewHolder(RecyclerView.java:6389)
                                                     at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5335)
                                                     at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5598)
                                                     at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5440)
                                                     at android.support.v7.widget.RecyclerView$o.c(RecyclerView.java:5436)
                                                     at android.support.v7.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:2224)
                                                     at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1551)
                                                     at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1511)
                                                     at android.support.v7.widget.LinearLayoutManager.c(LinearLayoutManager.java:595)
                                                     at android.support.v7.widget.RecyclerView.N(RecyclerView.java:3583)
                                                     at android.support.v7.widget.RecyclerView.p(RecyclerView.java:3312)
                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                     at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
                                                     at android.view.View.layout(View.java:17688)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2513)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:735)
12-14 11:19:25.731 3732-3732/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                     at android.os.Handler.handleCallback(Handler.java:761)
                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                     at android.os.Looper.loop(Looper.java:156)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by a709764117** [comment]
同样的报错刚解决 
自定义ViewHolder类里 成员变量回调接口为未初始化

原先if语句放外面

if( onClickListener.isRight()){                     // onClickListener为自定义ViewHolder类的成员变量
                  rightMsg.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                            //do something
                    }
                });
} 

改为

if语句放里面 

                  rightMsg.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                         if( onClickListener.isRight()){  
                            //do something
                         } 
                    }
                });

希望对你有帮助

**Comment by CymChad** [comment]
版本号？

**Comment by GadusBetter** [comment]
应该是混淆的问题吧，我也遇到这个问题了，但是写成内部类就好使了

**Comment by AllenCoder** [comment]
混淆问题，自定义viewholder必须是公开 静态内部类 ，并加入混淆规则

**Comment by lhholylight** [comment]
我也出现了这样的问题，debug包，没开混淆，版本2.9.34

**Comment by wecodexyz** [comment]
加了混淆规则，貌似还是出现这个错误

**Comment by caldremch** [comment]
#添加以下混淆规则可解决
#保留继承于BaseViewHolder的内部类不被混淆
-keep class $ extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
(...);
}

**Comment by SirBad** [comment]
#添加以下混淆规则可解决
#保留继承于BaseViewHolder的内部类不被混淆
-keep class $ extends com.chad.library.adapter.base.viewholder.BaseViewHolder {

}
并且多布局会存在这个问题
