### ISSUE TITLE
线上bug

### ISSUE THREAD

**Issue by andy91310** [CymChad/BaseRecyclerViewAdapterHelper#1834]
这是线上友盟统计的bug，影响的用户有点多，实在是看不出来哪里的问题？
求大神帮忙分析下。

- android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.ProgressBar
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1483)
	at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:771)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:750)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5689)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

- Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	... 27 more

- Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	at android.util.ArrayMap.allocArrays(ArrayMap.java:187)
	at android.util.ArrayMap.put(ArrayMap.java:459)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1055)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1065)
	at android.graphics.drawable.VectorDrawable$VPathRenderer.<init>(VectorDrawable.java:840)
	at android.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:664)
	at android.graphics.drawable.VectorDrawable.mutate(VectorDrawable.java:224)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:351)
	at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
	at android.content.res.Resources.loadDrawable(Resources.java:2659)
	at android.content.res.HwResources.loadDrawable(HwResources.java:619)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:788)
	at android.widget.ProgressBar.<init>(ProgressBar.java:310)
	at android.widget.ProgressBar.<init>(ProgressBar.java:265)
	at android.widget.ProgressBar.<init>(ProgressBar.java:261)
	... 30 more

- java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1483)
	at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:771)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:750)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5689)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

- Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	at android.util.ArrayMap.allocArrays(ArrayMap.java:187)
	at android.util.ArrayMap.put(ArrayMap.java:459)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1055)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1065)
	at android.graphics.drawable.VectorDrawable$VPathRenderer.<init>(VectorDrawable.java:840)
	at android.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:664)
	at android.graphics.drawable.VectorDrawable.mutate(VectorDrawable.java:224)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:351)
	at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
	at android.content.res.Resources.loadDrawable(Resources.java:2659)
	at android.content.res.HwResources.loadDrawable(HwResources.java:619)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:788)
	at android.widget.ProgressBar.<init>(ProgressBar.java:310)
	at android.widget.ProgressBar.<init>(ProgressBar.java:265)
	at android.widget.ProgressBar.<init>(ProgressBar.java:261)
	... 30 more

- java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Object[]
	at android.util.ArrayMap.allocArrays(ArrayMap.java:187)
	at android.util.ArrayMap.put(ArrayMap.java:459)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1055)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1065)
	at android.graphics.drawable.VectorDrawable$VPathRenderer.<init>(VectorDrawable.java:840)
	at android.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:664)
	at android.graphics.drawable.VectorDrawable.mutate(VectorDrawable.java:224)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:351)
	at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
	at android.content.res.Resources.loadDrawable(Resources.java:2659)
	at android.content.res.HwResources.loadDrawable(HwResources.java:619)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:788)
	at android.widget.ProgressBar.<init>(ProgressBar.java:310)
	at android.widget.ProgressBar.<init>(ProgressBar.java:265)
	at android.widget.ProgressBar.<init>(ProgressBar.java:261)
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1483)
	at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:771)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:750)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
	at android.supp

**Comment by AllenCoder** [comment]
猜测你可能是用了 VectorDrawable ，在部分机型部分系统版本下会发生崩溃不兼容

**Comment by AllenCoder** [comment]
在基类BaseActivity 里面加上这个试试

```

    /*
     * 解决Vector兼容性问题
     *
     * First up, this functionality was originally released in 23.2.0,
     * but then we found some memory usage and Configuration updating
     * issues so we it removed in 23.3.0. In 23.4.0 (technically a fix
     * release) we’ve re-added the same functionality but behind a flag
     * which you need to manually enable.
     */
    static {
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }
```

**Comment by andy91310** [comment]
好的，万分感谢，我试试呢

**Comment by andy91310** [comment]
我刚查了下你说的这个问题，这个错误我看了下统计，只有5.0以上版本才有这个错误呢。

**Comment by CymChad** [comment]
没有复现方法这个错误很难定位

**Comment by weiweiForAndroid** [comment]
> 没有复现方法这个错误很难定位

我也遇到了～～～在华为手机上可以复现
