### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by yang-mr** [CymChad/BaseRecyclerViewAdapterHelper#1837]
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling android.support.v7.widget.RecyclerView{bcd9fb5 VFED..... ......ID 0,0-720,836 #7f0a0282 app:id/recyclerView}, layout:android.support.v7.widget.LinearLayoutManager@9dd1342, 
                                                                            at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2663)
                                                                            at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5074)
                                                                            at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:11564)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6905)
                                                                            at com.chad.library.adapter.base.BaseQuickAdapter.addData(BaseQuickAdapter.java:560)

**Comment by CymChad** [comment]
版本，以及复现操作

**Comment by yang-mr** [comment]
最新版本  我是用本地数据 模拟测试的

**Comment by CymChad** [comment]
怎么操作的？

**Comment by yangyueyue** [comment]
也遇到同样问题

**Comment by hudan2714** [comment]
有解决吗？

**Comment by 1226362423** [comment]
怎么解决的啊

**Comment by dongliwu520** [comment]
有人解决了吗？我是在添加一条数据完成后的onAddFinished()  里又执行了  mAdapter?.addData(0, data) 就出现了该问题
