### ISSUE TITLE
Inconsistency detected

### ISSUE THREAD

**Issue by NutBear** [CymChad/BaseRecyclerViewAdapterHelper#1858]

**Comment by NutBear** [comment]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3813e88 position=3 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                                               at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                               at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                               at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                               at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                               at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                               at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by NutBear** [comment]
有人遇到过吗 用了上拉加载

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/1689
