### ISSUE TITLE
代码没有报错 但是出现警告 java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by XiongKe94** [CymChad/BaseRecyclerViewAdapterHelper#1880]
代码:
```
2-28 16:39:59.598 9131-9131/com.xk.gvido.app.debug W/System.err: java.lang.reflect.InvocationTargetException
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1051)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1031)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:772)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:750)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
12-28 16:39:59.599 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1570)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:682)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.view.View.layout(View.java:16636)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.view.View.layout(View.java:16636)
12-28 16:39:59.600 9131-9131/com.xk.gvido.app.debug W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
```

```
public class GankPictureAdapter extends BaseQuickAdapter<GanHuoBean, GankPictureAdapter.GankPictureViewHolder> {
    private Activity activity;

    public GankPictureAdapter(Activity activity, @Nullable List<GanHuoBean> data) {
        super(R.layout.item_frag_gank_picture, data);
        this.activity = activity;
    }

    @Override
    protected void convert(GankPictureViewHolder helper, GanHuoBean item) {
        helper.updateView(item);
    }

    public class GankPictureViewHolder extends IBaseViewHolder {
        @BindView(R.id.welfare_image_view)
        ImageView welfareImageView;
        @BindView(R.id.welfare_title_tv)
        TextView welfareTitleTv;

        public GankPictureViewHolder(View view) {
            super(view);
        }

        @Override
        public <T> void updateView(T dateItem) {
            if (dateItem instanceof GanHuoBean) {
                GanHuoBean ganHuoBean = (GanHuoBean) dateItem;
                GlideUtils.loadImage(mContext, ganHuoBean.getImageUrl(), welfareImageView, GlideUtils.imageDefaultOptions(R.drawable.default_app_icon));
                welfareTitleTv.setText(String.format("%s  %s", ganHuoBean.getDate(), ganHuoBean.getTitle()));
                welfareTitleTv.setOnClickListener(view -> LaunchUtils.startWebViewActivity(activity, ganHuoBean));
                welfareImageView.setOnClickListener(view -> LaunchUtils.startPictureActivity(activity, view,
                        new PictureBean(ganHuoBean.getImageUrl(), ganHuoBean.getTitle())));
            }
        }
    }
}
```
```
public abstract class IBaseViewHolder extends BaseViewHolder {
    public IBaseViewHolder(View view) {
        super(view);
        ButterKnife.bind(this, view);
    }

    public abstract <T> void updateView(T dateItem);
}
```

**Comment by XiongKe94** [comment]
代码没有报错 但是出现警告

**Comment by AllenCoder** [comment]
自定义viewholder 请修改为如下带， 

```
  public static class GankPictureViewHolder extends IBaseViewHolder {
        @BindView(R.id.welfare_image_view)
        ImageView welfareImageView;
        @BindView(R.id.welfare_title_tv)
        TextView welfareTitleTv;

        public GankPictureViewHolder(View view) {
            super(view);
        }

        @Override
        public <T> void updateView(T dateItem) {
            if (dateItem instanceof GanHuoBean) {
                GanHuoBean ganHuoBean = (GanHuoBean) dateItem;
                GlideUtils.loadImage(mContext, ganHuoBean.getImageUrl(), welfareImageView, GlideUtils.imageDefaultOptions(R.drawable.default_app_icon));
                welfareTitleTv.setText(String.format("%s  %s", ganHuoBean.getDate(), ganHuoBean.getTitle()));
                welfareTitleTv.setOnClickListener(view -> LaunchUtils.startWebViewActivity(activity, ganHuoBean));
                welfareImageView.setOnClickListener(view -> LaunchUtils.startPictureActivity(activity, view,
                        new PictureBean(ganHuoBean.getImageUrl(), ganHuoBean.getTitle())));
            }
        }
    }
```
另外，如果开启混淆和代码压缩请加入 proguard文件 

```
-keep class com.chad.library.adapter.** {
*;
}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
-keep public class * extends com.chad.library.adapter.base.BaseViewHolder
-keepclassmembers  class **$** extends com.chad.library.adapter.base.BaseViewHolder {
     <init>(...);
}
```
