### ISSUE TITLE
ArrayIndexOutOfBoundsException  版本 2.9.28

### ISSUE THREAD

**Issue by cai784921129** [CymChad/BaseRecyclerViewAdapterHelper#1883]
java.lang.ArrayIndexOutOfBoundsException: length=24; index=-1
        at java.util.ArrayList.get(ArrayList.java:310)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItem(BaseQuickAdapter.java:611)
        at com.chad.library.adapter.base.BaseQuickAdapter.getExpandableItem(BaseQuickAdapter.java:1816)
        at com.chad.library.adapter.base.BaseQuickAdapter.collapse(BaseQuickAdapter.java:1761)
        at com.chad.library.adapter.base.BaseQuickAdapter.collapse(BaseQuickAdapter.java:1796)
        at mst.com.baserecyclerviewadapterhelper.adapter.ExpandableAdapter$2.onClick(ExpandableAdapter.java:82)
        at android.view.View.performClick(View.java:5264)
        at android.view.View$PerformClick.run(View.java:21297)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)

**Comment by cai784921129** [comment]
点击一级带单与二级菜单过快的话 holder.getAdapterPosition() == -1

**Comment by CymChad** [comment]
收到
