### ISSUE TITLE
ArrayIndexOutOfBoundsException setOnItemClickListener()中onItemClick

### ISSUE THREAD

**Issue by MAIMIHO** [CymChad/BaseRecyclerViewAdapterHelper#1933]
你好!: 

版本:  'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.34'
setOnItemClickListener()中onItemClick(BaseQuickAdapter adapter, View view, int position);
出现参数 position 是-1

```java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
	at java.util.ArrayList.get(ArrayList.java:413)
	at .lambda$setListener$3$BaseOtaFragment()
	at $$Lambda$2.onItemClick()
	at com.chad.library.adapter.base.BaseQuickAdapter.setOnItemClick(BaseQuickAdapter.java:976)
	at com.chad.library.adapter.base.BaseQuickAdapter$5.onClick(BaseQuickAdapter.java:956)
	at android.view.View.performClick(View.java:5647)
	at android.view.View$PerformClick.run(View.java:22462)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
```

**Comment by AllenCoder** [comment]
是否是必现？复现机型 和Demo ？
Demo在你那里能否正常工作？

**Comment by AllenCoder** [comment]
无反馈，关闭问题
