### ISSUE TITLE
获取itemView NullPointerException

### ISSUE THREAD

**Issue by lxww14** [CymChad/BaseRecyclerViewAdapterHelper#1990]
//动态显示和隐藏某些符合条件的item- 

View itemView = adapter.getViewByPosition(i, R.id.parentLayout);
                    RecyclerView.LayoutParams param = (RecyclerView.LayoutParams) itemView.getLayoutParams();
                    if (isExpand) {
                        param.height = ConstraintLayout.LayoutParams.WRAP_CONTENT;
                        param.width = ConstraintLayout.LayoutParams.MATCH_PARENT;
                        itemView.setVisibility(View.VISIBLE);
                    } else {
                        itemView.setVisibility(View.GONE);
                        param.height = 0;
                        param.width = 0;
                    }
                    itemView.setLayoutParams(param);

//error stack

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                           at com.vphoto.photographer.biz.order.details.details_new.OrderDetailsActivity.setItemViewIsExpand(OrderDetailsActivity.java:1102)
                                                                           at com.vphoto.photographer.biz.order.details.details_new.OrderDetailsActivity.lambda$initView$1$OrderDetailsActivity(OrderDetailsActivity.java:1036)
                                                                           at com.vphoto.photographer.biz.order.details.details_new.OrderDetailsActivity$$Lambda$1.onItemClick(Unknown Source)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter$5.onClick(BaseQuickAdapter.java:998)
                                                                           at android.view.View.performClick(View.java:5646)
                                                                           at android.view.View$PerformClick.run(View.java:22459)
                                                                           at android.os.Handler.handleCallback(Handler.java:761)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lxww14** [comment]
当获取不可见的item的 itemView时候就会报这个错

**Comment by CymChad** [comment]
建议你用属性来控制隐藏和显示，而不是拿到当前控件来控制。
