### ISSUE TITLE
多条目布局中，条目的种类最大限制只能为7个吗？当使用第8个时，就会报错

### ISSUE THREAD

**Issue by FunnyLee** [CymChad/BaseRecyclerViewAdapterHelper#2056]
03-14 14:51:50.121 10749-10749/com.nvc.smart E/CrashReport: sys default last handle start!
03-14 14:51:50.123 10749-10749/com.nvc.smart E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.nvc.smart, PID: 10749
                                                               android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
                                                                   at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:193)
                                                                   at android.content.res.Resources.loadXmlResourceParser(Resources.java:2175)
                                                                   at android.content.res.Resources.getLayout(Resources.java:1134)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1478)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:989)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:985)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:762)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                   at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                   at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                   at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at cn.bingoogolapple.swipebacklayout.BGASwipeBackLayout.onMeasure(BGASwipeBackLayout.java:704)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6088)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                   at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                   at android.view.View.measure(View.java:20000)
                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2328)
                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1417)
03-14 14:51:50.123 10749-10749/com.nvc.smart E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1670)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1305)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6478)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6259)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)

**Comment by EmMper** [comment]
https://stackoverflow.com/questions/45788814/android-content-res-resourcesnotfoundexception-resource-id-0xfffffe6c

getItemType中返回的值，未通过addItemType添加进去。
