### ISSUE TITLE
使用BaseMultiItemQuickAdapter加载布局时NotFoundException: Resource ID #0xfffffe6c

### ISSUE THREAD

**Issue by adminLiu-s** [CymChad/BaseRecyclerViewAdapterHelper#2082]
android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
                                                                   at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:202)
                                                                   at android.content.res.Resources.loadXmlResourceParser(Resources.java:2968)
                                                                   at android.content.res.Resources.getLayout(Resources.java:1984)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1478)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:989)
                                                                   at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:50)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:762)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
                                                                   at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                   at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                   at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                   at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                   at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by EmMper** [comment]
https://stackoverflow.com/questions/45788814/android-content-res-resourcesnotfoundexception-resource-id-0xfffffe6c

getItemType中返回的值，未通过addItemType添加进去。

**Comment by adminLiu-s** [comment]
![image](https://user-images.githubusercontent.com/11938143/37815573-58799580-2eaa-11e8-9dba-79eef7345e8b.png)
我是按照demo来xie'de写的，第一条数据也能出来，可是一滑动就报错了，也就是加载第二种类型布局时

**Comment by lpc904586134** [comment]
getItemType没有找到对应的类型，返回了这个TYPE_NOT_FOUND = -404;，-404就是0xfffffe6c
