### ISSUE TITLE
Crash on layout null

### ISSUE THREAD

**Issue by amjadislam1** [CymChad/BaseRecyclerViewAdapterHelper#2099]
Please solve this issue.

Class: BaseMultiItemQuickAdapter
Method: 

private int getLayoutId(int viewType) {
        return layouts.get(viewType, TYPE_NOT_FOUND);
    }

Exception:
serv.provider E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: qa.qserv.provider, PID: 5471
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.SparseIntArray.get(int, int)' on a null object reference
                                                                     at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:56)
                                                                     at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:52)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:769)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3109)

**Comment by AllenCoder** [comment]
Looks like you have multiple layouts, the viewId and the corresponding layout are not found, it should be set incorrectly

**Comment by qasimalbaqali** [comment]
I'm getting the same problem. @AllenCoder what do you mean by having multiple layouts.  This is how my code looks like. Is this the correct way of setting the layout?

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view =  inflater.inflate(R.layout.fragment_accepted_declarations, container, false);

        RecyclerView declarationsRecyclerView = (RecyclerView) view.findViewById(R.id.recyclerViewAcceptedDeclarationsList);
        LinearLayoutManager llm = new LinearLayoutManager(getContext());
        llm.setOrientation(LinearLayoutManager.VERTICAL);
        declarationsRecyclerView.setLayoutManager(llm);

        List<Declaration> declarationsList = new ArrayList<>();
        declarationsList.add(new Declaration("Ov vergoeding jan", new Date(), 60.45));

        mDeclarationsAdapter = new AcceptedDeclarationsPagerAdapter(declarationsList);
        mDeclarationsAdapter.setDefaultViewTypeLayout(R.layout.list_item_accepted_declaration);
        declarationsRecyclerView.setAdapter(mDeclarationsAdapter);

        return view;
    }
```
