### ISSUE TITLE
和TwinklingRefreshLayout一起使用时会报错

### ISSUE THREAD

**Issue by YueSeSuiFeng** [CymChad/BaseRecyclerViewAdapterHelper#2110]
` java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1158360 position=11 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                     at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                     at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                     at android.os.Handler.handleCallback(Handler.java:742)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:157)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5686)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

`1. `

        <com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/refresh"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:tr_enable_overscroll="false">

            
            
            
            
            
            

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/background"
                android:overScrollMode="never"/>

        </com.lcodecore.tkrefreshlayout.TwinklingRefreshLayout>

`

**Comment by AllenCoder** [comment]
根据错误日志暂时猜测不是框架问题，请尝试以下方案
[https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in](https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in)

[https://www.jianshu.com/p/2eca433869e9](https://www.jianshu.com/p/2eca433869e9)

**Comment by YueSeSuiFeng** [comment]
已经重写过LayoutManager，和TwinklingRefreshLayout这个一起用上啦加载时就会报错（https://github.com/lcodecorex/TwinklingRefreshLayout）；但是改用SwipeRefreshLayout暂时没遇到这个错误，但是会加载更多时刷新页面是数据会显示不全，错乱。item的布局最外层的Layout是layout_height设置了match_parent.不知道哪里出问题了？

/**
 * 官方的BUG
 * 解决 IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter
 */

public class CustomLinearLayoutManager extends LinearLayoutManager {

    public CustomLinearLayoutManager(Context context) {
        super(context);
    }

    public CustomLinearLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public CustomLinearLayoutManager(Context context, int orientation, boolean reverseLayout) {
        super(context, orientation, reverseLayout);
    }

    /**
     * 重写该方法，返回false
     */
    @Override
    public boolean supportsPredictiveItemAnimations() {
        return false;
    }

    /**
     * 重写该方法，去捕捉该异常
     *
     * @param recycler
     * @param state
     */
    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        //override this method and implement code as below
        try {
            super.onLayoutChildren(recycler, state);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}


------------------ 原始邮件 ------------------
发件人: "Allen"<notifications@github.com>;
发送时间: 2018年4月3日(星期二) 晚上9:15
收件人: "CymChad/BaseRecyclerViewAdapterHelper"<BaseRecyclerViewAdapterHelper@noreply.github.com>;
抄送: "只若初见"<963304310@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CymChad/BaseRecyclerViewAdapterHelper] 和TwinklingRefreshLayout一起使用时会报错 (#2110)




根据错误日志暂时猜测不是框架问题，请尝试以下方案
 https://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in
 
https://www.jianshu.com/p/2eca433869e9
