### ISSUE TITLE
和XRecyclerView使用出现ClassCastException异常

### ISSUE THREAD

**Issue by SSSSunrise** [CymChad/BaseRecyclerViewAdapterHelper#2113]
`FATAL EXCEPTION: main
                                                                         Process: com.dongxiaogroup.mbpay, PID: 24770
                                                                         java.lang.ClassCastException: com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter$SimpleViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolder
                                                                             at com.chad.library.adapter.base.BaseQuickAdapter.onViewAttachedToWindow(BaseQuickAdapter.java:68)
                                                                             at com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onViewAttachedToWindow(XRecyclerView.java:655)
                                                                             at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6987)
                                                                             at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:758)
                                                                             at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8029)
                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7987)
                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7975)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1572)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
                                                                             at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1449)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                                             at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:515)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
                                                                             at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                                                                             at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
                                                                             at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
                                                                             at android.view.View.measure(View.java:19388)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
                                                                         	at android.v`

**Comment by AllenCoder** [comment]
```
com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter$SimpleViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolde
```
第三方，自定义一个viewholder 需要继承BaseViewHolder

**Comment by SSSSunrise** [comment]
有demo吗，我试着按照文档上说的继承了BaseViewHolder 但是并没有效果

**Comment by AllenCoder** [comment]
```
public static class ViewHolder extends BaseViewHolder {

    TextView tv;

    public ViewHolder(View view) {
        super(view);
        tv = (TextView) view.findViewById(R.id.item_gr_myskills_tv);
    }
}
```
另外需要加入混淆配置，混淆规则参考README文档

**Comment by SSSSunrise** [comment]
好的 谢谢

**Comment by SSSSunrise** [comment]
我试了试，依然会包类型转换异常，好像这个XRecyclerView的Viewholder 仅支持RecyclerView.ViewHolder

**Comment by SSSSunrise** [comment]
![6 iksn9qmtx fnq jxan2c](https://user-images.githubusercontent.com/31717774/38285923-3564f4d2-37f5-11e8-9159-de2f7d2c2d89.png)

**Comment by dendrocyte** [comment]
你好～我在debug mode 並不會出現這問題
但一旦上架後就出現同樣的問題

```
class MenuAdapter(layoutResId: Int, data: List<MenuData>?)
    : BaseQuickAdapter<MenuData, MenuHolder>(layoutResId, data) {
    override fun convert(helper: MenuHolder, item: MenuData) {
}
```

`class MenuHolder(view: View) : BaseViewHolder(view)`


 java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to org.videolan.vlc.noovo.adapter.MenuHolder
        at org.videolan.vlc.noovo.adapter.MenuAdapter.convert(MenuAdapter.kt:22)
