### ISSUE TITLE
删除第一个item报错，删除其他item没问题

### ISSUE THREAD

**Issue by doubleZuo** [CymChad/BaseRecyclerViewAdapterHelper#214]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{43142ad8 position=0 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)}
                                                                    at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:681)
                                                                    at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
                                                                    at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1134)
                                                                    at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3485)
                                                                    at android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:151)
                                                                    at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:445)
                                                                    at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:246)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3330)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(R
...
...

**Comment by CymChad** [comment]
你的版本是？

**Comment by doubleZuo** [comment]
@CymChad 版本是v1.9.8。是版本问题吗，我换成v1.9.7再试试

**Comment by CymChad** [comment]
版本是新的，没问题，具体看下你的代码，你有没有添加头部？

**Comment by doubleZuo** [comment]
添加头部headview，也添加emptyview @CymChad 
`  adpter = new QuickAdapter(R.layout.item_comment, mPresenter.getConmentList());
        adpter.setEmptyView(true, true, emptyView);
        adpter.addHeaderView(header);
        adpter.openLoadMore(true);
        adpter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mPresenter.loadCommentsTask(false);
            }
        });`

**Comment by CymChad** [comment]
我测试了一下，并没有问题，我添加了头部，空布局，和上拉刷新更多。
![1](https://cloud.githubusercontent.com/assets/7698209/17427892/c32b1d68-5b16-11e6-83af-5b670330bded.gif)

**Comment by doubleZuo** [comment]
@CymChad 我的问题仍然没有解决。
头布局或空布局，占layoutpostition吗
  final int pos = (vh.getAdapterPosition()-1);
list.remove(pos)

**Comment by CymChad** [comment]
你不用-1，头部我帮你做过处理了

**Comment by CymChad** [comment]
你直接用adapter.remove(i);

**Comment by CymChad** [comment]
你可以查看源码。数据我都帮你管理了，你要删除后的数据，可以adapter.getData();

**Comment by CymChad** [comment]
源码
```java
 public void remove(int position) {
        this.mData.remove(position);
        this.notifyItemRemoved(position + this.getHeaderLayoutCount());
    }
```

**Comment by doubleZuo** [comment]
打印了，第一项显示的position是1（应该是0吧）。我要取出这个position的data，发给服务器，服务器返回后才可以删除。怎么获取当前position的数据

**Comment by doubleZuo** [comment]
打印了，第一项显示的position是1（应该是0吧）。我要取出这个position的data，发给服务器，服务器返回后才可以删除。怎么获取当前position的数据 @CymChad

**Comment by CymChad** [comment]
你应该是点击删除吧，那个postion有给你吧。

**Comment by CymChad** [comment]
在点击事件的回调里面有，position这个参数
