### ISSUE TITLE
itemView may not be null

### ISSUE THREAD

**Issue by zcychinese** [CymChad/BaseRecyclerViewAdapterHelper#2168]

**Comment by HeMing123** [comment]
+1

**Comment by eren000** [comment]
java.lang.IllegalArgumentException: itemView may not be null
        at androidx.recyclerview.widget.RecyclerView$ViewHolder.<init>(RecyclerView.java:10833)
        at com.chad.library.adapter.base.BaseViewHolder.<init>(BaseViewHolder.java:79)
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1045)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:763)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:66)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)


![image](https://user-images.githubusercontent.com/5646528/59553098-8f2c8e00-8fc2-11e9-8a9d-bc6274b5c9cb.png)



重写getItemViewType return position
加载了大量图片,显示了300张左右,再往下滑动崩溃
