### ISSUE TITLE
为什么我复写onViewAttachedToWindow和onViewDetachedFromWindow方法,就会报类型转换异常.

### ISSUE THREAD

**Issue by Vander-liu** [CymChad/BaseRecyclerViewAdapterHelper#2188]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.microger.mxx.ui.adapter.MarkAppAdapter$MarkViewHolder
                                                                            at com.microger.mxx.ui.adapter.MarkAppAdapter.onViewAttachedToWindow(MarkAppAdapter.java:31)
                                                                            at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6961)
                                                                            at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:750)
                                                                            at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                            at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8003)
                                                                            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7961)
                                                                            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7949)
                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1570)
                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                            at android.view.View.layout(View.java:16653)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by Vander-liu** [comment]
我查了相关的问题,但是没找到合理的答案,不知道我是不是使用不当.

**Comment by Vander-liu** [comment]
public static class MarkViewHolder extends BaseViewHolder {
      xxxx
}

我的内部Holder 是静态的 public权限.但是不知道为什么会引起这个错误.

**Comment by Vander-liu** [comment]
public class MarkAppAdapter extends BaseQuickAdapter<AppMarkBean, MarkAppAdapter.MarkViewHolder> {

    public MarkAppAdapter() {
        super(R.layout.holder_mark_app);
    }

    @Override
    protected void convert(MarkViewHolder helper, AppMarkBean item) {
        //绑定数据
        helper.bindData(item);
    }

    @Override
    public void onViewAttachedToWindow(MarkViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        holder.onAttach();
    }

    @Override
    public void onViewDetachedFromWindow(MarkViewHolder holder) {
        super.onViewDetachedFromWindow(holder);
        holder.onDetach();
    }

    /**
     * 每个Item对应的ViewHolder
     */
    public static class MarkViewHolder extends BaseViewHolder {

   
        public MarkViewHolder(View view) {
            super(view);

        }

       public void  onAttach(){}
     
      public void onDetach(){}

}

**Comment by Vander-liu** [comment]
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err: java.lang.reflect.InvocationTargetException
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1062)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1038)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:779)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:757)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
04-28 17:06:31.181 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:742)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5524)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTag(java.lang.Object)' on a null object reference
04-28 17:06:31.182 12066-12066/com.microger.mxx.debug W/System.err:     at com.microger.mxx.ui.adapter.MarkViewHolder.<init>(MarkViewHolder.java:46)
04-28 17:06:31.183 12066-12066/com.microger.mxx.debug W/System.err: 	... 20 more

**Comment by Vander-liu** [comment]
找到原因了,原来源码里面创建自定义是通过反射创建的,但是我在构造方法里面有其他操作,就会出现这个问题.

但是这个异常被try catch了.我直接看后面那段Error ,一直找不到原因.

我感觉这个 应该是组件相关的问题.这边我想ViewHolder初始化就做一些操作.如果是反射的话,那么就会出现问题.

**Comment by getglory** [comment]
> public class MarkAppAdapter extends BaseQuickAdapter<AppMarkBean, MarkAppAdapter.MarkViewHolder> {
> 
> ```
> public MarkAppAdapter() {
>     super(R.layout.holder_mark_app);
> }
> 
> @Override
> protected void convert(MarkViewHolder helper, AppMarkBean item) {
>     //绑定数据
>     helper.bindData(item);
> }
> 
> @Override
> public void onViewAttachedToWindow(MarkViewHolder holder) {
>     super.onViewAttachedToWindow(holder);
>     holder.onAttach();
> }
> 
> @Override
> public void onViewDetachedFromWindow(MarkViewHolder holder) {
>     super.onViewDetachedFromWindow(holder);
>     holder.onDetach();
> }
> 
> /**
>  * 每个Item对应的ViewHolder
>  */
> public static class MarkViewHolder extends BaseViewHolder {
> 
> 
>     public MarkViewHolder(View view) {
>         super(view);
> 
>     }
> 
>    public void  onAttach(){}
>  
>   public void onDetach(){}
> ```
> 
> }

因为BaseAdapterRecyclerViewHelper重写了这两个方法，它有自己的Header和Footer，还有EmptyView，这几个item的ViewHolder时BaseViewHolder，而不是你定义的ViewHolder，所以会出错。你可以用BaseViewHolder：
public class MarkAppAdapter extends BaseQuickAdapter<AppMarkBean, BaseViewHolder> 
然后判断是否是你自己的item，再做操作：

`@Override
protected void convert(BaseViewHolder helper, AppMarkBean item) {
    //绑定数据
    if (helper instanceof MarkViewHolder ) {
      MarkViewHolder markHolder = (MarkViewHolder)helper;
      markHolder.bindData(item);
     }
   
}

@Override
public void onViewAttachedToWindow(BaseViewHolder holder) {
    super.onViewAttachedToWindow(holder);
   if (helper instanceof MarkViewHolder ) {
      MarkViewHolder markHolder = (MarkViewHolder)helper;
      markHolder .onAttach();
     }
    
}

@Override
public void onViewDetachedFromWindow(BaseViewHolder holder) {
    super.onViewDetachedFromWindow(holder);
 if (helper instanceof MarkViewHolder ) {
      MarkViewHolder markHolder = (MarkViewHolder)helper;
      markHolder .onDetach();
     }
    
}
`

**Comment by getglory** [comment]
> 找到原因了,原来源码里面创建自定义是通过反射创建的,但是我在构造方法里面有其他操作,就会出现这个问题.
> 
> 但是这个异常被try catch了.我直接看后面那段Error ,一直找不到原因.
> 
> 我感觉这个 应该是组件相关的问题.这边我想ViewHolder初始化就做一些操作.如果是反射的话,那么就会出现问题.

因为Adapter重写了很多RecyclerView.Adapter的方法，所以很多方法不要去使用或者重写，比如notifyItemChanged相关的方法不要使用，应该使用refreshNotifyItemChanged等BRAH提供的方法，不然会造成item刷新错误。

**Comment by liuqingdada** [comment]
重写 createBaseViewHolder方法即可
    @SuppressWarnings({"unchecked", "rawtypes"})
    protected K createBaseViewHolder(View view) {
        Class temp = getClass();
        Class z = null;
        while (z == null && null != temp) {
            z = getInstancedGenericKClass(temp);
            temp = temp.getSuperclass();
        }
        K k;
        // 泛型擦除会导致z为null
        if (z == null) {
            k = (K) new BindDataViewHolder(view);
        } else {
            k = createGenericKInstance(z, view);
        }
        return k != null ? k : (K) new BindDataViewHolder(view);
    }

比如我这里是 BindDataViewHolder
