### ISSUE TITLE
设置空布局后崩溃

### ISSUE THREAD

**Issue by zhangshuliang** [CymChad/BaseRecyclerViewAdapterHelper#2209]
我在recyclerview.setAdapter()方法后，adapter.setEmptyView(R.layout.layout_observe_empty);崩溃

错误日志：
java.lang.RuntimeException: please bind recyclerView first!
        at com.chad.library.adapter.base.BaseQuickAdapter.checkNotNull(BaseQuickAdapter.java:148)
        at com.chad.library.adapter.base.BaseQuickAdapter.setEmptyView(BaseQuickAdapter.java:1325)
        at com.jingdata.blockchain.model.mainmodel.observehouse.ObserveHouseFragment$3.onResponse(ObserveHouseFragment.java:96)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6337)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by zzjian** [comment]
报错很明显了，先调用`bindToRecyclerView` 方法

**Comment by zhangshuliang** [comment]
@zzjian 谢谢你，原来不知道这个方法，学习了
