### ISSUE TITLE
BaseQuickAdapter 设置setEmptyView 奔溃BUG

### ISSUE THREAD

**Issue by itcheng** [CymChad/BaseRecyclerViewAdapterHelper#2225]
在TabLayout +ViewPager+Fragment+BaseQuickAdapter  组合使用的时候，用BaseQuickAdapter 设置setEmptyView，如果有4个tab，那么来回切换一次的话，就会报removeView错误奔溃！应该是Fragement 销毁了，BaseQuickAdapter  还没销毁，所以还持有EmptyView，导致奔溃，希望解决这个bug吧！

The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
                                                                at android.view.ViewGroup.addView(ViewGroup.java:3415)
                                                                at android.view.ViewGroup.addView(ViewGroup.java:3360)
                                                                at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:746)
                                                                at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)

**Comment by AllenCoder** [comment]
```
The specified child already has a parent. You must call removeView() on the child's parent first.
```
不应该频繁设置emptyView
