### ISSUE TITLE
收起 展开功能 抛错 UnsupportedOperationException

### ISSUE THREAD

**Issue by MissRight** [CymChad/BaseRecyclerViewAdapterHelper#2226]
at java.util.AbstractList.add(AbstractList.java:148)
                      at java.util.AbstractList.addAll(AbstractList.java:260)
                      at com.chad.library.adapter.base.BaseQuickAdapter.expand(BaseQuickAdapter.java:1679)
                      at com.chad.library.adapter.base.BaseQuickAdapter.expand(BaseQuickAdapter.java:1715)

**Comment by AllenCoder** [comment]
使用 Arrays.asList(arr) 转换的 List 并不能进行 add 和 remove 操作。
Arrays.asList(arr) 返回的类型是 Aarrays$ArrayList 并不是 ArrayList，
Aarrays$ArrayList 和 ArrayList 都继承 AbstractList，但是 AbstractList 中的 add 方法和 remove 方法都是直接抛出 UnsupportedOperationException，并没有直接实现。
ArrayList 重写了 add 方法和 remove 方法,能够进行对应的添加和删除操作，Aarrays$ArrayList 却没有去重写，所以此时调用 add 方法和 remove 方法会抛出 UnsupportedOperationException。

作者：寻梦的尕柳
链接：https://www.jianshu.com/p/7f718d900111
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
