### ISSUE TITLE
ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

### ISSUE THREAD

**Issue by fandeus** [CymChad/BaseRecyclerViewAdapterHelper#2269]
场景：使用fragment + viewpage， 我添加了头布局和脚布局，创建的时候没有问题，但是滑动话会来的时候就报错了，如下。

`
View header = getWeatherHeaderView(weatherBean);
        View footView = getWeatherFootView();
        if (mAdapter == null && future.size() > 0) {
            mAdapter = new FutureAdapter(R.layout.item_future_weather, future);
            mAdapter.addHeaderView(header);
            mAdapter.addFooterView(footView);
        }
        mRecyclerView.setAdapter(mAdapter);
`

添加头部布局
`
/**
     * 添加头布局
     * @param weatherBean
     */
    public View getWeatherHeaderView(WeatherEntity.WeatherBean weatherBean) {
        String city = weatherBean.getCity_name() + "\n" + weatherBean.getNow().getText();
        final View view = getLayoutInflater().inflate(R.layout.item_weather_header, (ViewGroup) mRecyclerView.getParent(), false);
        ImageView headerBg = view.findViewById(R.id.weather_header_bg);
        TextView headerTemp = view.findViewById(R.id.weather_header_temp);
        TextView headerLocation = view.findViewById(R.id.weather_header_location);
        TextView headerAdvice = view.findViewById(R.id.weather_header_advice);
        TextView headerTips = view.findViewById(R.id.weather_header_tips);

        if (TimeUtil.isNight()) {
            headerBg.setImageDrawable(getResources().getDrawable(R.drawable.weather_bg_night));
        } else {
            headerBg.setImageDrawable(getResources().getDrawable(R.drawable.weather_bg_day));
        }
        headerTips.setVisibility(isShow ? View.VISIBLE : View.GONE);
        headerAdvice.setText(weatherBean.getToday().getSuggestion().getDressing().getDetails());
        headerTemp.setText(weatherBean.getNow().getTemperature());
        headerLocation.setText(city);
        return view;
    }
`

添加脚布局
`/**
     * 添加叫布局
     */
    private View getWeatherFootView() {
        final View foot = getLayoutInflater().inflate(R.layout.item_weather_foot, (ViewGroup) mRecyclerView.getParent(), false);
        return foot;
    }`

错误日志：
06-03 15:54:22.592 14636-14641/mypackage I/art: Do full code cache collection, code=109KB, data=124KB
06-03 15:54:22.593 14636-14641/mypackage I/art: After code cache collection, code=96KB, data=91KB
06-03 15:54:23.239 14636-14698/mypackage D/libc-netbsd: getaddrinfo: tj.nineton.cn get result from proxy gai_error = 0
06-03 15:54:23.240 14636-14698/mypackage I/System.out: [socket][2] connection tj.nineton.cn/47.98.18.144:80;LocalPort=-1(10000)
06-03 15:54:23.240 14636-14636/mypackage E/RecyclerView: No adapter attached; skipping layout
06-03 15:54:23.615 14636-14698/mypackage.baobo I/System.out: [socket][/192.168.1.13:34796] connected
06-03 15:54:23.983 14636-14636/mypackage E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mypackage, PID: 14636
    java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:750)
        at android.view.View.layout(View.java:17942)
        at android.view.ViewGroup.layout(ViewGroup.java:5754)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2744)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2414)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1488)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7095)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:921)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:907)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by AllenCoder** [comment]
fragment在viewpager容器里来回切换，如果没有设置，会导致重复实例化，重复加载数据，
建议在设置一个缓存，
解决方式：给page
```


mViewPager.setOffscreenPageLimit(3);
```

**Comment by fandeus** [comment]
嗯，好的，学到了一新的技术点。谢谢大神。这个问题就这么被你轻松的解决了。

**Comment by ddyos** [comment]
> fragment在viewpager容器里来回切换，如果没有设置，会导致重复实例化，重复加载数据，
> 建议在设置一个缓存，
> 解决方式：给page
> 
> ```
> 
> 
> mViewPager.setOffscreenPageLimit(3);
> ```

Tabhost里面的两个Fragement都用到了同一个adapter，然后设置了emptyView。来回切换也有同样的错误，有解决方案吗？

**Comment by TpOut** [comment]
你好，想问下你们是必现的吗？或者复现条件是什么
因为我只是在统计的崩溃日志里有看到，但是自己复现不了

**Comment by fandeus** [comment]
> 你好，想问下你们是必现的吗？或者复现条件是什么
> 因为我只是在统计的崩溃日志里有看到，但是自己复现不了

我这边是必现的。出现的场景就是，没有设置ViewPage的加载数，导致每次都会重现创建Fragment。然后导致了这个问题。

**Comment by xilost** [comment]
> fragment在viewpager容器里来回切换，如果没有设置，会导致重复实例化，重复加载数据，
> 建议在设置一个缓存，
> 解决方式：给page
> 
> ```
> 
> 
> mViewPager.setOffscreenPageLimit(3);
> ```

为什么重复实例化会出现这个问题，现在我的需求就是需要重新刷新这个fragment，怎么处理？
