### ISSUE TITLE
多点击事件 刷新适配器时数据错误

### ISSUE THREAD

**Issue by xtxiaolu** [CymChad/BaseRecyclerViewAdapterHelper#2276]
adapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
            @Override
            public void onItemChildClick(BaseQuickAdapter adapter, View view, int position) {
             
                switch (view.getId()) {
                    case R.id.simpleDraweeView:
                        DataCenter.getInstance().setImageList(imageList.get(position));
                        Intent intent = new Intent(getActivity(), PreviewImageActivity.class);
                        startActivity(intent);
                        break;
                    case R.id.photo_check:
                        if (imageList.get(position).getClick()) {
                            imageList.get(position).setClick(false);
                        } else {
                            imageList.get(position).setClick(true);
                        }
                        break;
                    default:
                }
                adapter.addData(imageList);
            }
        });

**Comment by xtxiaolu** [comment]
放里面和外面都不行

**Comment by xtxiaolu** [comment]
06-06 10:31:31.878 10636-10636/com.example.kongsou_android.erxiang E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kongsou_android.erxiang, PID: 10636
    java.lang.OutOfMemoryError: Failed to allocate a 206438412 byte allocation with 16777216 free bytes and 140MB until OOM
        at java.util.Arrays.copyOf(Arrays.java:3231)
        at java.util.Arrays.copyOf(Arrays.java:3204)
        at java.util.ArrayList.grow(ArrayList.java:249)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:223)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:215)
        at java.util.ArrayList.addAll(ArrayList.java:564)
        at com.chad.library.adapter.base.BaseQuickAdapter.addData(BaseQuickAdapter.java:559)
        at com.example.kongsou_android.erxiang.mvp.upload.ui.fragment.SelectImageFragment$1.onItemChildClick(SelectImageFragment.java:81)
        at com.chad.library.adapter.base.BaseViewHolder$1.onClick(BaseViewHolder.java:390)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6577)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by AllenCoder** [comment]
你的用法肯定不对，你在点击事件里面  
```
adapter.addData(imageList);
```
报错信息也很明显 oom 
```
java.lang.OutOfMemoryError: Failed to allocate a 206438412 byte allocation with 16777216 free bytes and 140MB until OOM
```

具体写法可以参考demo的嵌套点击事件的写法
