### ISSUE TITLE
BaseMultiItemQuickAdapter共享RecycledViewPool会几率性报错。

### ISSUE THREAD

**Issue by parcool** [CymChad/BaseRecyclerViewAdapterHelper#2277]
报错信息：
```
06-06 16:13:55.984 24581-24581/com.test W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.chad.library.adapter.base.BaseViewHolder.setText(BaseViewHolder.java:124)
        at com.test.ui.adapter.RecommendHotAdapter.convert(RecommendHotAdapter.java:30)
```
定位到的代码：
```
 viewHolder.setText(R.id.tv_title123, item.getProductName())
```

结构：
外层RecyclerView内嵌2个RecyclerView(不同2个itemType)

OutAdapter代码：
```Java
public class OutAdapter extends BaseMultiItemQuickAdapter<RecommendModel<?>, BaseViewHolder> {

    RecyclerView.RecycledViewPool recycledViewPool = new RecyclerView.RecycledViewPool();
    public OutAdapter(List<RecommendModel<?>> data) {
        super(data);
//        recycledViewPool = new RecyclerView.RecycledViewPool();
        addItemType(RecommendModel.ITEM_TYPE_BANNER, R.layout.layout_convenient_banner);
        addItemType(RecommendModel.ITEM_TYPE_CATEGORIES, R.layout.layout_categories);
    }

    @Override
    protected void convert(BaseViewHolder helper, RecommendModel item) {
       switch (helper.getItemViewType()) {
            case RecommendModel.ITEM_TYPE_BANNER:
                     recyclerView1.setRecycledViewPool(recycledViewPool);
                     //...正常普通BaseQuickAdapter流程
                     break;
            case RecommendModel.ITEM_TYPE_CATEGORIES:
                     recyclerView2.setRecycledViewPool(recycledViewPool);
                     //...正常普通BaseQuickAdapter流程
                     break;
          }
     }

}
```

以上代码是简化版，如果不设置```setRecycledViewPool(recycledViewPool);```就不会报错。复现步骤就是多次上下滑动。

**Comment by parcool** [comment]
对了，外层RecyclerView的LayoutManager也设置了layoutManager.setRecycleChildrenOnDetach(true);

**Comment by AllenCoder** [comment]
这个大概率是由于多布局情况下，viewholder默认会缓存了view的索引，在复用recycledViewPool之后，会导致偶发性的view为空，没有做判空处理，直接抛出空指针异常了

**Comment by parcool** [comment]
如何解决呢？

**Comment by RDSunhy** [comment]
@AllenCoder 能分享下解决方案吗？？？？
