### ISSUE TITLE
我采用BaseQuickAdapter实现多布局，实现上拉刷新后，出现 java.lang.NullPointerException

### ISSUE THREAD

**Issue by jisuz** [CymChad/BaseRecyclerViewAdapterHelper#2355]
java.lang.NullPointerException
                                                                               at com.chad.library.adapter.base.BaseViewHolder.setVisible(BaseViewHolder.java:248)
                                                                               at com.chad.library.adapter.base.loadmore.LoadMoreView.visibleLoading(LoadMoreView.java:57)
                                                                               at com.chad.library.adapter.base.loadmore.LoadMoreView.convert(LoadMoreView.java:34)
                                                                               at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:930)
                                                                               at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                               at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1330)
                                                                               at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1074)
                                                                               at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4838)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:593)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:561)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                               at dalvik.system.NativeStart.main(Native Method)

我采用了BaseQuickAdapter，实现多种布局，在上拉刷新的时候，出现了NullPointerException，想请教一下是什么问题？

**Comment by jisuz** [comment]
部分核心代码：
  private void initRvNearbyList() {
        mRvNearbyList.setLayoutManager(new LinearLayoutManager(getActivity()));
        // 需加，不然滑动不流畅
        mRvNearbyList.setNestedScrollingEnabled(false);
        mRvNearbyList.setHasFixedSize(false);
        mRvNearbyList.setItemAnimator(new DefaultItemAnimator());
    }

 private void initAdapter() {
        homeAdapter = new MiNearbyListAdapter(getActivity());
        homeAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                if (mRecyclerViewItems.get(position) instanceof CouponBean) {
                    CouponBean couponBean = (CouponBean) mRecyclerViewItems.get(position);
                    EventBus.getDefault().post(new StartBrotherEvent(CouponDetailFragment.newInstance(couponBean.getUuid())));
                } else if (mRecyclerViewItems.get(position) instanceof MiAdsBean) {

                }
            }
        });
        homeAdapter.setEnableLoadMore(true);
        homeAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                mRvNearbyList.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        loadMore();
                    }
                },500);
            }
        },mRvNearbyList);
        homeAdapter.openLoadAnimation();
        mRvNearbyList.setAdapter(homeAdapter);
    }

  private void refresh() {
        isRefresh = true;
        mNextRequestPage = 1;
        homeAdapter.setEnableLoadMore(false);//这里的作用是防止下拉刷新的时候还可以上拉加载
        loadListData();
    }

private void setData(boolean isRefresh, List data) {
        final int size = data == null ? 0 : data.size();
        if (isRefresh) {
            homeAdapter.setNewData(data);
        } else {
            if (size > 0) {
                homeAdapter.addData(data);
            }
        }
        homeAdapter.notifyDataSetChanged();
        if (mNextRequestPage >= TOTAL_PAGE) {
            //数据全部加载完毕
            homeAdapter.loadMoreEnd();
            Toast.makeText(getActivity(), "没有更多数据了", Toast.LENGTH_SHORT).show();
        } else {
            homeAdapter.loadMoreComplete();
        }
    }

**Comment by 09ae9c** [comment]
+1
![image](https://user-images.githubusercontent.com/11228492/43988784-7227d03a-9d6f-11e8-8be1-27140a84928c.png)

**Comment by lqplqp** [comment]
一样

**Comment by CymChad** [comment]
收到

**Comment by AllenCoder** [comment]
1 报错原因是多布局的 setVisibility根据设置的控件id 没有在对于的布局view里面找到，请检查 view的绑定 是否正确？
2. 检查多布局 view的type和 数据绑定是否一致

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/63221986-ed990700-c1d3-11e9-94c5-026c0ece92be.png)
记得判断iitemtype
