### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{43a783c0 position=0 id=-1, oldPos=-1, pLpos:-1}

### ISSUE THREAD

**Issue by hudan2714** [CymChad/BaseRecyclerViewAdapterHelper#2362]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{43a783c0 position=0 id=-1, oldPos=-1, pLpos:-1}
	at android.support.v7.widget.RecyclerView$5.attachViewToParent(TbsSdkJava:763)
	at android.support.v7.widget.ChildHelper.attachViewToParent(TbsSdkJava:239)
	at android.support.v7.widget.RecyclerView.addAnimatingView(TbsSdkJava:1274)
	at android.support.v7.widget.RecyclerView.animateChange(TbsSdkJava:3831)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(TbsSdkJava:3643)
	at android.support.v7.widget.RecyclerView.dispatchLayout(TbsSdkJava:3323)
	at android.support.v7.widget.RecyclerView.onLayout(TbsSdkJava:3844)
	at android.view.View.layout(View.java:14889)
	at android.view.ViewGroup.layout(ViewGroup.java:4651)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14889)
	at android.view.ViewGroup.layout(ViewGroup.java:4651)

**Comment by AllenCoder** [comment]
相同问题参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=java.lang.IllegalArgumentException%3A+Called+attach+on+a+child+which+is+not+detached](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?utf8=%E2%9C%93&q=java.lang.IllegalArgumentException%3A+Called+attach+on+a+child+which+is+not+detached)

**Comment by qq2748** [comment]
解决方法呢
