### ISSUE TITLE
我在一个recycleview的头部嵌套了一个recycleview 然后同时使用你的adapter会报这个错误

### ISSUE THREAD

**Issue by Android-xiaole** [CymChad/BaseRecyclerViewAdapterHelper#2373]
我在一个recycleview的头部嵌套了一个recycleview 然后同时使用你的adapter会报这个错误

java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6750)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5929)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5812)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5808)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3290)
                                                                     at android.view.View.measure(View.java:19886)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at com.zhy.autolayout.AutoLinearLayout.onMeasure(AutoLinearLayout.java:43)
                                                                     at android.view.View.measure(View.java:19886)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                     at android.view.View.measure(View.java:19886)
                                                                     at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9073)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3878)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3595)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4148)
                                                                     at android.view.View.layout(View.java:17666)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5577)
                                                                     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
                                                                     at android.view.View.layout(View.java:17666)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5577)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at com.zhy.autolayout.AutoFrameLayout.onLayout(AutoFrameLayout.java:70)
                                                                     at android.view.View.layout(View.java:17666)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5577)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at com.zhy.autolayout.AutoFrameLayout.onLayout(AutoFrameLayout.java:70)
                                                                     at android.view.View.layout(View.java:17666)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5577)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                     at com.zhy.autolayout.AutoLinearLayout.onLayout(AutoLinearLayout.java:50)
                                                                     at android.view.View.layout(View.java:17666)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5577)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at android.view.View.layout(View.java:17666)
                                                                 	at android.view.ViewGroup.layout(Vie

版本：implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30'
implementation 'com.android.support:recyclerview-v7:28.0.0-alpha3'

gradle配置：
compileSdkVersion 28
    buildToolsVersion '27.0.1'
    defaultConfig {
        applicationId "com.chile.fastloan"

        minSdkVersion 16
        targetSdkVersion 28
        versionCode 8
        versionName "1.2"
        flavorDimensions "versionCode"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
}

**Comment by Android-xiaole** [comment]
补充一下这个两个adapter是同一个对象

**Comment by AllenCoder** [comment]
可以复用adapter，但是两个adapter应该指向不同的对象引用，如果是相同，肯定会有问题
