### ISSUE TITLE
签名打包后报错：E/RecyclerView: No adapter attached; skipping layout + Resources$NotFoundException: Resource ID #0xfffffe6c

### ISSUE THREAD

**Issue by admingalery** [CymChad/BaseRecyclerViewAdapterHelper#2392]
提出这个issue之前，我已经搜索过了其他的issue，并且按照别人的建议都试了一遍，但是没有解决。
我的项目在签名打包前，各个功能都正常的，现在打包后，就报这个错误：
08-09 01:23:41.147 7655-7655/com.xxxxxx.myapp E/RecyclerView: No adapter attached; skipping layout
08-09 01:23:41.246 7655-7655/com.xxxxxx.myappE/RecyclerView: No adapter attached; skipping layout
08-09 01:23:41.682 7655-7655/com.xxxxxx.myappE/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxx.myapp, PID: 7655
    android.content.res.Resources$NotFoundException: Resource ID #0xfffffe6c
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2134)
        at android.content.res.Resources.getLayout(Resources.java:1143)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1518)
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1022)
        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:52)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:774)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)

我已经确认不是因为漏添加了布局文件，因为不打包时都是正常的：
public ArticleAdapter(Context context, List<Article> data) {
        super(data);
        mContext = context;
        addItemType(ArticleItem.ONE_SMALL_IMAGE, R.layout.one_small_image_article_item);
        addItemType(ArticleItem.ONE_BIG_IMAGE, R.layout.one_big_image_article_item);
        addItemType(ArticleItem.THREE_SMALL_IMAGE, R.layout.three_small_image_article_item);
    }

**Comment by lpc904586134** [comment]
getItemType没有找到对应的类型，返回了这个TYPE_NOT_FOUND = -404;，-404就是0xfffffe6c
