### ISSUE TITLE
2.9.41版 继承 BaseQuickAdapter 还是会出现 NoSuchMethodException

### ISSUE THREAD

**Issue by LandChanning** [CymChad/BaseRecyclerViewAdapterHelper#2416]
版本：2.9.41

使用场景：
1、kotlin，继承 BaseQuickAdapter 实现自定义 Adapter，重写了 createBaseViewHolder 方法生成自定义的 ViewHolder。
2、自定义的 Adapter 和 ViewHolder 都是单独的类且位于单独 kt 文件中。
3、使用过程中，通过 addHeaderView 方法添加了一个头布局。

复现：每次进入该列表页都会打印异常日志。

代码：
```
class MyAdapter() : BaseQuickAdapter<Entity, CoverVH>(R.layout.item_slist_list) {
    override fun createBaseViewHolder(parent: ViewGroup, layoutResId: Int): CoverVH {
        return if (layoutResId == R.layout.item_slist_list) {
            CoverVH(LayoutInflater.from(parent.context).inflate(layoutResId, parent, false))
        } else {
            super.createBaseViewHolder(parent, layoutResId)
        }
    }
}

class CoverVH(v: View)
```

异常log：
```
08-22 10:43:46.054 18778-18778/com.my.list W/System.err: java.lang.NoSuchMethodException: <init> [class android.view.View]
08-22 10:43:46.055 18778-18778/com.my.list W/System.err:     at java.lang.Class.getConstructor0(Class.java:2204)
        at java.lang.Class.getDeclaredConstructor(Class.java:2050)
        at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:1067)
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1045)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:765)

08-22 10:43:46.056 18778-18778/com.my.list W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
```

请问是我继承重写的方式有问题吗？感觉频繁抛出并打印异常会造成页面卡顿。

**Comment by AllenCoder** [comment]
kotlin 版本写法参照这个demo [https://github.com/AllenCoder/BRVAH_kotlin](https://github.com/AllenCoder/BRVAH_kotlin)
