### ISSUE TITLE
java.lang.NullPointerException指向源码相关位置，有log日志文件，麻烦指导下，谢谢~

### ISSUE THREAD

**Issue by payneHwang** [CymChad/BaseRecyclerViewAdapterHelper#2436]
这个是log日志：
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.chad.library.adapter.base.BaseViewHolder com.chad.library.adapter.base.BaseViewHolder.setAdapter(com.chad.library.adapter.base.BaseQuickAdapter)' on a null object reference
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:765)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6365)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5563)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`
显示在这个位置上holder报空了，使用的版本是2.9.30版本，目前我这边一直无法复现，但是线上版本bug平台已经有很多次这样的错误信息，麻烦解答下。
![image](https://user-images.githubusercontent.com/16483463/44698614-45b29700-aab3-11e8-9073-eb6230329a6b.png)

**Comment by AllenCoder** [comment]
引用this为空 ，请修复自己的代码写法
