### ISSUE TITLE
BaseMultiItemQuickAdapter 报错

### ISSUE THREAD

**Issue by saky0542** [CymChad/BaseRecyclerViewAdapterHelper#244]
java.lang.NullPointerException
                                                                                 at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:42)
                                                                                 at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:38)
                                                                                 at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:515)
                                                                                 at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:41)

**Comment by CymChad** [comment]
你每一个数据数据没有setItemType。
