### ISSUE TITLE
嵌套viewpager

### ISSUE THREAD

**Issue by shuiming11** [CymChad/BaseRecyclerViewAdapterHelper#2482]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 2 Pager id: com.souyute.product_image:id/item_pager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class com.souyute.product_image.ui.adapter.ItemImageAdapter
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1137)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2190)
        at android.view.View.dispatchTouchEvent(View.java:11794)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
当我在item中嵌套viewpager时会发生以上错误，我已经调用notifyDataSetChanged了仍然报错，请问有什么办法可以解决吗

**Comment by CymChad** [comment]
请提供复现demo
