### ISSUE TITLE
BaseMultiItemQuickAdapter#removeDataFromParent 空指针异常

### ISSUE THREAD

**Issue by GreenhairTurtle** [CymChad/BaseRecyclerViewAdapterHelper#2565]
```java
 /**
     * 移除子控件时，移除父控件实体类中相关子控件数据，避免关闭后再次展开数据重现
     *
     * @param child 子控件实体
     */
    protected void removeDataFromParent(T child) {
        int position = getParentPosition(child);
        if (position >= 0) {
            IExpandable parent = (IExpandable) mData.get(position);
            parent.getSubItems().remove(child);
        }
    }
```

当父布局没用子项时，调用adapter.remove(position)会报空指针异常
```java
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.remove(java.lang.Object)' on a null object reference
        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.removeDataFromParent(BaseMultiItemQuickAdapter.java:108)
        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.remove(BaseMultiItemQuickAdapter.java:77)
```
因为
> parent.getSubItems()为空

**Comment by actionbar** [comment]
同样遇到这个问题，目前我的解决办法是，在父级里面如果没有子项数据的话，就给父级初始化一个子项的空集合
.setSubItems(new ArrayList<>());
