### ISSUE TITLE
上拉加载数组下标越界

### ISSUE THREAD

**Issue by Rtsunoath** [CymChad/BaseRecyclerViewAdapterHelper#260]
list中有二十条数据，每次滑动到底部就会cash，是哪里出问题了么

**Comment by Rtsunoath** [comment]
java.lang.IndexOutOfBoundsException: Invalid index 20, size is 20
                                                                   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                   at java.util.ArrayList.get(ArrayList.java:308)
                                                                   at com.sinaweibo.adapter.HomeAdapter.convert(HomeAdapter.java:39)
                                                                   at com.sinaweibo.adapter.HomeAdapter.convert(HomeAdapter.java:28)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:538)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                   at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                   at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                   at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4357)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by CymChad** [comment]
你用的是新的版本吗？

**Comment by Rtsunoath** [comment]
是呀，最新版本的

**Comment by CymChad** [comment]
贴代码

**Comment by CymChad** [comment]
贴代码

**Comment by CymChad** [comment]
你可以试下，我们最新的demo，我测试过没有问题。昨天有人和你出现的bug一样，原因就是在上拉的时候用addData出现的错误，但是他的版本不是2.0，更新到2.0就好了。

**Comment by CymChad** [comment]
如果不是2.0，不想更换新版本的话，可以按照以前的API来做上拉加载，https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/old_doc-cn
