### ISSUE TITLE
ViewPage+Fragment列表中添加Header的情况下，重新切换回来的时候报错，The specified child already has a parent.

### ISSUE THREAD

**Issue by lijunguan** [CymChad/BaseRecyclerViewAdapterHelper#261]
开始以为是，切换回来后重新执行生命周期，重复添加头部导致的，1.将Adpter 添加头部 移至onCreate(), 也不行， 2. 在onViewCreate 中添加头部之前 先移除所有header 也还是不行。   debug，大概是在执行完viewpage的页面切换后，重行布局页面的时候出的错。       错误信息 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                 at android.view.ViewGroup.addViewInner(ViewGroup.java:4070)
                                                                 at android.view.ViewGroup.addView(ViewGroup.java:3920)
                                                                 at android.view.ViewGroup.addView(ViewGroup.java:3861)
                                                                 at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:638)
                                                                 at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7054)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7012)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7000)
                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1428)
                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:598)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1761)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                 at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                 at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1319)
                                                                 at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:817)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                 at android.view.View.layout(View.java:16112)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                 at android.view.View.layout(View.java:16112)
                                                             	at andr

**Comment by shichaohui** [comment]
应该是你的写法有问题吧，我试过了ViewPager+Fragment adapter addHeader，并没有出现你提出的bug。
我的写法：
