### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by zhangshangkun** [CymChad/BaseRecyclerViewAdapterHelper#2619]
Process: com.zpf.xjgu, PID: 22756
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
                                                                  at com.chad.library.adapter.base.BaseViewHolder.setVisible(BaseViewHolder.java:231)
                                                                  at com.chad.library.adapter.base.loadmore.LoadMoreView.visibleLoading(LoadMoreView.java:57)
                                                                  at com.chad.library.adapter.base.loadmore.LoadMoreView.convert(LoadMoreView.java:34)
                                                                  at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:928)
                                                                  at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                  at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                  at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                  at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                  at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:171)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6651)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by yangfeng1994** [comment]
是不是你item中的view的id没有找到？或者是你bean类里面的数据为空？
