### ISSUE TITLE
刷新带有adapter的fragment，频繁报错。

### ISSUE THREAD

**Issue by xilost** [CymChad/BaseRecyclerViewAdapterHelper#2654]
1. 版本号：2.9.44
2.目前的需求是，再底层页做了一些用户相关的操作，会主动去刷新首页的某个fragment（刷新通过getItemPosition返回POSITION_NONE实现），里面带有Adapter，很容易发生crash。
3. crash日志：
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6796)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2727)
    at android.view.View.layout(View.java:16673)
    at android.view.ViewGroup.layout(ViewGroup.java:5476)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2304)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2033)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1209)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6330)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
    at android.view.Choreographer.doCallbacks(Choreographer.java:674)
    at android.view.Choreographer.doFrame(Choreographer.java:610)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:179)
    at android.app.ActivityThread.main(ActivityThread.java:5769)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by Panxiaoan1993** [comment]
是否有用到emptyview？fragment是否已被回收？如果有使用viewpager，确保viewpager的offscreenPageLimit跟fragment的个数对应，先保证刷新的时候fragment不是处于销毁状态

**Comment by xilost** [comment]
没有有emptyView，不过fragment有被回收的可能，RecyclerView带有header 发自Rossi 在2019年03月22日 17:02，JimmyPan 写道： 是否有用到emptyview？fragment是否已被回收？如果有使用viewpager，确保viewpager的offscreenPageLimit跟fragment的个数对应，先保证刷新的时候fragment不是处于销毁状态 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xilost** [comment]
@Panxiaoan1993 
没有有emptyView，不过fragment有被回收的可能，RecyclerView带有header

**Comment by TpOut** [comment]
我也是类似的问题。fragment在viewpager里面，但是我是在当前页面重复刷新，崩溃
fragment的主要结构是recyclerview，网络请求后动态添加header，并且在１秒内移除
这个时候如果刷新多次，导致第二次添加header在第一次header移除的短时间内，就会崩溃（这是现象）

但是写了个demo，直接remove并且add，是肯定不会蹦的。。
有点懵逼，不知道啥情况

**Comment by xilost** [comment]
现在可以复现问题了，只要使用addHeaderView，当前fragment页面横竖屏切换时，直接崩溃，报问题中的错误。

**Comment by CrazySongCN** [comment]
我也遇到这个问题，目前每次刷新数据时都先adapter.setNewData(null)，虽然不崩了，但是影响用户体验。。。下个版本看看重构下这块

**Comment by xilost** [comment]
没有解决就直接关闭了？
