### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wuzhaohui026** [CymChad/BaseRecyclerViewAdapterHelper#269]
测试断网恢复数据，在不满一屏的页面会出现这个问题。

FATAL EXCEPTION: main
                                                                         Process: cn.smartevents.gulfinfo, PID: 31462
                                                                         java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                             at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5177)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:5248)
                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7678)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3333)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:598)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1761)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1761)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15718)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2129)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1103)
                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5944)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:601)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:571)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                         	at android.os.Handler.handleCallback(

**Comment by CymChad** [comment]
贴代码

**Comment by Ludejin** [comment]
attached views may not be recycled。我觉得是没有remove掉一些多余的View

**Comment by CymChad** [comment]
@Ludejin 正解

**Comment by CymChad** [comment]
http://stackoverflow.com/questions/30693821/fragment-with-recyclerview-java-lang-illegalargumentexception-scrapped-or-att
