### ISSUE TITLE
RecyclerView设置为水平问题

### ISSUE THREAD

**Issue by lhj1079947827** [CymChad/BaseRecyclerViewAdapterHelper#2721]
recyclerView设置为LinearManager.horizontal的时候,adapter的布局宽度永远是match_parent，自己设置的值无效

**Comment by yangfeng1994** [comment]
你的item中的布局设置的是 match_parent 吗？

**Comment by lhj1079947827** [comment]
不是，是我设置的一个固定值，如设置两百，但实际出来的还是match_parent 。完全不能自定义自己的宽度大小

**Comment by 13120241790** [comment]
@lhj1079947827  @limuyang2   @1109993488 
你好 ， BaseMultiItemQuickAdapter 里面的子模块如果有需要用到 RecyclerView 是不是必须用 BaseQuickAdapter? 不能用原生的 RecyclerView.Adapter 是吗 ？ 


```
public class MultiSampleAdapter extends BaseMultiItemQuickAdapter
convert 中
        LinearLayoutManager layoutManager = new LinearLayoutManager(context);
        layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(new HouseTypeItemAdapter(tempDataList, context));

```

用的普通的 recyclerView 和 adapter crash 

crash log
```
2019-07-18 19:19:49.519 19482-19482/? E/CrashReport: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
        at com.comjia.kanjiaestate.sample.view.adapter.HouseTypeItem.handleConvert(HouseTypeItem.java:52)
        at com.comjia.kanjiaestate.sample.view.adapter.MultiSampleAdapter.convert(MultiSampleAdapter.java:46)
        at com.comjia.kanjiaestate.sample.view.adapter.MultiSampleAdapter.convert(MultiSampleAdapter.java:15)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:951)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)

```

不胜感激

**Comment by shichaohui** [comment]
@lhj1079947827 未能重现这个问题。能提供复现步骤吗？最好提供一下有该问题的 Demo 。

**Comment by tanzhihao1qaz** [comment]
我也遇到过，当时用的是3.0.4版本，换了3.0.6就没有这个问题，但是变成了item长度变成固定的一段，大概是50dp的长度，我设置的明明是120dp
