### ISSUE TITLE
NullPointerException when SimpleClickListener.onInterceptTouchEvent

### ISSUE THREAD

**Issue by jasonni** [CymChad/BaseRecyclerViewAdapterHelper#276]
`  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPressed(boolean)' on a null object reference
                      at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:51)
                      at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2479)
                      at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2607)
                      at android.view.View.dispatchTouchEvent(View.java:9301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2659)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1787)
                      at android.app.Dialog.dispatchTouchEvent(Dialog.java:787)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2620)
                      at android.view.View.dispatchPointerEvent(View.java:9521)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                      at java.lang.reflect.Method.invoke(Native Method)`

**Comment by jasonni** [comment]
Is resetPressedView



        private void resetPressedView(final View pressedView) {
            pressedView.postDelayed(new Runnable() {
                @Override
                public void run() {
                    pressedView.setPressed(false);
                }
            }, 100);
            mIsPrepressed = false;
            mPressedView = null;
        }


 run earlier than
 


        if (!mGestureDetector.onTouchEvent(e) && e.getActionMasked() == MotionEvent.ACTION_UP && mIsShowPress) {
            mPressedView.setPressed(false);
            mIsShowPress = false;
            mIsPrepressed = false;
            mPressedView = null;

        }
        

?

**Comment by AllenCoder** [comment]
thank you ,i  find this bug，  i will fix it

**Comment by CymChad** [comment]
fix bug

 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:v2.0.4'
