### ISSUE TITLE
java.lang.IllegalArgumentException: itemView may not be null

### ISSUE THREAD

**Issue by eren000** [CymChad/BaseRecyclerViewAdapterHelper#2784]
java.lang.IllegalArgumentException: itemView may not be null
at androidx.recyclerview.widget.RecyclerView$ViewHolder.(RecyclerView.java:10833)
at com.chad.library.adapter.base.BaseViewHolder.(BaseViewHolder.java:79)
at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1045)
at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:763)
at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:66)
at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
at android.os.Handler.handleCallback(Handler.java:907)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:216)

![image](https://user-images.githubusercontent.com/5646528/59553135-445f4600-8fc3-11e9-8d06-af27bd284b38.png)

重写getItemViewType return position,没有header和footer
加载了大量图片,显示了300张左右,再往下滑动崩溃

**Comment by AllenCoder** [comment]
1 .图片加载是否引用了第三方框架？
2. 如果没有引用，检查一下，图片的管理是否恰当
3.重写getItemViewType return position是否导致指定的position没有对应的itemView

**Comment by eren000** [comment]
[demo.zip](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/files/3328784/demo.zip)

MediaChooseAdapter  72行

**Comment by 1109993488** [comment]
建议不要修改getItemViewType,框架内部占用了0x111,0x222,0x333,0x555(修改可能会对其他人有影响,暂不考虑修改)

**Comment by 1109993488** [comment]
如果非要用你可以用负数

**Comment by tank2014gz** [comment]
奇缘,跟框架内部使用了同样的0x111,占坑

**Comment by WShaobin** [comment]
> 建议不要修改getItemViewType,框架内部占用了0x111,0x222,0x333,0x555(修改可能会对其他人有影响,暂不考虑修改)

就是这里0x111的问题，数据太多了0x111=273,导致老是第273条的时候报错，希望作者改大一点

**Comment by zxm1243** [comment]
> > 建议不要修改getItemViewType,框架内部占用了0x111,0x222,0x333,0x555(修改可能会对其他人有影响,暂不考虑修改)
> 
> 就是这里0x111的问题，数据太多了0x111=273,导致老是第273条的时候报错，希望作者改大一点

请问这个问题解决了吗？

**Comment by Wynsbin** [comment]
> > > 建议不要修改getItemViewType,框架内部占用了0x111,0x222,0x333,0x555(修改可能会对其他人有影响,暂不考虑修改)
> > 
> > 
> > 就是这里0x111的问题，数据太多了0x111=273,导致老是第273条的时候报错，希望作者改大一点
> 
> 请问这个问题解决了吗？

最后选择重写getItemViewType，虽然这种方式有点欠佳，但是作者不改只能自己修改。
```
@Override
    public int getItemViewType(int position) {
        int header = getHeaderLayoutCount();
        int footer = getFooterLayoutCount();
        if ((header == 0 && position == HEADER_VIEW) || (footer == 0 && position == FOOTER_VIEW)) {
            return 0;
        }
        if (header > position) {
            return super.getItemViewType(position);
        }
        if (mData.size() > position - header) {
            return position;
        } else {
            return super.getItemViewType(position);
        }
}
```
