### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder

### ISSUE THREAD

**Issue by 1130381752** [CymChad/BaseRecyclerViewAdapterHelper#2785]
问题描述：
当我点击列表中的项目进行删除时（如最下面的代码中，删除了本地list那项并立马调用了adapter的notifyItemRemoved(pos)方法刷新），但是会闪退，后来发现是跟setOnLoadMoreListener()方法有关系，目前只是重写了LinearLayoutManager的onLayoutChildren方法把IndexOutOfBoundsException catch住了，但是很想知道为什么会闪退，都是很正常的用法啊（我修改了外部数据集，就立马调用adpter刷新数据的方法使得内外部数据集一致了啊）。

错误日志：
`AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hk.javalearn, PID: 7863
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3ac9f35 position=0 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{6a9fd5b VFED..... ......I. 0,134-1080,418 #7f080098 app:id/rv_list}, adapter:com.hk.javalearn.activity.TestActivity$MyApdater@134de22, layout:androidx.recyclerview.widget.LinearLayoutManager@f7d20b3, context:com.hk.javalearn.activity.TestActivity@761647c
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3330)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
        at android.view.View.measure(View.java:23169)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2725)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
2019-06-16 21:18:57.705 7863-7863/com.hk.javalearn E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

产生此问题的所有相关代码：
`public class TestActivity extends SwipeBackActivity {
    @BindView(R.id.ll_full)
    LinearLayout llFull;
    @BindView(R.id.rv_list)
    RecyclerView rvList;

    private List<String> list = new ArrayList<>();
    private MyApdater adapter;

    @Override
    protected int getLayoutId() {
        return R.layout.activity_test;
    }
    @Override
    protected void initView() {
        ButterKnife.bind(this);
        setAdapter();
        loadData();
    }
    private void loadData() {
        list.add("");
        adapter.notifyDataSetChanged();
        adapter.loadMoreEnd();
    }
    private void setAdapter() {
        adapter = new MyApdater(R.layout.item_button, list);
        adapter.setPreLoadNumber(2);
        adapter.setOnLoadMoreListener(() -> {
        });
        rvList.setLayoutManager(new LinearLayoutManager(this));
//        rvList.setLayoutManager(new FixLinearLayoutManager(this));
        rvList.setAdapter(adapter);
    }
    public void back(View view) {
        finish();
    }
    class MyApdater extends BaseQuickAdapter<String, BaseViewHolder>
    {

        MyApdater(int layoutResId, @Nullable List<String> data) {
            super(layoutResId, data);
        }
        @Override
        protected void convert(BaseViewHolder helper, String item) {
            helper.setOnClickListener(R.id.btn_name, v -> {
                int position = helper.getAdapterPosition();
                list.remove(position);
                adapter.notifyItemRemoved(position);
            });
        }
    }
}`

**Comment by AllenCoder** [comment]
参考 [https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2132](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/2132)

**Comment by helloworld10010** [comment]
解决了吗，我这没有上下同时拉。倒是用了diffutil，不知道是不是它的锅
