### ISSUE TITLE
自定义BaseViewHolder出现ClassCastException

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [CymChad/BaseRecyclerViewAdapterHelper#2854]
错误：
UncaughtException detected: java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.sharker.ui.lesson.adapter.VideoRecyclerViewAdapter$MyViewHolder
        at com.sharker.ui.lesson.adapter.VideoRecyclerViewAdapter.onBindViewHolder(VideoRecyclerViewAdapter.java:19)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
        at android.view.View.layout(View.java:17666)
        at android.view.ViewGroup.layout(ViewGroup.java:5577)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
    	at android.app.ActivityThread.main(ActivityThread.java:6

**Comment by DancingSnowInFingertips** [comment]
public class VideoRecyclerViewAdapter extends BaseQuickAdapter<ShortCourse, VideoRecyclerViewAdapter.MyViewHolder> {

    public VideoRecyclerViewAdapter() {
        super(R.layout.item_video_list);
    }

    @Override
    protected MyViewHolder createBaseViewHolder(View view) {
        return super.createBaseViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int position, @NonNull List<Object> payloads) {
        super.onBindViewHolder(holder, position, payloads);
        if (payloads.isEmpty()) {
            onBindViewHolder(holder, position);
        } else {
            ShortCourse bean = mData.get(position);
            if (bean == null) {
                return;
            }
            ImageButton bn = holder.getView(R.id.collect);
            bn.setSelected(bean.isCollectStatus());
        }
    }

    @Override
    protected void convert(MyViewHolder helper, ShortCourse item) {
        VideoView videoView = helper.getView(R.id.video_player);
        videoView.setUrl(item.getShortVideoUrl());
        videoView.setVideoController(helper.controller);
        Glide.with(mContext)
                .load(StringUtil.unitUrl(item.getShortVideoCover()))
                .into(helper.controller.getThumb());
        helper.setText(R.id.tv_title, item.getShortVideoTitle())
                .setText(R.id.tv_subtitle, item.getAlbumTitle())
                .addOnClickListener(R.id.collect)
                .addOnClickListener(R.id.share);
        ImageButton bn = helper.getView(R.id.collect);
        bn.setSelected(item.isCollectStatus());
    }

    public class MyViewHolder extends BaseViewHolder {
        private StandardVideoController controller;

        public MyViewHolder(View view) {
            super(view);
            controller = new StandardVideoController(view.getContext());
            controller.setFullButtonVisible(false);
        }
    }
}

**Comment by DancingSnowInFingertips** [comment]
我的问题：不管是内部类还是外部类，都会又这个问题，混淆已经配置，debug时候打开就会崩溃
引用的版本：2.9.45-androidx

**Comment by DancingSnowInFingertips** [comment]
更新到2.9.49-androidx,并添加

 @Override
    protected MyViewHolder createBaseViewHolder(View view) {
        return new MyViewHolder(view);
    }

错误解决

**Comment by zdongcoding** [comment]
> 更新到2.9.49-androidx,并添加
> 
> @override
> protected MyViewHolder createBaseViewHolder(View view) {
> return new MyViewHolder(view);
> }
> 
> 错误解决

我 只添加  2.9.49-androidx   就好了， 不需要加下面的

**Comment by caldremch** [comment]
#添加以下混淆规则可解决
#保留继承于BaseViewHolder的内部类不被混淆
-keep class $ extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
(...);
}
