### ISSUE TITLE
    java.lang.NullPointerException: GridSectionAverageGapItemDecoration$Section.startPos' on a null object reference

### ISSUE THREAD

**Issue by Wanchen7** [CymChad/BaseRecyclerViewAdapterHelper#2876]
版本号：2.9.46

问题描述：
参考demo使用GridSectionAverageGapItemDecoration
 1、当删除data数据的Header+Body的一项后
 2、界面上的其他元素隐藏使recyclerview大小调整
 3、调用setNewData  

调试的时候看，应该是执行到2 还没到3就crash了

伪代码：

```
//初始化
list.add(header);
list.add(body);
list.add(body);
list.add(header);
list.add(body);
list.add(body);
adapter.setNewData(list);

//删除数据
 list.remve(0);
 list.remve(1);
 titleBar.setVisible(GONE);
 adapter.setNewData(list);

```

日志：
2019-08-26 19:19:50.374 5674-5674/com.album E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.album, PID: 5674
    java.lang.NullPointerException: Attempt to read from field 'int com.album.portal.homepage.view.adapter.GridSectionAverageGapItemDecoration$Section.startPos' on a null object reference
        at com.album.portal.homepage.view.adapter.GridSectionAverageGapItemDecoration.getItemOffsets(GridSectionAverageGapItemDecoration.java:141)
        at androidx.recyclerview.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:5100)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.calculateItemDecorationsForChild(RecyclerView.java:9679)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:595)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3521)
        at android.view.View.measure(View.java:22002)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22002)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22002)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
        at android.view.View.measure(View.java:22002)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:609)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:743)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:97)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1874)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:813)
        at android.view.View.measure(View.java:22002)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
        at android.view.View.measure(View.java:22002)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
2019-08-26 19:19:50.374 5674-5674/com.album E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by yangfeng1994** [comment]
你debug试一下，是不是因为你一出数据的时候，notify了，当item再去找条数据给View赋值的时候，获取到的数据是空的

**Comment by Wanchen7** [comment]
我的问题 sry
