### ISSUE TITLE
java.lang.reflect.GenericSignatureFormatErro导致频繁崩溃

### ISSUE THREAD

**Issue by WarriorYu** [CymChad/BaseRecyclerViewAdapterHelper#2920]
这是bugly收集的bug,只在一下这个机型出现。看着像是反射导致的。麻烦看一下具体原因
机型：荣耀 BND AL10 | Android 9,level 28

报错详细信息：
java.lang.reflect.GenericSignatureFormatError
	at libcore.reflect.GenericSignatureParser.expect(GenericSignatureParser.java:473)
	at libcore.reflect.GenericSignatureParser.parseClassTypeSignature(GenericSignatureParser.java:305)
	at libcore.reflect.GenericSignatureParser.parseClassSignature(GenericSignatureParser.java:234)
	at libcore.reflect.GenericSignatureParser.parseForClass(GenericSignatureParser.java:126)
	at java.lang.Class.getGenericSuperclass(Class.java:872)
	at com.chad.library.adapter.base.BaseQuickAdapter.getInstancedGenericKClass(BaseQuickAdapter.java:1)
	at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:3)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:9)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.a(RecyclerView.java:42)
	at androidx.recyclerview.widget.RecyclerView$Recycler.b(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Recycler.d(RecyclerView.java:11)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.a(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:114)
	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:101)
	at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:115)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:35)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.b(HeaderScrollingViewBehavior.java:21)
	at com.google.android.material.appbar.ViewOffsetBehavior.a(ViewOffsetBehavior.java:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.a(AppBarLayout.java:14)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:35)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:926)
	at android.view.View.layout(View.java:20960)
	at android.view.ViewGroup.layout(ViewGroup.java:6279)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:812)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Slack88** [comment]
![IMG_20210928_190411](https://user-images.githubusercontent.com/86712560/135136583-7d0d7852-6f91-43fb-9138-4cb495407ac5.jpg)
Warto wracać cena za sztukę nie gra roli,,🗓️
