### ISSUE TITLE
加载更多过程中上下滑动列表会报错

### ISSUE THREAD

**Issue by lololiu** [CymChad/BaseRecyclerViewAdapterHelper#296]
我在项目中开启了加载更多的功能，但是发现当有时候网络环境差，数据加载过慢时，在底部的loading转动的时候，上下滑动列表会报错：
> java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position  20(offset:20).state:21
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4659)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                 at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
                                                                                 at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
                                                                                 at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1529)
                                                                                 at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2486)

测试demo代码：
```java
        mListView = (RecyclerView) findViewById(R.id.lisview);
        List<String> list = new ArrayList<>();
        for (int i = 0; i < 20; i++) {
            list.add("item" + i);
        }
        mListView.setLayoutManager(new LinearLayoutManager(this));
        final MyAdapter adapter = new MyAdapter(this, R.layout.utem_layout, list);
        adapter.openLoadMore(20, true);
        adapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        List<String> list1 = new ArrayList<>();
                        for (int i = 0; i < 20; i++) {
                           list1.add("item" + (i + 20));
                        }
                        adapter.notifyDataChangedAfterLoadMore(list1, false);
                    }
                }, 5000);
            }
        });
        mListView.setAdapter(adapter);
```

**Comment by CymChad** [comment]
版本号？

**Comment by lololiu** [comment]
@CymChad  V1.7.5

**Comment by CymChad** [comment]
新的版本已经修复这个问题了，如果你不想大改，你可以使用v1.9.8
