### ISSUE TITLE
java.lang.IllegalArgumentException: itemView may not be null

### ISSUE THREAD

**Issue by sdgSnow** [CymChad/BaseRecyclerViewAdapterHelper#2990]
java.lang.IllegalArgumentException: itemView may not be null
        at androidx.recyclerview.widget.RecyclerView$ViewHolder.<init>(RecyclerView.java:10833)
        at com.chad.library.adapter.base.BaseViewHolder.<init>(BaseViewHolder.java:79)
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1014)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:753)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:68)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by sdgSnow** [comment]
我这个列表只要滑动到第两百多item的时候就必现，数量少就很正常，请问下这个是什么问题呢

**Comment by limuyang2** [comment]
麻烦给出一下版本号和demo，问题的可行性比较多，你现在提供的信息不足以排查

**Comment by sdgSnow** [comment]
public class RoomNumberAdapter extends BaseQuickAdapter<RoomNumberBean, BaseViewHolder> {
    private List<RoomNumberBean> beanList;
    private Context context;

    public RoomNumberAdapter(List<RoomNumberBean> beanList, Context context) {
        super(R.layout.item_room_number, beanList);
        this.beanList = beanList;
        this.context = context;
    }

    public void setData(List<RoomNumberBean> beanList) {
        this.beanList = beanList;
        notifyDataSetChanged();
    }

    @Override
    protected void convert(BaseViewHolder helper, RoomNumberBean item) {
        helper.setText(R.id.tv_build_room_name, item.getRoomName());
        helper.setText(R.id.tv_build_name, item.getBuildName());
    }

    @Override
    public int getItemCount() {
        return beanList.size();
    }

   @Override
    public int getItemViewType(int position) {
        return 0;
    }

你好，这个是我的adapter，版本是2.9.33，当这个list数据有几百之后就会出现

**Comment by limuyang2** [comment]
请问你为什么要自己管理data，自己重写getItemViewType？
有什么特殊原因么？
