### ISSUE TITLE
3.x版本重写GetItemCount()报错

### ISSUE THREAD

**Issue by DarrenWorks** [CymChad/BaseRecyclerViewAdapterHelper#2995]
版本：3.0.0-beta1
重写方法： 
return super.getItemCount() == mMax ? super.getItemCount() : super.getItemCount() + 1;
报错信息：
kotlin.KotlinNullPointerException
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:220)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:74)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7046)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6214)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6097)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6093)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3521)
        at android.view.View.measure(View.java:23454)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:23454)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:23454)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1535)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:581)
        at android.view.View.measure(View.java:23454)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
2019-12-24 11:19:32.170 27501-27501/com.office.btjt E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

由于核心逻辑基于新版本的provider无法切回旧版本，还望作者给予帮助，十分感谢

**Comment by limuyang2** [comment]
由于你改写了`getItemCount`，进行了+1操作。在`onCreateViewHolder`创建VH的时候，就被识别成多创建一个`loadMoreView`，而你没有实现`loadMore`模块。所以爆了空指针异常。

修改方法：请勿随意重写`getItemCount()`方法，如需修改data的数量，请重写`getDefItemCount()`方法

**Comment by limuyang2** [comment]
请查看`getItemCount()`方法源码，里面并不仅仅是返回`data`数量这么简单。
如果重写`getItemCount()`方法，那么`onCreateViewHolder()`方法逻辑也需要自己彻底重写，这回导致非常多的问题

**Comment by DarrenWorks** [comment]
> 由于你改写了`getItemCount`，进行了+1操作。在`onCreateViewHolder`创建VH的时候，就被识别成多创建一个`loadMoreView`，而你没有实现`loadMore`模块。所以爆了空指针异常。
> 
> **修改方法：**
> 请勿随意重写`getItemCount()`方法，如需修改data的数量，请重写`getDefItemCount()`方法

2.x版本我记得是可以修改的，我现在是要实现一个多图列表最后有个加一按钮（类似微信朋友圈发照片）的功能，刚才想了一下，getDefItemCount似乎也可以实现这个效果，不过我已经用修改数据源的方式实现了，不过还是谢谢帮助，重写方法应该可以实现的更简洁

**Comment by DarrenWorks** [comment]
> 请查看`getItemCount()`方法源码，里面并不仅仅是返回`data`数量这么简单。
> 如果重写`getItemCount()`方法，那么`onCreateViewHolder()`方法逻辑也需要自己彻底重写，这会导致非常多的问题



> > 由于你改写了`getItemCount`，进行了+1操作。在`onCreateViewHolder`创建VH的时候，就被识别成多创建一个`loadMoreView`，而你没有实现`loadMore`模块。所以爆了空指针异常。
> > **修改方法：**
> > 请勿随意重写`getItemCount()`方法，如需修改data的数量，请重写`getDefItemCount()`方法
> 
> 2.x版本我记得是可以修改的，我现在是要实现一个多图列表最后有个加一按钮（类似微信朋友圈发照片）的功能，刚才想了一下，getDefItemCount似乎也可以实现这个效果，不过我已经用修改数据源的方式实现了，不过还是谢谢帮助，重写方法应该可以实现的更简洁

尝试了一下，重写getDefItemCount依然会报同样的错误

**Comment by kylodw** [comment]
我也遇到同样的错误。。。也试着重写了getDefItemCount

**Comment by 1226362423** [comment]
+1 重写getDefItemCount没用
