### ISSUE TITLE
BaseNodeAdapter  BaseExpandNode 接收数据问题  beta7版本

### ISSUE THREAD

**Issue by lovemianhuatang** [CymChad/BaseRecyclerViewAdapterHelper#3023]
`public class CompanyDisciplinaryHead extends BaseExpandNode implements Serializable {

    // 标题
    private String title;
    // 类型;
    private Integer type;
    private List<BaseNode> childNode;

    public String getTitle() {
        return title;
    }

    public Integer getType() {
        return type;
    }

    /**
     * 重写此方法，返回子节点
     */
    @Nullable
    @Override
    public List<BaseNode> getChildNode() {
        return childNode;
    }
}`

网络请求框架没问题  是 private List<BaseNode> childNode;导致的  
 请问private List<BaseNode> childNode;  这个泛型不能换成自己的实体吗 ？

private List<BaseNode> childNode;    使体内这个接收网络数据时接收异常

Failed to invoke public com.chad.library.adapter.base.entity.node.BaseNode() with no args

W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    Caused by: java.lang.RuntimeException: Failed to invoke public com.chad.library.adapter.base.entity.node.BaseNode() with no args
        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableTakeUntil.subscribeActual(ObservableTakeUntil.java:38)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.lang.InstantiationException: Can't instantiate abstract class com.chad.library.adapter.base.entity.node.BaseNode
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)
    	... 31 more

**Comment by limuyang2** [comment]
需要自己封装一下

**Comment by limuyang2** [comment]
必须是BaseNode类型

**Comment by lovemianhuatang** [comment]
泛型为BaseNode类型接收不到数据   怎么封装？

**Comment by lovemianhuatang** [comment]
![image](https://user-images.githubusercontent.com/41498415/71759354-dccd0180-2ee6-11ea-8115-39c3caceae4c.png)

**Comment by lovemianhuatang** [comment]
@limuyang2 我使用mSubItems 接收 然后getChildNode()时添加到childNode返回。 这样对吗？

**Comment by limuyang2** [comment]
我不知道`CompanyDisciplinaryBody`是什么类型，如果是继承于`BaseNode`，那直接返回就可以了

**Comment by limuyang2** [comment]
对于面向对象编程，三大要素：**继承、多态、封装**。
首先，你需要理解什么是**继承**：
举例：
```
A继承BaseNode，B也是继承BaseNode，那么A和B都是BaseNode类型。
所以我回答了，只要数组里的child是BaseNode类型就可以。
```

再举例：
```java
A是继承BaseNode的，那么可直接返回（因为A属于BaseNode的子类）：

List<A> childList = new ArrayList();
/**
 * 重写此方法，返回子节点
 */
@Nullable
@Override
public List<BaseNode> getChildNode() {
    return childList;
}
```

**Comment by lovemianhuatang** [comment]
这个我知道。但是返回有警告

**Comment by lovemianhuatang** [comment]
![Uploading image.jpg…]()

**Comment by limuyang2** [comment]
> 泛型为BaseNode类型接收不到数据 怎么封装？

接受不到数据是什么意思？

**Comment by lovemianhuatang** [comment]
直接用List<BaseNode>接收不到后台的值   要用List<XXX>   XXX继承自BaseNode

**Comment by lovemianhuatang** [comment]
![image](https://user-images.githubusercontent.com/41498415/71777393-4417ae00-2fda-11ea-89bc-841e9a93cf78.png)
![image](https://user-images.githubusercontent.com/41498415/71777402-5eea2280-2fda-11ea-95c9-148efcc9929b.png)
我的CompanyDisciplinaryBody是继承了BaseNode 的  但是返回报错getChildNode()

**Comment by limuyang2** [comment]
可以这样返回的
```java
public class FirstNode extends BaseExpandNode {

    private List<SecondNode> childNode;

    public FirstNode(List<SecondNode> childNode) {
        this.childNode = childNode;
        setExpanded(false);
    }

    @Nullable
    @Override
    public List<BaseNode> getChildNode() {
        List<BaseNode> childNode = new ArrayList<BaseNode>(this.childNode);
        return childNode;
    }
}
```

**Comment by lovemianhuatang** [comment]
所以还是要自己new 一个是吗？

**Comment by limuyang2** [comment]
你之前写的是对的，一个意思，重写封装一下就行了

**Comment by lovemianhuatang** [comment]
按java的继承来说  我继承了父类  为什么会返回报错？ 有些奇怪

**Comment by limuyang2** [comment]
我这里额外多做一个解释，为何要用`List<BaseNode>`接收。
主要是为了应对 子节点会多种类型的情况：
```java
例如：A和B都是继承 BaseNode


    @Nullable
    @Override
    public List<BaseNode> getChildNode() {
        List<BaseNode> childNode = new ArrayList<BaseNode>();

        childNode.add(A);
        childNode.add(B);

        return childNode;
    }
```

**Comment by lovemianhuatang** [comment]
知道了  谢谢

**Comment by lovemianhuatang** [comment]
我还有个问题 在BaseNodeProvider 要用到BaseFragment或Activity  只能传进来吗？像下面这样？
![image](https://user-images.githubusercontent.com/41498415/71777506-f8660400-2fdb-11ea-83d4-c77cf18b517f.png)


![image](https://user-images.githubusercontent.com/41498415/71777515-09167a00-2fdc-11ea-937e-0be7d158e56a.png)


![image](https://user-images.githubusercontent.com/41498415/71777518-0fa4f180-2fdc-11ea-9469-37004678b545.png)


![image](https://user-images.githubusercontent.com/41498415/71777526-1f243a80-2fdc-11ea-96f7-4b71d520eb2f.png)

**Comment by limuyang2** [comment]
如果只是需要`context`的话，直接用`getContenxt()`就行了。
其它的，只能传进去了

**Comment by lovemianhuatang** [comment]
ok  谢谢

**Comment by monotcoder** [comment]
kotlin中gson解析报 Failed to invoke public ***... with no args

![WechatIMG9977](https://user-images.githubusercontent.com/18587755/147083313-c341aba9-1e97-4dcb-852c-ad1f4206e390.jpeg)

按照截图所示将注释掉的写法替换成大括号里面的写法

主要解决 with no args 问题
