### ISSUE TITLE
Take bitmap screenshot of whole recycler view

### ISSUE THREAD

**Issue by omkar-tenkale** [CymChad/BaseRecyclerViewAdapterHelper#3036]
Normal solutions of taking recycler view screenshot were not working with this library.

So i found  way to do this.

```
   public  Bitmap getRecyclerViewScreenshot(RecyclerView view) {
        int size = view.getAdapter().getItemCount();
        int topheight = adapter.getHeaderLayout().getMeasuredHeight();
        int bottomheight = adapter.getFooterLayout().getMeasuredHeight();
        RecyclerView.ViewHolder holder = view.getAdapter().createViewHolder(view, 0);
        view.getAdapter().onBindViewHolder(holder, 0);
        holder.itemView.measure(View.MeasureSpec.makeMeasureSpec(view.getWidth(), View.MeasureSpec.EXACTLY),
                View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
        holder.itemView.layout(0, 0, holder.itemView.getMeasuredWidth(), holder.itemView.getMeasuredHeight());
        Bitmap bigBitmap = Bitmap.createBitmap(view.getMeasuredWidth(), (holder.itemView.getMeasuredHeight() * size)+topheight+bottomheight,
                Bitmap.Config.ARGB_8888);
        Canvas bigCanvas = new Canvas(bigBitmap);
        bigCanvas.drawColor(Color.WHITE);
        Paint paint = new Paint();
        int iHeight = 0;
        holder.itemView.setDrawingCacheEnabled(true);
        holder.itemView.buildDrawingCache();

        Bitmap headerBitmap= loadBitmapFromView(adapter.getHeaderLayout());
        bigCanvas.drawBitmap(headerBitmap, 0f, iHeight, paint);
        iHeight+=topheight;
        bigCanvas.drawBitmap(holder.itemView.getDrawingCache(), 0f, iHeight, paint);
        holder.itemView.setDrawingCacheEnabled(false);
        holder.itemView.destroyDrawingCache();
        iHeight += holder.itemView.getMeasuredHeight();
        for (int i = 1; i < size; i++) {
            view.getAdapter().onBindViewHolder(holder, i);
            holder.itemView.setDrawingCacheEnabled(true);
            holder.itemView.buildDrawingCache();
            bigCanvas.drawBitmap(holder.itemView.getDrawingCache(), 0f, iHeight, paint);
            iHeight += holder.itemView.getMeasuredHeight();
            holder.itemView.setDrawingCacheEnabled(false);
            holder.itemView.destroyDrawingCache();
        }
        Bitmap footerBitmap= loadBitmapFromView(adapter.getFooterLayout());
        bigCanvas.drawBitmap(footerBitmap, 0f, iHeight, paint);

        return bigBitmap;
    }

    public  Bitmap loadBitmapFromView(View v1) {
//        v.layout(v.getLeft(), v.getTop(), v.getRight(), v.getBottom());

//        Bitmap b = Bitmap.createBitmap( v.getLayoutParams().width, v.getLayoutParams().height, Bitmap.Config.ARGB_8888);
//        Canvas c = new Canvas(b);
//        v.layout(v.getLeft(), v.getTop(), v.getRight(), v.getBottom());
//        v.draw(c);
//        return b;
        Bitmap bitmap;
        v1.setDrawingCacheEnabled(true);
// bitmap = Bitmap.createBitmap(v1.getDrawingCache());
        bitmap = loadBitmapFromView(v1, v1.getWidth(), v1.getHeight());
        v1.setDrawingCacheEnabled(false);
        return bitmap;
    }

    public static Bitmap loadBitmapFromView(View v, int width, int height) {
        Bitmap b = Bitmap.createBitmap(width , height, Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(b);
        v.layout(0, 0, width, height);
//Get the view’s background
        Drawable bgDrawable =v.getBackground();
        if (bgDrawable!=null)
//has background drawable, then draw it on the canvas
            bgDrawable.draw(c);
        else
//does not have background drawable, then draw white background on the canvas
            c.drawColor(Color.WHITE);
        v.draw(c);
        return b;
    }


    public void scrollUp() {
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                final MotionEvent event = MotionEvent.obtain(System.currentTimeMillis(), System.currentTimeMillis(), MotionEvent.ACTION_DOWN, rvInvoice.getWidth() / 2, rvInvoice.getHeight() / 2, 0);
                dispatchTouchEvent(event);
                event.recycle();
            }
        });

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                final MotionEvent event = MotionEvent.obtain(System.currentTimeMillis(), System.currentTimeMillis(), MotionEvent.ACTION_MOVE, rvInvoice.getWidth() / 2, rvInvoice.getHeight() / 2, 0);
                dispatchTouchEvent(event);
                event.recycle();
            }
        }, 50);

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                final MotionEvent event = MotionEvent.obtain(System.currentTimeMillis(), System.currentTimeMillis(), MotionEvent.ACTION_MOVE, rvInvoice.getWidth() / 2, rvInvoice.getHeight() / 2 - 400, 0);
                dispatchTouchEvent(event);
                event.recycle();
            }
        }, 100);

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                final MotionEvent event = MotionEvent.obtain(System.currentTimeMillis(), System.currentTimeMillis(), MotionEvent.ACTION_UP, rvInvoice.getWidth() / 2, rvInvoice.getHeight() / 2 - 400, 0);
                dispatchTouchEvent(event);
                event.recycle();
            }
        }, 200);
    }

```

Before calling  getRecyclerViewScreenshot(),
I have to manually load footer by programatically scrolling to bottom,

```
 rvInvoice.scrollToPosition(adapter.getData().size());
//Reached last element,footer still not loaded,swipe up to bring footer on screen 
  scrollUp(); 
getRecyclerViewScreenshot();
```

**Comment by omkar-tenkale** [comment]
Could there be an improved version of this built in with the library?

**Comment by limuyang2** [comment]
if use `LinearLayoutManager`, this method works fine.
```java
    public Bitmap getScreenshotFromRecyclerView(RecyclerView view) {
        RecyclerView.Adapter adapter = view.getAdapter();
        Bitmap bigBitmap = null;
        if (adapter != null) {
            int size = adapter.getItemCount();
            int height = 0;
            Paint paint = new Paint();
            int iHeight = 0;
            final int maxMemory = (int) (Runtime.getRuntime().maxMemory() / 1024);

            // Use 1/8th of the available memory for this memory cache.
            final int cacheSize = maxMemory / 8;
            LruCache<String, Bitmap> bitmaCache = new LruCache<>(cacheSize);
            for (int i = 0; i < size; i++) {
                RecyclerView.ViewHolder holder = adapter.createViewHolder(view, adapter.getItemViewType(i));
                adapter.onBindViewHolder(holder, i);
                holder.itemView.measure(View.MeasureSpec.makeMeasureSpec(view.getWidth(), View.MeasureSpec.EXACTLY),
                        View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
                holder.itemView.layout(0, 0, holder.itemView.getMeasuredWidth(), holder.itemView.getMeasuredHeight());

                Bitmap drawingCache = Bitmap.createBitmap(holder.itemView.getWidth(), holder.itemView.getHeight(), Bitmap.Config.RGB_565);
                Canvas canvas = new Canvas(drawingCache);
                canvas.drawColor(Color.WHITE);
                holder.itemView.draw(canvas);

                bitmaCache.put(String.valueOf(i), drawingCache);
                
                height += holder.itemView.getMeasuredHeight();
            }

            bigBitmap = Bitmap.createBitmap(view.getMeasuredWidth(), height, Bitmap.Config.ARGB_8888);
            Canvas bigCanvas = new Canvas(bigBitmap);
            bigCanvas.drawColor(Color.WHITE);

            for (int i = 0; i < size; i++) {
                Bitmap bitmap = bitmaCache.get(String.valueOf(i));
                bigCanvas.drawBitmap(bitmap, 0f, iHeight, paint);
                iHeight += bitmap.getHeight();
                bitmap.recycle();
            }

        }
        return bigBitmap;
    }
```

**Comment by limuyang2** [comment]
reference [stackoverflow](https://stackoverflow.com/questions/30085063/take-a-screenshot-of-recyclerview-in-full-length)

**Comment by omkar-tenkale** [comment]
Tried this approach before,app crashes with

```
 java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
```

**Comment by omkar-tenkale** [comment]
```
  for (int i = 0; i < size; i++) {
   //Crash here in above code             RecyclerView.ViewHolder holder = adapter.createViewHolder(view, adapter.getItemViewType(i));
```

**Comment by limuyang2** [comment]
> Tried this approach before,app crashes with
> 
> ```
>  java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
>         at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
> ```

In my case, this method works

**Comment by omkar-tenkale** [comment]
I'm using header and footer.
Did you use them too?

**Comment by limuyang2** [comment]
> I'm using header and footer.
> Did you use them too?

yes, I'm use them too

**Comment by omkar-tenkale** [comment]
Can you share the code?

I'll also try with the library sample
