### ISSUE TITLE
使用BaseNodeAdapter折叠效果 和  加载更多模块一起使用  点击展开子项的时候  多展开几项后会数组越界

### ISSUE THREAD

**Issue by zhizhi1hao** [CymChad/BaseRecyclerViewAdapterHelper#3123]
使用BaseNodeAdapter折叠效果 和  加载更多模块一起使用  点击展开子项的时候  多展开几项后会数组越界
代码示例：
public class ReceiveInfoAdapter extends BaseNodeAdapter implements LoadMoreModule {
    public ReceiveInfoAdapter() {
        super();
        addNodeProvider(new ReceiveProvider());
        addNodeProvider(new ReceiveOptionProvider());
    }

    @Override
    protected int getItemType(List<? extends BaseNode> list, int i) {
        BaseNode node = list.get(i);
        if (node instanceof Receive) {
            return 1;
        } else if (node instanceof Materiel) {
            return 2;
        }
        return -1;
    }
    public static final int EXPAND_COLLAPSE_PAYLOAD = 110;
}

public class ReceiveProvider extends BaseNodeProvider {
    @Override
    public int getItemViewType() {
        return 1;
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_receive_provider;
    }

    @Override
    public void convert(BaseViewHolder baseViewHolder,BaseNode baseNode) {
        Receive entity = (Receive) baseNode;
        baseViewHolder.setText(R.id.name,entity.getConllarUseId());
        baseViewHolder.setText(R.id.time,entity.getConllarUseDate());
  
        }

    }

    @Override
    public void convert(BaseViewHolder baseViewHolder,BaseNode baseNode,List<?> payloads) {
    }
    @Override
    public void onClick(BaseViewHolder helper, View view, BaseNode data, int position) {
        super.onClick(helper, view, data, position);
        Receive entity = (Receive) data;
        if (entity.isExpanded()) {
            getAdapter().collapse(position);
        } else {
//            getAdapter().expandAndCollapseOther(position);
            getAdapter().expandOrCollapse(position);
        }
    }
}

public class ReceiveOptionProvider extends BaseNodeProvider {
    @Override
    public int getItemViewType() {
        return 2;
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_receive_child_provider;
    }

    @Override
    public void convert(BaseViewHolder baseViewHolder, BaseNode baseNode) {
        Materiel materiel = (Materiel) baseNode;
        baseViewHolder.setText(R.id.name, materiel.getMaterielName());
        baseViewHolder.setText(R.id.xinhao, materiel.getMaterielModel());
        baseViewHolder.setText(R.id.num, materiel.getNumber());
    }
}

    //设置加载更多
        adapter.getLoadMoreModule().setEnableLoadMore(true);
        adapter.getLoadMoreModule().setOnLoadMoreListener(this);
        //默认第一次加载会进入回调，如果不需要可以配置
        adapter.getLoadMoreModule().setEnableLoadMoreIfNotFullPage(true);
        //当列表滑动到倒数第N个Item的时候(默认是1)回调onLoadMoreRequested方法
        adapter.getLoadMoreModule().setPreLoadNumber(1);
        adapter.setEmptyView(R.layout.empty_layout);
        smartRefresh.setOnRefreshListener(this);
        smartRefresh.setEnableLoadMore(false);

错误码：
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{533dac4 position=5 id=-1, oldPos=5, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{649eec7 VFE...... .F....I. 0,0-1080,1302 #7f080170 app:id/recyclerView}, adapter:com.yswl.intelligencewaterworks.adapter.ReceiveInfoAdapter@9257cf4, layout:androidx.recyclerview.widget.LinearLayoutManager@9c0bc1d, context:com.yswl.intelligencewaterworks.ui.maintain.MaintainInfoActivity@b663fc7
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:407)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Requiem4Eternity** [comment]
我也遇到了，使用的版本是3.0.4，错误日志：
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBaseViewHolder{1c1110ff position=2 id=-1, oldPos=2, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{2dedf652 VFED.... ......I. 0,245-540,1421 #7f080241 app:id/rv_gc_groupList}, adapter:com.eternity.appstream.adapter.RVAGCGroup@24cb0d23, layout:androidx.recyclerview.widget.LinearLayoutManager@14877220, context:com.eternity.appstream.HomeActivity@12e13ed3
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1843)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15671)
        at android.view.ViewGroup.layout(ViewGroup.java:5059)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)`

**Comment by Requiem4Eternity** [comment]
值得一提的是，如果在expandOrCollapse(position)之后，加上notifyDataSetChanged()，就不会崩溃了，
但也不会再有折叠动画，折叠事件大概率会错乱。

**Comment by szhdev** [comment]
我也遇到了上述问题

**Comment by li-yu** [comment]
解决方案供参考：https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/3065#issuecomment-1019767558
