### ISSUE TITLE
若使用MergeAdapter，添加headerview后出现异常

### ISSUE THREAD

**Issue by scatl** [CymChad/BaseRecyclerViewAdapterHelper#3127]
`RecyclerView recyclerView = findViewById(R.id.recyclerview);

        View headerView = LayoutInflater.from(this).inflate(R.layout.headerview, new LinearLayout(this));

        AdapterOne adapterOne = new AdapterOne(R.layout.item_adapter_one);

        AdapterMain adapterMain = new AdapterMain(R.layout.item_adapter_main);
        adapterMain.addHeaderView(headerView, 0);
        LinearLayoutManager linearLayoutManager1 = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(linearLayoutManager1);
        recyclerView.setAdapter(new MergeAdapter(adapterMain, adapterOne));

        List<String> main = new ArrayList<>();
        List<String> one = new ArrayList<>();
        for (int i = 0; i < 20; i ++) {
            main.add("main  " + i);
            one.add("one  " + i);
        }

        adapterOne.setNewData(one);
        adapterMain.setNewData(main);`

adapter：
`public class AdapterMain extends BaseQuickAdapter<String, BaseViewHolder> {
    public AdapterMain(int layoutResId) {
        super(layoutResId);
    }

    @Override
    protected void convert(@NonNull BaseViewHolder helper, String item) {
        helper.setText(R.id.item_adapter_main_textview, item+"");
        Log.e("main", item);
    }
}
`

exception:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.chad.library.adapter.base.BaseViewHolder.setText(BaseViewHolder.java:117)
        at com.scatl.mergeadapter.AdapterMain.convert(AdapterMain.java:22)
        at com.scatl.mergeadapter.AdapterMain.convert(AdapterMain.java:15)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:1019)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:1052)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:72)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
        at androidx.recyclerview.widget.NestedAdapterWrapper.onBindViewHolder(NestedAdapterWrapper.java:157)
        at androidx.recyclerview.widget.MergeAdapterController.onBindViewHolder(MergeAdapterController.java:368)
        at androidx.recyclerview.widget.MergeAdapter.onBindViewHolder(MergeAdapter.java:185)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3853)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4410)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
        at android.view.View.layout(View.java:22066)
        at android.view.ViewGroup.layout(ViewGroup.java:6320)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3166)
2020-04-13 11:46:26.828 2805-2805/com.scatl.mergeadapter E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2676)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1802)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7775)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
        at android.view.Choreographer.doCallbacks(Choreographer.java:865)
        at android.view.Choreographer.doFrame(Choreographer.java:800)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7550)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
`

**Comment by limuyang2** [comment]
请等待后续兼容
