### ISSUE TITLE
BaseMultiItemQuickAdapter ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by protectedMan** [CymChad/BaseRecyclerViewAdapterHelper#3134]
版本为brvah3.0.3 ，使用remoteAt(0)
此异常出现规律是这样的：
当列表有且仅有一条数据时，删除第一条，不会有问题。
当列表不止一条数据时，删除第一条，会出现下面的问题。
```
ava.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getDefItemViewType(BaseMultiItemQuickAdapter.kt:26)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.kt:333)
        at com.arjinmc.recyclerviewdecoration.RecyclerViewItemDecoration.drawHorizontal(RecyclerViewItemDecoration.java:341)
        at com.arjinmc.recyclerviewdecoration.RecyclerViewItemDecoration.onDraw(RecyclerViewItemDecoration.java:167)
        at androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4494)
```

**Comment by w1984908499** [comment]
请问解决了吗
