### ISSUE TITLE
v2.1.1 版本 addData(List<T> newData) 分页加载时列表没有刷新

### ISSUE THREAD

**Issue by muhezi** [CymChad/BaseRecyclerViewAdapterHelper#315]
第一页10条数据， 第二页只有一条数据， 在加载调用 addData 后， adapter 里的 mData 数据是 11 条， 页面还是停留在 footer loading ，没有刷新 UI，页面上的数据还是10条，滑动后才显示正确，这个地方应是 notifyItemRangeChanged() 的原因。

最后直接使用notifyDataSetChanged就可以了， 楼主看看这个问题会不会复现， 我的 recyclerview版本是 23.4.0；
```java
mQuickAdapter.getData().addAll(datas);
mQuickAdapter.dataAdded();
```

**Comment by CymChad** [comment]
恩，好的，我看一下。

**Comment by CymChad** [comment]
你用一下，mQuickAdapter.addData();看会不会有问题。

**Comment by CymChad** [comment]
我刚才在demo中测试了一下，没有出现这个问题，你可不可以在demo中复现一下，然后贴出demo代码，这能够让bug更快的被修复。

**Comment by muhezi** [comment]
您好， 我是参照 [PullToRefreshUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java) 写的， 调用addData 还是会有上面我描述的那种情况， 您帮看下是不是程序调用的问题。

代码如下：
```java
--> 从服务端读取数据
public void refresh() {

    // 切换至Loading页面
    if (mQuickAdapter.getData().isEmpty()) {
        multiState.showLoading();
    }

    bmobQuery.setLimit(PAGE_SIZE);
    bmobQuery.setSkip((nextPage - 1) * PAGE_SIZE);
    bmobQuery.findObjectsByTableObservable()
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new RxSubscribe<JSONArray>(mCxt) {
                @Override
                protected void _onNext(JSONArray jsonArray) {
                    loadPage(jsonArray);
                }

                @Override
                protected void _onError(String message) {
                    if (mQuickAdapter.getData().isEmpty()) {
                        multiState.showError();
                    } else {
                        mQuickAdapter.showLoadMoreFailedView();
                    }
                }

                @Override
                protected boolean showDialog() {
                    return false;
                }
            });
}

--> 显示解析、显示数据
private void loadPage(JSONArray jsonArray) {

    if (isRefresh) {
        isRefresh = false;
        mQuickAdapter.getData().clear();
        mQuickAdapter.openLoadMore(PAGE_SIZE);
        mQuickAdapter.removeAllFooterView();
        if (mSwipeRefreshLayout.isRefreshing()) {
            mSwipeRefreshLayout.setRefreshing(false);
        }
    }

    List<? extends BmobObject> datas = dataParser.parseJson(jsonArray.toString());
    if (datas != null && !datas.isEmpty()) {
        // mQuickAdapter.getData().addAll(datas);
        // mQuickAdapter.dataAdded();
        mQuickAdapter.addData(datas);
    }

    if (mQuickAdapter.getData().isEmpty()) {
        multiState.showEmpty();
    } else {
        multiState.showContent();
    }

    // nextPage
    nextPage = jsonArray.length() == 0 || jsonArray.length() < PAGE_SIZE ? 0 : nextPage + 1;

    if (nextPage == 0) {
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                mQuickAdapter.loadComplete();
                if (notLoadingView == null) {
                    notLoadingView = LayoutInflater.from(mCxt).inflate(R.layout.layout_footer_notloading,
                            (ViewGroup) mRecyclerView.getParent(), false);
                }
                mQuickAdapter.addFooterView(notLoadingView);
            }
        }, 500);
    }
}

--> SwipeRefreshLayout 下拉回调
@Override
public void onRefresh() {
    this.isRefresh = true;
    this.nextPage = 1;
    refresh();
}

--> 加载更多回调
@Override
public void onLoadMoreRequested() {
    if (nextPage == 0) {
        return;
    }
    mRecyclerView.post(new Runnable() {
        @Override
        public void run() {
            refresh();
        }
    });
}
```

**Comment by CymChad** [comment]
我看了下你的代码，没问题。
```
//mQuickAdapter.addData(DataServer.getSampleData(1));
和  
 // mQuickAdapter.getData().addAll(datas);
// mQuickAdapter.dataAdded();
```
意思一样的，除了notify不一样。但是我demo测试过了没复现bug。

**Comment by CymChad** [comment]
要不你录制一个gif看看？

**Comment by CymChad** [comment]
notifyItemRangeChanged 的第一个参数positionStart确实有问题，我改一下，等下发布一个版本你测试试一下，我这边测试不出来，因为我之前错误的参数还是正常显示了。麻烦你了。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.2'

**Comment by CymChad** [comment]
麻烦你测试出结果后告知我一下。

**Comment by muhezi** [comment]
v2.1.1版本
[异常情况](http://ocx0s9eur.bkt.clouddn.com/rvlm-error.mp4)
[正常情况](http://ocx0s9eur.bkt.clouddn.com/rvlm-normal.mp4)

**Comment by muhezi** [comment]
我刚更新了 2.1.2 版本， 加载更多那块没问题了， 但是再一次下拉刷新报异常了， 总数据 12 条， PAGESIZE = 10 。

错误日志：
```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 11(offset:11).state:13
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4659)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1472)
        at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
        at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:543)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5094)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
        at dalvik.system.NativeStart.main(Native Method)
```
辛苦啦， 先早点休息吧

**Comment by CymChad** [comment]
你是直接下拉刷新报错？还是下拉刷新后在第一次上拉的时候报错？

**Comment by muhezi** [comment]
上拉加载完成后 再下拉刷新的时候

**Comment by CymChad** [comment]
下拉刷新填充数据你用的还是addData？

**Comment by CymChad** [comment]
我的demo里面用的是 mQuickAdapter.setNewData();

**Comment by muhezi** [comment]
下拉刷新的填充数据我用的是addData 下午回去

**Comment by muhezi** [comment]
下午我在修改一下 然后给您反馈结果

**Comment by CymChad** [comment]
恩，好的，多谢，你可以判断如果是下拉的话直接setNewData，然后直接return出去，下面的流程没必要走了。

**Comment by muhezi** [comment]
现在我已经修改为 下拉刷新的时候调用 setNewData， 加载下一页数据 调用 addData， 正常情况下是没问题了,  还存在一种特殊情况， 就是同时进行 "下拉刷新" 和 "加载更多" 而产生冲突， 会出现一个BUG， 

日志如下：

```java
java.lang.IllegalStateException: 
    Added View has RecyclerView as parent but view is not a real child. Unfiltered index:5

    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6720)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6686)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6674)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1404)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
    at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1529)
    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2486)
    at android.view.View.dispatchTouchEvent(View.java:7731)
```
这个问题我的想法是， 让 BaseQuickAdapter 提供一个当前是否正在执行loading more 的方法，下拉的时候如果是在执行加载更多 就不执行下拉刷新，同一时间只允许用户使用一种动作。

**Comment by CymChad** [comment]
恩，可以的。

**Comment by CymChad** [comment]
其实如果你能获取到是否正在进行下拉刷新的状态，也可以做到，同一时间只允许用户使用一种动作。

**Comment by CymChad** [comment]
我在外面，晚上给你写个获取状态的方法。

**Comment by muhezi** [comment]
好的， 你说的那种方式如果传递下拉刷新状态给 BaseQuickAdapter， 可能需要修改footerview 的加载状态或者移除footerview，这两种方式都可以 你看看怎么处理简单就怎么来吧

**Comment by CymChad** [comment]
2.1.3 , 添加了一个 isLoading（）。你可以试试。

**Comment by LeaderChange** [comment]
原来我遇见的真的是BUG。。。。。

**Comment by LeaderChange** [comment]
啥时候能有个稳定的版本

**Comment by LeaderChange** [comment]
DEMO是最新的了吗

**Comment by CymChad** [comment]
@LeaderChange 是的最新的。有问题我们会尽快修复。这个版本已经相对稳定了，从2.0到现在已经迭代了13个版本了。

**Comment by LeaderChange** [comment]
希望文档上面方法的调用能够同步更新下，因为像我这样第一次使用的时候，如果文档是旧的方法，会挺麻烦了，谢谢啦

**Comment by muhezi** [comment]
更新到2.1.3版本后，同时下拉刷新和上拉加载的冲突已经解决了

**Comment by freefly2016** [comment]
点击事件setOnRecyclerViewItemClickListener 怎么都找不到了   2.1.3

**Comment by muhezi** [comment]
@freefly2016  addOnItemTouchListener()  [PullToRefreshUseActivity](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/blob/master/app/src/main/java/com/chad/baserecyclerviewadapterhelper/PullToRefreshUseActivity.java)  有示例

**Comment by freefly2016** [comment]
如果item 中还有动态添加的布局 可以使用这个吗

**Comment by freefly2016** [comment]
@muhezi  我现在用1.9.7 的可以用setonrec...    但是切换成2.1.3 的不可以 找不到方法

**Comment by muhezi** [comment]
@freefly2016   2.* 版本的都是通过 RecyclerView. addOnItemTouchListener() 来处理点击事件的， 你可以看看 [/base/listener](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/tree/master/library/src/main/java/com/chad/library/adapter/base/listener) 里面有没有

**Comment by CymChad** [comment]
@freefly2016 2.0版本更新已经把setOnRecyclerViewItemClickListener去除了，改成了 RecyclerView. addOnItemTouchListener @muhezi 👍

**Comment by freefly2016** [comment]
那设置网络图片 怎么设置呢？

**Comment by freefly2016** [comment]
1.9.7   中  在adapter 中设置网络图片呢 好像没有哎
