### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by Moster1h** [CymChad/BaseRecyclerViewAdapterHelper#3151]
1. 当前使用的版本号 
3.0.3
2. 复现操作描述 

建议getItem中对data做一下数据长度取值范围判断，不然会出现
java.lang.IndexOutOfBoundsException:，直接抛出异常非常不友好。

还有我建议你检查一下，对所有使用data的方法都进行判断

**Comment by limuyang2** [comment]
`getItemOrNull()` 就是带长度判断的

**Comment by hezhipengzipp** [comment]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItem(BaseQuickAdapter.kt:472)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:376)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)

**Comment by Jiang00** [comment]
@hezhipengzipp     /**
     * Don't override this method. If need, please override [getDefItemViewType]
     * 不要重写此方法，如果有需要，请重写[getDefItemViewType]
     *
     * @param position Int
     * @return Int
     */
    override fun getItemViewType(position: Int): Int {
