### ISSUE TITLE
BaseNodeAdapter替换最后一项IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ekibun** [CymChad/BaseRecyclerViewAdapterHelper#3153]
1. 当前使用的版本号
3.0.3
2. 复现操作描述
BaseNodeAdapter在setData时如果不存在NodeFooterImp，第169行会导致数组越界
```
val node = this.data[position]
```
3. crash日志
```
java.lang.IndexOutOfBoundsException: Index: 30, Size: 30
     at java.util.ArrayList.get(ArrayList.java:437)
     at com.chad.library.adapter.base.BaseNodeAdapter.removeNodesAt(BaseNodeAdapter.kt:169)
     at com.chad.library.adapter.base.BaseNodeAdapter.setData(BaseNodeAdapter.kt:119)
```

**Comment by huangxinbao** [comment]
描述：同上使用BaseNodeAdapter, 在只有一条数据的时候的时候，调用 remove方法发生奔溃;
版本号：3.0.2；
复现过程： 实际项目中发生奔溃；复现使用官方的demo，将树形的数据设置为一条；然后在 FirstProvider -》 中onClick() -  getAdapter().remove(data); 发生奔溃； 
奔溃日志： 
   --------- beginning of crash
2020-04-30 17:06:01.541 28177-28177/com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chad.baserecyclerviewadapterhelper, PID: 28177
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeNodesAt(BaseNodeAdapter.kt:169)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeAt(BaseNodeAdapter.kt:107)
        at com.chad.library.adapter.base.BaseQuickAdapter.remove(BaseQuickAdapter.kt:1243)
        at com.chad.library.adapter.base.BaseQuickAdapter.remove(BaseQuickAdapter.kt:1268)
        at com.chad.baserecyclerviewadapterhelper.adapter.node.tree.provider.FirstProvider.onClick(FirstProvider.java:81)
        at com.chad.baserecyclerviewadapterhelper.adapter.node.tree.provider.FirstProvider.onClick(FirstProvider.java:20)
        at com.chad.library.adapter.base.BaseProviderMultiAdapter$bindClick$1.onClick(BaseProviderMultiAdapter.kt:96)
        at android.view.View.performClick(View.java:6659)
        at android.view.View.performClickInternal(View.java:6631)
        at android.view.View.access$3100(View.java:790)
        at android.view.View$PerformClick.run(View.java:26187)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by MrHeping** [comment]
版本：3.0.4
描述： 同上使用BaseNodeAdapter,  父节点下删除最后一条数据（也就是删除最后一个子节点）时，会发生数组下标越界导致崩溃的错误。如果删除除最后一条数据其他的数据，就正常。错误日志如下：
`java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeNodesAt(BaseNodeAdapter.kt:169)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeAt(BaseNodeAdapter.kt:107)
        at com.chad.library.adapter.base.BaseQuickAdapter.remove(BaseQuickAdapter.kt:1287)
        at com.chad.library.adapter.base.BaseNodeAdapter.nodeRemoveData(BaseNodeAdapter.kt:301)
        at bell.ai.cloud.english.ui.activity.CacheInfoListActivity.onMessageEvent(CacheInfoListActivity.java:101)
        at java.lang.reflect.Method.invoke(Native Method)`

相关code：
`if (command.getData() != null) {
                //子节点
                CacheInfoItem cacheInfoItem = (CacheInfoItem) command.getData();
                //获取CacheInfoSectionItem，父节点
                CacheInfoSectionItem checkSectionItem = null;
                for (int i = 0; i < cacheInfoAdapter.getData().size(); i++) {
                    CacheInfoSectionItem cacheInfoSectionItem = (CacheInfoSectionItem) cacheInfoAdapter.getData().get(i);
                    if (cacheInfoSectionItem.getCatalogId() == cacheInfoItem.getLessonsBean().getCatalogId()) {
                        checkSectionItem = cacheInfoSectionItem;
                        break;
                    }
                }
                if (checkSectionItem != null) {
                    //报错的地方：nodeRemoveData函数方法内部removeAt报错，数组下标越界
                    cacheInfoAdapter.nodeRemoveData(checkSectionItem, cacheInfoItem);
                }
                return;
  }`

**Comment by 1226362423** [comment]
我也遇到了
