### ISSUE TITLE
3.0.2版本，RV弄无限循环滚动，每次都报空指针，getItem、getDefItemCount方法都重写了

### ISSUE THREAD

**Issue by CordyHo** [CymChad/BaseRecyclerViewAdapterHelper#3175]
代码：

    override fun convert(holder: BaseDataBindingHolder<RvItemDataBinding>, item: JsonBean.DataBean) {
        holder.dataBinding?.data = item
    }

    override fun getDefItemCount(): Int {
        return Int.MAX_VALUE
    }

    override fun getItem(position: Int): JsonBean.DataBean {
        return if (position >= data.size)
            data[position % data.size]
        else
            data[position]
    }

错误信息：
kotlin.KotlinNullPointerException
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:231)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)

这是我用原生Adaoter写法，可以正常运行：

`

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): MyVH {
        val binding = DataBindingUtil.inflate<RvItemDataBinding>(LayoutInflater.from(context), R.layout.rv_item_data, parent, false)
        return MyVH(binding.root, binding)
    }

    override fun getItemCount(): Int {
        return Int.MAX_VALUE
    }

    override fun onBindViewHolder(holder: MyVH, position: Int) {
        if (position >= data.size)
            holder.binding.data = data[position % data.size]
        else
            holder.binding.data = data[position]
    }

    class MyVH(itemView: View, val binding: RvItemDataBinding) : RecyclerView.ViewHolder(itemView)
`

**Comment by limuyang2** [comment]
能给个demo么？

**Comment by CordyHo** [comment]
> 能给个demo么？

链接: https://pan.baidu.com/s/1gpilUzlHbTI4aDRY-mindw  提取码: 4gte
有2个Adapter，一个原生写的，一个用BRVAH，你看看

**Comment by xichunjie** [comment]
我也是，getDefItemCount+1，就报空指针

**Comment by zhanhon** [comment]
你好，解决了吗

**Comment by soul7630** [comment]
你好，解决了吗？我也遇到同样的问题了

**Comment by CordyHo** [comment]
> 你好，解决了吗

没，最新版还是空指针

**Comment by CordyHo** [comment]
> 你好，解决了吗？我也遇到同样的问题了

没，最新版还是空指针

**Comment by LxzBUG** [comment]
解决了吗😂😂😂

**Comment by withyi9223** [comment]
我发现只要不重写getItem方法就不会有这个空指针的问题

**Comment by withyi9223** [comment]
需要重写getItemViewType方法呀
private val adapter by lazy {
        object : BaseQuickAdapter<Int, BaseViewHolder>(R.layout.item_layout) {
            override fun convert(helper: BaseViewHolder?, item: Int?) {
                helper?.itemView?.apply {
                    textView.text = "hello world$item"
                }
            }
 
            override fun getItemCount(): Int {
                return Int.MAX_VALUE
            }
 
            override fun getItem(position: Int): Int? {
                return data[position % data.size]
            }
 
            override fun getItemViewType(position: Int): Int {
                var count = headerLayoutCount + data.size
                if (count <= 0) {
                    count = 1
                }
                return super.getItemViewType(position % count)
            }
        }
    }

**Comment by CordyHo** [comment]
可以了，是什么原理啊？

**Comment by CordyHo** [comment]
可以了，是什么原理啊？

**Comment by weizhizhu** [comment]
解了吗

**Comment by panhs** [comment]
getItemViewType复写了还是崩溃， 用的3.0.6版本 java.lang.NullPointerException
                                                                                                    	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:247)
                                                                                                    	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:75)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330

**Comment by panhs** [comment]
> 需要重写getItemViewType方法呀
> 
> private val adapter by lazy { object : BaseQuickAdapter<Int, BaseViewHolder>(R.layout.item_layout) { override fun convert(helper: BaseViewHolder?, item: Int?) { helper?.itemView?.apply { textView.text = "hello world$item" } }
> 
> ```
>         override fun getItemCount(): Int {
>             return Int.MAX_VALUE
>         }
> 
>         override fun getItem(position: Int): Int? {
>             return data[position % data.size]
>         }
> 
>         override fun getItemViewType(position: Int): Int {
>             var count = headerLayoutCount + data.size
>             if (count <= 0) {
>                 count = 1
>             }
>             return super.getItemViewType(position % count)
>         }
>     }
> }
> ```

用的是哪个版本， 我用的3.0.6还是空指针异常

**Comment by panhs** [comment]
override fun getItemCount(): Int {
        return if(data.isEmpty()) 0 else Int.MAX_VALUE
    }
我加了这个，暂时解决了
