### ISSUE TITLE
getDefItemCount + 1 的问题

### ISSUE THREAD

**Issue by ouyuan2019** [CymChad/BaseRecyclerViewAdapterHelper#3210]
version:3.0.4
以前用2.9.40是可以的，现在升级到3.0.4就不行了

 kotlin.KotlinNullPointerException
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:245)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7201)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6332)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6216)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6212)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:560)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4215)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3615)
        at android.view.View.measure(View.java:24604)

**Comment by ouyuan2019** [comment]
需要重写getItemViewType 返回0 ，重写getDefItemViewType不管用，然后还要重写getItem，不然会数组越界。。。
<img width="864" alt="WX20200605-163634@2x" src="https://user-images.githubusercontent.com/24469937/83855499-bdaef600-a74a-11ea-8571-65927f2a94dd.png">

**Comment by Nextweekends** [comment]
> 需要重写getItemViewType 返回0 ，重写getDefItemViewType不管用，然后还要重写getItem，不然会数组越界。。。
> <img alt="WX20200605-163634@2x" width="864" src="https://user-images.githubusercontent.com/24469937/83855499-bdaef600-a74a-11ea-8571-65927f2a94dd.png">

你好，我按照你的方法重写，还是出现了数组越界的问题
  override fun getDefItemCount(): Int {
        return if (data.size > 9) 9 else data.size
    }

    override fun getDefItemViewType(position: Int): Int {
        return 0
    }

    override fun getItem(position: Int): Album {
        return getItemOrNull(position)!!
    }

**Comment by LonLove** [comment]
四个方法都需要重写才可以

**Comment by jayoss152** [comment]
最基础的东西都没做好，估计作者也是因为这样放弃维护了，弃坑了

**Comment by zhupengxiang** [comment]
@jayoss152 这个框架还行吧  挺方便的
