### ISSUE TITLE
无法使用自定义ViewHolder

### ISSUE THREAD

**Issue by long216** [CymChad/BaseRecyclerViewAdapterHelper#3276]
确定是继承的BaseViewHolder
使用之后报错 类型错误
怎么解决呢

**Comment by DaveBoy** [comment]
朋友你错误信息和代码都不放出来。。。。
还想让人解决问题。。。

**Comment by long216** [comment]
class MusicPublishAdapter extends BaseQuickAdapter<Music, MusicViewHolder> {
        public MusicPublishAdapter() {
            super(R.layout.item_music_publish);
        }
        @Override
        protected void convert(@NotNull MusicViewHolder baseViewHolder, Music music) {
            baseViewHolder.setText(R.id.tv_item_music_name, music.getName());
            baseViewHolder.setText(R.id.tv_item_music_time, TimeUtils.timestampToDate4((long) music.getDuration()));
        }
    }

    class MusicViewHolder extends BaseViewHolder{
        public MusicViewHolder(@NotNull View view) {
            super(view);
        }
    }
=========================================================================
报错信息:
    java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.woyihome.woyihomeapp.ui.publish.MusicPublishActivity$MusicViewHolder
        at com.woyihome.woyihomeapp.ui.publish.MusicPublishActivity$MusicPublishAdapter.convert(MusicPublishActivity.java:188)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:376)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3853)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4410)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
        at android.view.View.layout(View.java:22113)
        at android.view.ViewGroup.layout(ViewGroup.java:6387)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3286)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2782)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1865)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8029)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
2020-07-24 10:32:50.418 8723-8723/com.woyihome.woyihomeapp E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:793)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7509)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by DaveBoy** [comment]
断点一下 BaseQuickAdapter  onCreateViewHolder这个方法
