### ISSUE TITLE
移除树结构最后一个节点会越界

### ISSUE THREAD

**Issue by xmt328** [CymChad/BaseRecyclerViewAdapterHelper#3323]
**Describe the bug**
在BaseNodeAdapter#removeNodesAt中如果position是最后一个元素，再移除自己之后再调用this.data[position]会越界
```java
    private fun removeNodesAt(position: Int): Int {
        if (position >= data.size) {
            return 0
        }
        // 记录被移除的item数量
        var removeCount = 0

        // 先移除子项
        removeCount = removeChildAt(position)

        // 移除node自己
        this.data.removeAt(position)
        removeCount += 1

        val node = this.data[position]
        // 移除脚部
        if (node is NodeFooterImp && node.footerNode != null) {
            this.data.removeAt(position)
            removeCount += 1
        }
        return removeCount
    }
```

```
    java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeNodesAt(BaseNodeAdapter.kt:169)
        at com.chad.library.adapter.base.BaseNodeAdapter.removeAt(BaseNodeAdapter.kt:107)
```

**Comment by Vicent9920** [comment]
我也遇到了，自己解决越界错误，但是页面还是有问题

**Comment by xiaoxiezi** [comment]
把源文件copy下来，加个footerLayoutCount>0判断，页面效果就不会出问题了。
剩下就等作者更新了

**Comment by com13117340768** [comment]
> 把源文件copy下来，加个footerLayoutCount>0判断，页面效果就不会出问题了。
> 剩下就等作者更新了

谢谢，我试试下

**Comment by 1226362423** [comment]
+1

**Comment by Qdafengzi** [comment]
改源码 
if (this.data.size>position){
            val node = this.data[position]
            // 移除脚部   bug   ---->
            if (node is NodeFooterImp && node.footerNode != null) {
                this.data.removeAt(position)
                removeCount += 1
            }
        }

**Comment by jqorz** [comment]
fork一下，修改为val node = this.data.getOrNull(position)即可

**Comment by 1226362423** [comment]
注释掉脚部代码
