### ISSUE TITLE
GridLayoutManager addHeader  crash

### ISSUE THREAD

**Issue by liompei** [CymChad/BaseRecyclerViewAdapterHelper#3329]
当我使用一个GridLayoutManager的recyclerView时，在获取到数据去setList时同时进行addHeaderView，项目就会崩溃，一个越界的报错

2020-09-18 12:10:32.413 24185-24185/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 24185
    java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
        at java.util.ArrayList.get(ArrayList.java:437)
        at AdapterHelper$createSearchResultSpanSizeLookup$1.getSpanSize(AdapterHelper.kt:56)
        at com.chad.library.adapter.base.BaseQuickAdapter$onAttachedToRecyclerView$1.getSpanSize(BaseQuickAdapter.kt:442)
        at androidx.recyclerview.widget.GridLayoutManager.getSpanSize(GridLayoutManager.java:493)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:551)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)

**Comment by liompei** [comment]
我通过一下方式让问题得到暂时解决

**Comment by liompei** [comment]
getSpanSize内 adapter.data[position - adapter.headerLayoutCount]
