### ISSUE TITLE
addData使用问题

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#333]
现在我的RecyclerView里面添加了一个Head  然后我在我获取数据的回调方法里addData，报如下错误
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{7a49b06 position=0 id=-1, oldPos=-1, pLpos:-1}
                                                                         at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:654)
                                                                         at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
                                                                         at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1107)
                                                                         at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3270)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3088)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                         at android.view.View.layout(View.java:16653)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

但是我调用dataAdded就没有问题，初步定位是BaseQuickAdapter中addData方法的notifyItemRangeChanged方法有问题，问下楼主是我使用有问题么？

**Comment by CymChad** [comment]
贴下你使用的代码

**Comment by CymChad** [comment]
你的版本号是？

**Comment by yuruxuan** [comment]
@CymChad 

代码如下

 private void getPageOneComment() {
        mAdapter.openLoadMore(PAGE_SIZE);
        mHelper.getCommentList(item, 1, new CommentHelper.GetCommentListListener() {
            @Override
            public void onSuccess(final List<Comment> list) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        mCommentList.clear();
//                        mCommentList.addAll(list);
                        mAdapter.addData(list);
//                        mAdapter.dataAdded();
//                        mAdapter.removeAllFooterView();
                        layout_swipe_refresh.setRefreshing(false);
                        page = 2;
                    }
                });
            }

            @Override
            public void onFailure(String msg) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        mAdapter.showLoadMoreFailedView();
                        layout_swipe_refresh.setRefreshing(false);
                    }
                });
            }
        });
    }

版本号
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.1.3'

**Comment by yuruxuan** [comment]
格式有点凌乱   对不起啊

**Comment by CymChad** [comment]
第一次加载数据用，setNewData。

**Comment by yuruxuan** [comment]
@CymChad 那addData是在什么情形使用呢？每次上拉刷新  我是不是需要都dataAdded才可以？

**Comment by CymChad** [comment]
加载更多的时候使用。你可以使用addData或者你自己用list.add后dataAdded，两种方式选一种就可以了。

**Comment by yuruxuan** [comment]
@CymChad 我懂了    当Head和empty  不能notifyItemRangeChanged  数据和视图对不上   所以一定要notifydatasetchanged

谢谢大牛
