### ISSUE TITLE
通过继承的方式传递布局报java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by abcdlulu123** [CymChad/BaseRecyclerViewAdapterHelper#3366]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/13221321/98906143-8f062a00-24f7-11eb-990d-4d3715a38947.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/13221321/98906153-94637480-24f7-11eb-939d-49d64a062cac.png">
使用这种继承的方式 传值  报
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:694)
        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:546)

请问 有没有人解决过这个问题

**Comment by ZhangHao555** [comment]
android 11上会出现 我也遇到了
