### ISSUE TITLE
BaseViewHolder cannot be cast to BaseDataBindingHolder的问题

### ISSUE THREAD

**Issue by Cedar-byte** [CymChad/BaseRecyclerViewAdapterHelper#3402]
1. 当前使用的版本号：3.0.4
2. 操作描述，自定义adapter并继承BaseQuickAdapter，其中传入的是BaseDataBindingHolder
3. 使用代码：
`public class VideoHomeListAdapter extends BaseQuickAdapter<VideoHomeListBean, BaseDataBindingHolder'<'ItemVideoListBinding'>'> {...}`
4. crash日志：
`java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
        at com.module.module_video.VideoHomeListFragment$bind$1.convert(VideoHomeListFragment.kt:67)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:376)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)`

5. 出现以上错误时，按照其他issue里说的添加混淆后也还是报相同的错误，没有任何效果。但是，如果我为这个adapter传入空的集合时，就不报上面的错了。代码如下：
list = ArrayList()
        adapter = VideoHomeListAdapter(list)
        recyclerview.adapter = adapter

**Comment by cainanqi** [comment]
有解决办法了吗?我也是这个问题

**Comment by nauhalf** [comment]
@Cedar-byte 
why you close the issue ? I've same the problem but I don't know how to solve it

**Comment by 1244752609** [comment]
R.layout.xx资源文件跟BaseDataBindingHolder<VB>里面的VB泛型没对上
