### ISSUE TITLE
父reyclerview嵌套子recyclerview，滑动子rv时候报 ConcurrentModificationException异常

### ISSUE THREAD

**Issue by androidfreshman** [CymChad/BaseRecyclerViewAdapterHelper#3418]
这个是包错信息：
java.util.ConcurrentModificationException
        at java.util.ArrayList$SubList.size(ArrayList.java:1057)
        at com.chad.library.adapter.base.BaseQuickAdapter.getItemCount(BaseQuickAdapter.java:698)
        at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:90)
        at android.support.v7.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:323)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:349)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
我用父recyclerview包含了子recyclerview，然后子recyclerview可以加载更多所以我在父recyclerview的adapter里面执行了接口请求来更新子recyclerview，但是滑动的时候会报这个ConcurrentModificationException错误

**Comment by chapliny** [comment]
这个一般不能这么做，后来是改成 外面请求好数据在 赋值进来了吧
