### ISSUE TITLE
添加混淆报错

### ISSUE THREAD

**Issue by MengYaoSai** [CymChad/BaseRecyclerViewAdapterHelper#3447]
2021-03-09 15:04:54.886 11469-11469/com.example.demo E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.ClassCastException: com.chad.library.adapter.base.viewholder.BaseViewHolder cannot be cast to com.chad.library.adapter.base.viewholder.BaseDataBindingHolder
        at com.example.demo.ui.home.adapter.QuestionnaireAddVoteAdapter.convert(QuestionnaireAddVoteAdapter.kt:21)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:376)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:24730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24730)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:792)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:480)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:134)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:277)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:119)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1578)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1690)
        at android.view.View.measure(View.java:24730)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1599)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:585)
        at android.view.View.measure(View.java:24730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24730)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:24730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:24730)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6858)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)

**Comment by viosonlee** [comment]
我也这样

**Comment by YorkBo** [comment]
添加下面混淆配置可以解决

-keep class cc.yorkbo.ui.recyclerview.adapter.BaseAdapter {*;}
-keep public class * extends cc.yorkbo.ui.recyclerview.adapter.viewholder.BaseViewHolder
-keepclassmembers  class *$* extends cc.yorkbo.ui.recyclerview.adapter.viewholder.BaseViewHolder {
   *;
}

**Comment by Dajkwen** [comment]
断点之后会发现是在构造 BaseDataBindingHolder 的时候，由于混淆，使得构造失败，报 java.lang.NoSuchMethodException: BaseDataBindingHolder.<init>[class android.view.View] 这个错误，

所以混淆的时候可以这样，
-keepclassmembers class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
    public void *(android.view.View);
}
或者如果使用 BaseDataBindingHolder 的子类的话，可以这样，
-keepclassmembers class * extends com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
    public void *(android.view.View);
}
安全起见，可以两段都加上。
亲测有效

**Comment by KAICW** [comment]
无效，没用，还是会报错

**Comment by hyhyhykw** [comment]
> 断点之后会发现是在构造 BaseDataBindingHolder 的时候，由于混淆，使得构造失败，报 java.lang.NoSuchMethodException: BaseDataBindingHolder.[class android.view.View] 这个错误，
> 
> 所以混淆的时候可以这样，
> -keepclassmembers class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
> public void *(android.view.View);
> }
> 或者如果使用 BaseDataBindingHolder 的子类的话，可以这样，
> -keepclassmembers class * extends com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
> public void *(android.view.View);
> }
> 安全起见，可以两段都加上。
> 亲测有效

-keepclassmembers class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
public <init>(android.view.View);
}
其中的<init>代表的就是构造方法

**Comment by hyhyhykw** [comment]
> 断点之后会发现是在构造 BaseDataBindingHolder 的时候，由于混淆，使得构造失败，报 java.lang.NoSuchMethodException: BaseDataBindingHolder.[class android.view.View] 这个错误，
> 
> 所以混淆的时候可以这样，
> -keepclassmembers class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
> public void *(android.view.View);
> }
> 或者如果使用 BaseDataBindingHolder 的子类的话，可以这样，
> -keepclassmembers class * extends com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
> public void *(android.view.View);
> }
> 安全起见，可以两段都加上。
> 亲测有效

```
-keepclassmembers class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {
public <init>(android.view.View);
}

其中的<init>代表的就是构造方法
```

**Comment by Hiboboo** [comment]
我自己额外做了一段修补代码，混淆文件中不需要修改任何内容。
第一步，自己写一个新的类：
```kotlin
abstract class AbsBindingAdapter<T, BD : ViewDataBinding>(@LayoutRes layoutResId: Int) : BaseQuickAdapter<T, BaseViewHolder>(layoutResId) {

    override fun convert(holder: BaseViewHolder, item: T) {
        DataBindingUtil.bind<BD>(holder.itemView)?.let { this.onBindingConvert(it, item) }
    }

    abstract fun onBindingConvert(binding: BD, item: T)
}
```
第二步，用你实际的`Adapter`去继承刚才写的`AbsBindingAdapter`类
```kotlin
class ImageAdapter : AbsBindingAdapter<String, FragmentGlobalFullImageItemBinding>(R.layout.fragment_global_full_image_item) {

        override fun onBindingConvert(binding: FragmentGlobalFullImageItemBinding, item: String) {
            binding.image.load(item)
        }
    }
```

这样就可以了。
