### ISSUE TITLE
3.0.2版本 会出现这个问题     请求接口 加载数据 加载完后 会出现    调用：  mAdapter?.removeAllHeaderView()                                 addHeadView()

### ISSUE THREAD

**Issue by binbinyYang** [CymChad/BaseRecyclerViewAdapterHelper#3474]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{2b96bb5 position=0 id=-1, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{ac2324a VFED..... .F....ID 0,0-1080,1491 #7f09081e app:id/rv}, adapter:com.addcn.android.rent.house.RentHouseListAdapter@f3e25bb, layout:androidx.recyclerview.widget.LinearLayoutManager@6973ad8, context:com.addcn.android.rent.housenew.house.NewRentHouseActivity@bd76552
        at androidx.recyclerview.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
        at androidx.recyclerview.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
        at androidx.recyclerview.widget.RecyclerView.addAnimatingView(RecyclerView.java:1431)
        at androidx.recyclerview.widget.RecyclerView.animateDisappearance(RecyclerView.java:4161)
        at androidx.recyclerview.widget.RecyclerView$4.processDisappeared(RecyclerView.java:612)
        at androidx.recyclerview.widget.ViewInfoStore.process(ViewInfoStore.java:240)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3994)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5602)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5602)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:645)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5602)

**Comment by weskmoon** [comment]
请问这个问题解决了吗？我也出现这样的问题

**Comment by binbinyYang** [comment]
没

**Comment by andyhaha** [comment]
我也遇到了这个崩溃，不过我的是调用了removeAllFooterView之后又调用了addFooterView方法，结合使用了loadMoreComplete()方法

**Comment by andyhaha** [comment]
这个问题解决了吗，先调用removeAllHeaderView，再调用adapter.addHeaderView()方法就会出现。因为需要频繁remove和addHeader，首次调用没问题，第二次再这样使用出现这个必现的bug

**Comment by binbinyYang** [comment]
没 一直存在
