### ISSUE TITLE
上拉 会出现崩溃：Added View has RecyclerView as parent but view is not a real child

### ISSUE THREAD

**Issue by lianghuiyong** [CymChad/BaseRecyclerViewAdapterHelper#354]
出现的情况是，一进入页面，我就快速上拉，很快的那种，就一般会出现这种崩溃问题，感觉是数据添加到列表时候出现的问题。

```java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7109)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7073)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7061)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1428)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4413)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:588)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:557)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5276)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) ```


再次封装：
`public abstract class BaseRecyclerAdapter<T> extends BaseQuickAdapter<T> {

    public BaseRecyclerAdapter(int layoutResId, List<T> data) {
        super(layoutResId, data);
        setBaseView();
    }

    private void setBaseView(){
        //配置上拉加载更多时的过度页面,上拉时自动显示
        setLoadingView(LayoutInflater
                .from(AppConfig.getInstance())
                .inflate(R.layout.recycler_item_updata, null));

        //设置列表为空时的页面
        setEmptyView(LayoutInflater
                .from(AppConfig.getInstance())
                .inflate(R.layout.recycler_item_err, null));

        //配置上拉失败页面，显示时需调用 showLoadMoreFailedView()
        //点击失败页面会自动再次调用上拉加载
        setLoadMoreFailedView(LayoutInflater
                .from(AppConfig.getInstance())
                .inflate(R.layout.recycler_item_loadmorefailed, null));
    }

    //显示底部
    public void showFooter(){
        addFooterView(getFooterView());
    }

    //取消底部显示
    public void dismissFooter(){
        removeAllFooterView();
    }

    private View getFooterView(){
        return LayoutInflater
                .from(AppConfig.getInstance())
                .inflate(R.layout.recycler_item_footer, null);
    }

    //清空列表
    public void removeAll() {
        this.mData.clear();
        this.notifyDataSetChanged();
        this.dismissFooter();
    }
`

代码实现

```
@Override
    public void init() {
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
        myDoThingListAdapter = new WDBJListAdapter(R.layout.item_bj, null);
        recyclerView.setAdapter(myDoThingListAdapter);
        myDoThingListAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
        
        @Override
        public void onLoadMoreRequested() {
                PAGENO++;
                loadPage();
            }
        });
        
     loadPage();
    }

   loadPage(){

      //线程接收数据成功时
       myDoThingListAdapter.addData(temp);
       if (temp.size() < 5) {
       myDoThingListAdapter.loadComplete();
       myDoThingListAdapter.showFooter();
       } 
   }

**Comment by CymChad** [comment]
收到，正在跟进中。

**Comment by lianghuiyong** [comment]
我重写 addDate就没出现问题了

`@Override
    public void addData(List<T> newData) {
        if (newData != null) {
            this.mData.addAll(newData);
            dataAdded();
            notifyItemRangeInserted(this.mData.size(), newData.size());
        }
    }
`

**Comment by woniu0936** [comment]
@lianghuiyong 我也遇到了你的问题，按照你的方法试了试，会出现当下一页数据加载完成时，页面中item中的图片会闪烁一下的问题，你有遇到吗

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.2' 已修复

**Comment by mflk007** [comment]
分组折叠的时候偶然还是出现了 java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:2

 compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.18'

**Comment by qinxianyuzou** [comment]
用GridLayoutManager的时候也遇到了这个问题，起因应该是我添加了footerview，并且对footerview按条件显示隐藏，然后快速上拉就崩溃了，不知道怎么解决。@CymChad
