### ISSUE TITLE
实现BaseItemBinder  binder 无法获取当前adapter 对象，麻烦解决下

### ISSUE THREAD

**Issue by bimromatic** [CymChad/BaseRecyclerViewAdapterHelper#3548]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by ponthamaya** [comment]
Onclick function broken in v3.0.7

2021-11-15 09:47:09.843 2968-2968/com.ee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ee, PID: 2968
    java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/com.ee-UrNkn7MiKCFLAi695fwFEg==/base.apk)
        at com.chad.library.adapter.base.BaseProviderMultiAdapter.bindClick$lambda-2(BaseProviderMultiAdapter.kt:97)
        at com.chad.library.adapter.base.BaseProviderMultiAdapter.$r8$lambda$-CN5DVz23Tx0qfAN7oGoKeASNaE(Unknown Source:0)
        at com.chad.library.adapter.base.BaseProviderMultiAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by xingqun** [comment]
Try using the latest version of recyclerview.
eg: 
`implementation 'androidx.recyclerview:recyclerview:1.2.1'`

**Comment by huangShan-gitHub** [comment]
楼上方法有效，感谢~

**Comment by lyl21** [comment]
有效，thanks
