### ISSUE TITLE
Non-fatal Exception: java.lang.ClassCastException: RecommendBean cannot be cast to PdWaitingBean

### ISSUE THREAD

**Issue by xiexinli** [CymChad/BaseRecyclerViewAdapterHelper#3559]
Non-fatal Exception: java.lang.ClassCastException: com.xxl.buyermob.ui.product.recom.RecommendBean cannot be cast to com.xxl.buyermob.ui.product.recom.PdWaitingBean
       at com.xxl.buyermob.ui.product.recom.PdWaitingBinder.convert(PdWaitingBinder.kt:15)
       at com.chad.library.adapter.base.BaseBinderAdapter.convert(BaseBinderAdapter.kt:70)
       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:378)
       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:384)
       at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:691)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at androidx.core.widget.NestedScrollView.onLayout(NestedScrollView.java:1854)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3709)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3161)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at com.xxl.buyermob.ui.debug.Cockroach.safeMode(Cockroach.java:186)
       at com.xxl.buyermob.ui.debug.Cockroach.lambda$install$0(Cockroach.java:45)
       at com.xxl.buyermob.ui.debug.-$$Lambda$Cockroach$KjKEpE4TPIan2he2gxLWI7gBxMI.uncaughtException()
       at com.facebook.internal.instrument.crashreport.CrashHandler.uncaughtException(CrashHandler.kt:42)
       at org.chromium.base.JavaExceptionReporter.uncaughtException(:16)
       at cn.tongdun.android.bugly.xxo0o0ox0oxxoo.uncaughtException(:12)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)

发生的概率比较低，60%为小米手机

**Comment by xiexinli** [comment]
原因：同一个BaseBinderAdapter()对象，两个以上的binder重复添加（第一张图片），会导致第二第三种图片所展示的结果，然后在数据绑定的时候，根据itemType就会拿到错误的viewhodler，convert中，根据布局转化bean类，就会发生强转错误。
![image](https://user-images.githubusercontent.com/14163229/143537024-54504ae5-b4f3-41fb-95a7-5641002e577e.png)

![UunwyTxy4f](https://user-images.githubusercontent.com/14163229/143536708-fc5e4f4d-b368-4a95-876a-e50719962374.png)
![W7xMgrXNQM](https://user-images.githubusercontent.com/14163229/143536722-34b91c53-842e-4587-890d-9f95c43ac331.png)

修改方式：保证添加的binder不重复。或者重置BaseBinderAdapter()对象，然后再添加binder。

**Comment by AndyYw** [comment]
多谢大佬
