### ISSUE TITLE
ExpandableItem Activity点击最后一项出现异常

### ISSUE THREAD

**Issue by newstargithub** [CymChad/BaseRecyclerViewAdapterHelper#356]
java.lang.IndexOutOfBoundsException: Invalid index 27, size is 27
                                                                                          at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                          at java.util.ArrayList.get(ArrayList.java:308)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.getItem(BaseQuickAdapter.java:281)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.expandAll(BaseQuickAdapter.java:1046)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.expandAll(BaseQuickAdapter.java:1084)
                                                                                          at com.chad.baserecyclerviewadapterhelper.adapter.ExpandableItemAdapter$1.onClick(ExpandableItemAdapter.java:56)

**Comment by candebbs** [comment]
有可能是你自己数据源的问题，检查下

**Comment by CymChad** [comment]
@newstargithub 你的版本号是？

**Comment by CymChad** [comment]
更新到最新的版本应该就没问题了，这是之前的一个bug。

**Comment by newstargithub** [comment]
版本号是1.2

**Comment by CymChad** [comment]
那你升级一下就好了，最新的版本为  2.1.6
