### ISSUE TITLE
LoadMore模块使用直接崩掉了demo点击也崩掉了

### ISSUE THREAD

**Issue by xuxinjiang** [CymChad/BaseRecyclerViewAdapterHelper#3571]
2021-12-23 11:17:55.382 21201-21201/com.test.commentdialog E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.commentdialog, PID: 21201
    java.lang.IllegalStateException: Please first implements LoadMoreModule
        at com.chad.library.adapter.base.BaseQuickAdapter.getLoadMoreModule(BaseQuickAdapter.kt:104)
        at com.test.commentdialog.CommendMsgDialogFragment2.initView(CommendMsgDialogFragment2.java:115)
        at com.test.commentdialog.CommendMsgDialogFragment2.onViewCreated(CommendMsgDialogFragment2.java:104)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)

**Comment by getglory** [comment]
不是写了吗，Adapter需要实现LoadMoreModule。但是demo也没实现。。

**Comment by HuiZaierr** [comment]
> 
实现了还是崩啊

**Comment by lnkkk** [comment]
@NotNull
    @Override
    public BaseLoadMoreModule addLoadMoreModule(@NotNull BaseQuickAdapter<?, ?> baseQuickAdapter) {
        return new BaseLoadMoreModule(baseQuickAdapter);
    }

先构建一个baseLoadMoreModule
