### ISSUE TITLE
点击事件失效问题3.0.7无法解决

### ISSUE THREAD

**Issue by JohnDwang** [CymChad/BaseRecyclerViewAdapterHelper#3574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

1. 尝试在[历史问题](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues?q=is%3Aissue+is%3Aclosed)搜索答案。
2. 尝试阅读[文档](http://www.jianshu.com/p/b343fcff51b0)找到答案。
3. 尝试阅读[Demo](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)找到答案。
4. 尝试自己检查或试验以找到答案。
5. 尝试阅读源代码以找到答案。
6. 请勿将产品的一些特殊交互需求 和 该库暂不支持作为bug混为一谈，请您仔细甄别

如果以上都尝试过了请提一个新的[issues](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/new)   
参考[提問的智慧](https://github.com/FredWe/How-To-Ask-Questions-The-Smart-Way)

如果还是没有找到答案，提问请带上这几个必要信息
1. 当前使用的版本号
2. 复现操作描述
3. 使用代码
3. crash日志
4. gif复现效果
5. 抽取demo
       **将你出现的问题代码抽出来成一个可直接运行的项目。（最好fork[本库](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)修改）**
       **在本地修改demo，然后把commit push到github上，在issue里贴下demo的地址。**

**有详细的描述才能使得我们更快速的定位问题并解决问题，感谢配合！**

**Comment by yangdepengyang** [comment]
Process: com.simon.tools, PID: 26041
    java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/data/com.simon.tools/code_cache/.overlay/base.apk/classes.dex)
        at com.chad.library.adapter.base.BaseQuickAdapter.bindViewClickListener$lambda-7$lambda-6(BaseQuickAdapter.kt:495)
        at com.chad.library.adapter.base.BaseQuickAdapter.$r8$lambda$aqWf9Mix2Hshed6QsGcdRVGlHL8(Unknown Source:0)
        at com.chad.library.adapter.base.BaseQuickAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7750)
        at android.view.View.performClickInternal(View.java:7727)
        at android.view.View.access$3700(View.java:861)
        at android.view.View$PerformClick.run(View.java:29133)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by yangdepengyang** [comment]
环境：Androidx

**Comment by yangdepengyang** [comment]
语言：java
环境：Androidx
gradle:7.1.2
是无法获取到指定的对象

**Comment by android-taoge** [comment]
同样遇到这个问题
