### ISSUE TITLE
setDiffNewData异步diff数据时，可能导致IndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhujunhua2012** [CymChad/BaseRecyclerViewAdapterHelper#3584]
局部刷新时， 使用`#setDiffNewData`异步diff数据，此时在RecyclerView中下拉刷新（在BrvahAsyncDiffer进行异步diff的同时），会加载更早的数据，直接使用 `getData().addAll(0, earlierDataList)`，可能导致IndexOutOfBoundsException。

```
2022-01-07 13:44:14.986, E/WTag-CrashHandler, java.lang.IndexOutOfBoundsException: Index: 4, Size: 40
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.chad.library.adapter.base.diff.BrvahAsyncDiffer$submitList$1$result$1.areItemsTheSame(BrvahAsyncDiffer.kt:138)
	at androidx.recyclerview.widget.DiffUtil.forward(DiffUtil.java:239)
	at androidx.recyclerview.widget.DiffUtil.midPoint(DiffUtil.java:198)
	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:146)
	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:106)
	at com.chad.library.adapter.base.diff.BrvahAsyncDiffer$submitList$1.run(BrvahAsyncDiffer.kt:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

`getData().addAll(0, earlierDataList)`这个操作对数据源进行了更改，使得`BrvahAsyncDiffer#submitList`中的`val oldList: List<T> = adapter.data` 这个`oldList`数据发生了变化。
但是目前的场景，就是需要在已有数据之前添加`earlierDataList`，有其他方法吗？（不想整个替换数据源）

**Comment by zhujunhua2012** [comment]
@limuyang2 @CymChad

**Comment by SaltedFish-Extreme** [comment]
> @limuyang2 @CymChad

作者应该已经不维护了😂

**Comment by ZhangBingbin** [comment]
同样遇到这样的问题，请问下您解决了没有

**Comment by ZhangBingbin** [comment]
> `#setDiffNewData`这个使用异步diff `BrvahAsyncDiffer#submitList`，应该是参考的官方的`AsyncListDiffer#submitList`。 但是官方的`AsyncListDiffer#submitList`，其中使用的是 unmodifiable list `mReadOnlyList`（`AsyncListDiffer#getCurrentList`返回的数据源也是这个，外部是不能修改的）。
> 
> 但是BRVAH目前的使用中，`AsyncListDiffer#submitList`使用的是`val oldList: List<T> = adapter.data`，但是这个`adapter.data`在外部是可以对数据list进行`add/remove`之类的操作的。
> 
> 这样就导致了当前issue的问题，在后台线程进行diff的过程中，其他地方主线程对`adapter.data`数据源进行`add/remove`操作之后，后台线程处理中的`BrvahAsyncDiffer#submitList`中的`val oldList: List<T> = adapter.data`就被修改了，导致`getOldListSize`是原先的数据总数，但是`oldList#get(index)`时是其他地方主线程更新后的数据list，list的数据已经变了，就有可能导致IndexOutOfBoundsException或者其他问题了。

**Comment by ZhangBingbin** [comment]
同样遇到这样的问题，请问下您解决了没有

**Comment by 2318423730** [comment]
这个问题该怎么解决？

**Comment by dendrocyte** [comment]
用這隻就能做同步了
setDiffNewData(@NonNull diffResult: DiffUtil.DiffResult, list: MutableList<T>)
