### ISSUE TITLE
java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:3

### ISSUE THREAD

**Issue by woniu0936** [CymChad/BaseRecyclerViewAdapterHelper#360]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.gouhuoapp.say, PID: 27710
                                                                   java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:3
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6720)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6686)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6674)
                                                                       at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1559)
                                                                       at android.support.v7.widget.StaggeredGridLayoutManager.scrollBy(StaggeredGridLayoutManager.java:2060)
                                                                       at android.support.v7.widget.StaggeredGridLayoutManager.scrollVerticallyBy(StaggeredGridLayoutManager.java:1980)
                                                                       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4061)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:571)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:192)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5784)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)

**Comment by woniu0936** [comment]
上滑加载下一页的时候，如果滑动的太快，就会报这个错，页面就是一个activity现实一个三列的StaggeredGridLayoutManager，adapter是正常的赋值，加载下一页数据是这样写的：if (1 == pageNo) {
                            mAdapter.setNewData(list);
                        } else {
                            mAdapter.addData(list);
                        }

**Comment by CymChad** [comment]
你可以参考一下 #354

**Comment by woniu0936** [comment]
@CymChad 按照#354方案，加载下一页数据完成瞬间，item里面图片会有闪烁问题

**Comment by CymChad** [comment]
图片加载问题，应该是图片的加载框架问题吧？

**Comment by woniu0936** [comment]
@CymChad 没按照#354的方案解决的时候，一切正常，这个issue里面提到的bug能不能再库里面解决一下？

**Comment by CymChad** [comment]
354的解决方案，是因为，它通知了全部的item，目前的代码只是通知了，更新这一部分的item。

**Comment by CymChad** [comment]
我这边会跟进一下这个问题的。

**Comment by woniu0936** [comment]
@CymChad 辛苦了
