### ISSUE TITLE
打开你的项目编译的点击任何一个示例都报错

### ISSUE THREAD

**Issue by super963883929** [CymChad/BaseRecyclerViewAdapterHelper#3610]
Process: com.chad.baserecyclerviewadapterhelper, PID: 16938
    java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/~~P2UZzNhpW-FAgKLtRozK3g==/com.chad.baserecyclerviewadapterhelper-TWoqU1l2BU0wjSPLYFF0-w==/base.apk)
        at com.chad.library.adapter.base.BaseQuickAdapter.bindViewClickListener$lambda-7$lambda-6(BaseQuickAdapter.kt:495)
        at com.chad.library.adapter.base.BaseQuickAdapter.lambda$aqWf9Mix2Hshed6QsGcdRVGlHL8(Unknown Source:0)
        at com.chad.library.adapter.base.-$$Lambda$BaseQuickAdapter$aqWf9Mix2Hshed6QsGcdRVGlHL8.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7509)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28720)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8060)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by liangjingkanji** [comment]
也许可以看看还在维护的: [BRV](https://github.com/liangjingkanji/BRV/)

**Comment by jobscolin** [comment]
人麻了....估计得自己改改

**Comment by qazxcs113** [comment]
把Recyclerview的版本都升级一下 有一个是1.1.0 
    compileOnly 'androidx.recyclerview:recyclerview:1.2.1'
