### ISSUE TITLE
3.0.7 设置点击事件setOnItemClickListener ，崩溃。环境为：最新版android studio  ，gradle-7.2

### ISSUE THREAD

**Issue by android-taoge** [CymChad/BaseRecyclerViewAdapterHelper#3614]
Process: com.example.customviewpractice, PID: 20961
    java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/~~8WzCj7ns9uA2FADz3qLBHQ==/com.example.customviewpractice-eGLrtTObX928prmWXbfBNQ==/base.apk)
        at com.chad.library.adapter.base.BaseQuickAdapter.bindViewClickListener$lambda-7$lambda-6(BaseQuickAdapter.kt:495)
        at com.chad.library.adapter.base.BaseQuickAdapter.$r8$lambda$aqWf9Mix2Hshed6QsGcdRVGlHL8(Unknown Source:0)
        at com.chad.library.adapter.base.BaseQuickAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7750)
        at android.view.View.performClickInternal(View.java:7727)
        at android.view.View.access$3700(View.java:861)
        at android.view.View$PerformClick.run(View.java:29133)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by android-taoge** [comment]
撤回到3.0.4版本就没问题

**Comment by HurryYU** [comment]
implementation 'androidx.recyclerview:recyclerview:1.2.1'即可

**Comment by fengzoom** [comment]
var position = viewHolder.bindingAdapterPosition，貌似对应的bindingAdapterPosition，被干掉了，导致报错

**Comment by 18363853135** [comment]
> implementation 'androidx.recyclerview:recyclerview:1.2.1'即可

还是存在无法解决

**Comment by JackiePenghe** [comment]
在app module下手动依赖.能解决问题
implementation 'androidx.recyclerview:recyclerview:1.2.1'

**Comment by fengzoom** [comment]
我已经收到了····感谢来信！！！我会尽快浏览的！！

**Comment by BinIsGood** [comment]
> 在app module下手动依赖.能解决问题 implementation 'androidx.recyclerview:recyclerview:1.2.1'

按照该方法操作，确实解决了问题。

**Comment by fengzoom** [comment]
我已经收到了····感谢来信！！！我会尽快浏览的！！

**Comment by fengzoom** [comment]
我已经收到了····感谢来信！！！我会尽快浏览的！！
