### ISSUE TITLE
<bug>版本3.0.7 getViewByPosition 崩溃

### ISSUE THREAD

**Issue by leifu1107** [CymChad/BaseRecyclerViewAdapterHelper#3616]
找不到这个getBindingAdapterPosition()方法

 java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/com.closeli.btw-fdY2RSQ_3VLz5f4zNuyHKg==/base.apk)
        at com.chad.library.adapter.base.BaseQuickAdapter.bindViewClickListener$lambda-7$lambda-6(BaseQuickAdapter.kt:495)
        at com.chad.library.adapter.base.BaseQuickAdapter.$r8$lambda$aqWf9Mix2Hshed6QsGcdRVGlHL8(Unknown Source:0)
        at com.chad.library.adapter.base.BaseQuickAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7312)
        at android.view.View.performClickInternal(View.java:7286)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28242)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by dabingrunning** [comment]
+1

**Comment by dabingrunning** [comment]
implementation 'androidx.recyclerview:recyclerview:1.2.1'
把RecyclerView的版本升级一下就好了，androidx默认版本还是1.1.0

**Comment by CF-cs** [comment]
+1
