### ISSUE TITLE
加载更多报这个错误怎么解决呢?

### ISSUE THREAD

**Issue by roybill** [CymChad/BaseRecyclerViewAdapterHelper#3668]
项目中有特殊场景,需要让列表左右上下滑动,现在功能实现了,但是分页加载却提示空指针
1.OneViewHolder类:
public class OneViewHolder extends BaseViewHolder implements View.OnLongClickListener, View.OnClickListener {

    private SparseArray<View> viewSparseArray;

    private CommonViewHolder.onItemCommonClickListener commonClickListener;

    public OneViewHolder(@NotNull View view) {
        super(view);
        itemView.setOnClickListener(this);
        itemView.setOnLongClickListener(this);
        viewSparseArray = new SparseArray<>();
    }

    /**
     * 根据 ID 来获取 View
     *
     * @param viewId viewID
     * @param <T>    泛型
     * @return 将结果强转为 View 或 View 的子类型
     */
    public <T extends View> T getView(int viewId) {
        // 先从缓存中找，找打的话则直接返回
        // 如果找不到则 findViewById ，再把结果存入缓存中
        View view = viewSparseArray.get(viewId);
        if (view == null) {
            view = itemView.findViewById(viewId);
            viewSparseArray.put(viewId, view);
        }
        return (T) view;
    }

    public OneViewHolder setText(int viewId, CharSequence text) {
        TextView tv = getView(viewId);
        tv.setText(text);
        return this;
    }

//    public OneViewHolder setViewVisibility(int viewId, int visibility) {
//        getView(viewId).setVisibility(visibility);
//        return this;
//    }

    public OneViewHolder setImageResource(int viewId, int resourceId) {
        ImageView imageView = getView(viewId);
        imageView.setImageResource(resourceId);
        return this;
    }

    public interface onItemCommonClickListener {

        void onItemClickListener(int position);

        void onItemLongClickListener(int position);

    }

    public void setCommonClickListener(CommonViewHolder.onItemCommonClickListener commonClickListener) {
        this.commonClickListener = commonClickListener;
    }

    @Override
    public void onClick(View v) {
        if (commonClickListener != null) {
            commonClickListener.onItemClickListener(getAdapterPosition());
        }
    }

    @Override
    public boolean onLongClick(View v) {
        if (commonClickListener != null) {
            commonClickListener.onItemLongClickListener(getAdapterPosition());
        }
        return false;
    }

}

2.MyCoinAdapter类:
public class MyCoinAdapter extends BaseQuickAdapter<OperatorBean.Lists, OneViewHolder> implements LoadMoreModule {

    private LayoutInflater mLayoutInflater;
    private int mLayoutId;
    private int mFixX;
    private ArrayList<View> mMoveViewList = new ArrayList<>();

    public MyCoinAdapter(int layoutResId) {
        super(layoutResId);
        mLayoutInflater = LayoutInflater.from(UIUtils.getContext());
        mLayoutId = layoutResId;
    }

    @Override
    protected void convert(@NotNull OneViewHolder baseViewHolder, OperatorBean.Lists bean) {
        baseViewHolder.setText(R.id.tv_number, String.valueOf(bean.getNumber()))
                .setText(R.id.tv_user, bean.getUserName())
                .setText(R.id.tv_wallet_address, bean.getAddress())
                .setText(R.id.tv_ip_address, bean.getIp());
    }

    @Override
    public OneViewHolder onCreateViewHolder(@NotNull ViewGroup parent, int viewType) {
        View itemView = mLayoutInflater.inflate(mLayoutId, parent, false);
//        LogUtils.d("0959    11111111111"+itemView);
        OneViewHolder holder = new OneViewHolder(itemView);
//        LogUtils.d("0959    22222222222"+holder);
//        //获取可滑动的view布局
        LinearLayout moveLayout = holder.getView(R.id.id_move_layout);
//        LogUtils.d("0959    333333333"+moveLayout);
        moveLayout.scrollTo(mFixX, 0);
        mMoveViewList.add(moveLayout);
        return holder;
    }

    public ArrayList<View> getMoveViewList(){
        return mMoveViewList;
    }

    public void setFixX(int fixX){
        mFixX=fixX;
    }
}

3.错误信息
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at com.chad.library.adapter.base.loadmore.BaseLoadMoreView.isVisible(BaseLoadMoreView.kt:92)
        at com.chad.library.adapter.base.loadmore.BaseLoadMoreView.convert(BaseLoadMoreView.kt:71)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:372)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6198)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
    
    
    --------- beginning of system

**Comment by limuyang2** [comment]
建议你不要使用库中的便捷方法，直接自己 `findViewById` 并判断 null
