### ISSUE TITLE
V4新版本DefaultTrailingLoadStateAdapter$TrailingLoadStateVH类型强制转换错误

### ISSUE THREAD

**Issue by anjiuzhe** [CymChad/BaseRecyclerViewAdapterHelper#3692]
mRecyclerView.setRecycledViewPool(RecyclerViewPoolProvider.getCommonGameRecyclerPool());

两个页面的Recyclerview共用同一个RecyclerViewPool，如果都使用了加载等多的功能，内部会把列表的VH强制转换成TrailingLoadStateVH导致崩溃，下面是日志

2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG: Process Name: 'com.jiaozishouyou.android'
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG: Thread Name: 'main'
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG: Back traces starts.
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG: java.lang.ClassCastException: com.jiaozigame.android.common.base.BaseViewBindingHolder cannot be cast to com.chad.library.adapter.base.loadState.trailing.DefaultTrailingLoadStateAdapter$TrailingLoadStateVH
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.chad.library.adapter.base.loadState.trailing.DefaultTrailingLoadStateAdapter.onBindViewHolder(DefaultTrailingLoadStateAdapter.kt:16)
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.chad.library.adapter.base.loadState.LoadStateAdapter.onBindViewHolder(LoadStateAdapter.kt:58)
2022-09-15 10:10:29.615 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.chad.library.adapter.base.loadState.LoadStateAdapter.onBindViewHolder(LoadStateAdapter.kt:62)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.NestedAdapterWrapper.onBindViewHolder(NestedAdapterWrapper.java:157)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.ConcatAdapterController.onBindViewHolder(ConcatAdapterController.java:378)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.ConcatAdapter.onBindViewHolder(ConcatAdapter.java:189)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
2022-09-15 10:10:29.616 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
2022-09-15 10:10:29.617 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.618 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.619 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:1008)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.View.layout(View.java:23472)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewGroup.layout(ViewGroup.java:6526)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3985)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3436)
2022-09-15 10:10:29.620 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2318)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9232)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1186)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.Choreographer.doCallbacks(Choreographer.java:986)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.Choreographer.doFrame(Choreographer.java:912)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1171)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.os.Handler.handleCallback(Handler.java:938)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.os.Looper.loopOnce(Looper.java:233)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.os.Looper.loop(Looper.java:334)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at android.app.ActivityThread.main(ActivityThread.java:8344)
2022-09-15 10:10:29.621 4151-4151/com.jiaozishouyou.android E/DEBUG:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 10:10:29.622 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
2022-09-15 10:10:29.622 4151-4151/com.jiaozishouyou.android E/DEBUG:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
2022-09-15 10:10:29.622 4151-4151/com.jiaozishouyou.android E/DEBUG: Back traces ends.
2022-09-15 10:10:29.622 4151-4151/com.jiaozishouyou.android E/DEBUG: --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by anjiuzhe** [comment]
解决了，如果RecyclerView共用同一个回收池的话需要将ConcatAdapter的mIsolateViewTypes属性设置为false,
QuickAdapterHelper.Builder(this).setConfig(ConcatAdapter.Config.Builder().setIsolateViewTypes(false).build()).build()
同时需要注意的是如果有添加HeaderAdapter或者FooterAdapter需要重写getItemViewType方法，一般返回布局ID，类似DefaultTrailingLoadStateAdapter。

**Comment by insomniastay** [comment]
-keep public class * extends com.chad.library.adapter.base.viewholder.BaseViewHolder{
 <init>(...);
}
-keepclassmembers  class **$** extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
     <init>(...);
}
-keep class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {*;}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter

# 保留 BaseQuickAdapter 的泛型类型信息
-keep class com.chad.library.adapter.base.** { *; }

# 保留 ViewHolder 的泛型信息
-keepclassmembers class * extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
    <fields>;
    <methods>;
}

# 防止擦除泛型类
-keepattributes Signature

**Comment by insomniastay** [comment]
-keep public class * extends com.chad.library.adapter.base.viewholder.BaseViewHolder{
 <init>(...);
}
-keepclassmembers  class **$** extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
     <init>(...);
}
-keep class com.chad.library.adapter.base.viewholder.BaseDataBindingHolder {*;}
-keep public class * extends com.chad.library.adapter.base.BaseQuickAdapter
-keep class com.chad.library.adapter.base.** { *; }
-keepclassmembers class * extends com.chad.library.adapter.base.viewholder.BaseViewHolder {
    <fields>;
    <methods>;
}
-keepattributes Signature
