### ISSUE TITLE
多类型布局 第一次加载正常 ，下拉刷新重新设置数据 ，报错 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fwcjszyss** [CymChad/BaseRecyclerViewAdapterHelper#3752]
override fun getDataSuccess(mutableList: MutableList<VideoItemBean>) {
        list.clear()
        for (item in mutableList){
            var videoTitleBean = VideoTitleBean(item.dict_code,item.dict_name)
            list.add(videoTitleBean)

            for (videoItem in item.data!!){
                list.add(videoItem)
            }
        }
        adapter.notifyDataSetChanged()
        binding.refreshLayout.finishRefresh(true)
    }

首次加载正常， 执行下拉刷新后报错 如下：
                                                                                                    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=33; index=-1
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:439)
                                                                                                    	at com.lipont.appk.ui.adapter.FunVideoAdapter$3.onItemViewType(FunVideoAdapter.kt:79)

onItemViewType(object : BaseMultiItemAdapter.OnItemViewTypeListener<MultiItemEntity>{
            override fun onItemViewType(position: Int, list: List<MultiItemEntity>): Int {

                NLog.d("position = $position")  // 这里报错， position = -1 
                return list.get(position).itemType
            }

        }

**Comment by limuyang2** [comment]
请说明下你使用的版本

**Comment by limuyang2** [comment]
更新 beta12
