### ISSUE TITLE
使用后发现个问题

### ISSUE THREAD

**Issue by hiquanta** [CymChad/BaseRecyclerViewAdapterHelper#402]
10-15 12:36:57.076 6820-6820/com.hiquanta.scaffold E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.hiquanta.scaffold, PID: 6820
                                                                     java.lang.NoSuchMethodError: No virtual method getLayoutPosition()I in class Landroid/support/v7/widget/RecyclerView$ViewHolder; or its super classes (declaration of 'android.support.v7.widget.RecyclerView$ViewHolder' appears in /data/data/com.hiquanta.scaffold/files/instant-run/dex/slice-com.android.support-recyclerview-v7-21.0.3_df540e2a50890ed1f7dca1bd1facf505177c5453-classes.dex)
                                                                         at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:595)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

我使用的api 为21 编译 ，而类库是23，会报这个错

**Comment by elfman** [comment]
从错误日志里看，你用的recyclerview的版本是21的吧，试试改为23

**Comment by hiquanta** [comment]
改为23后可以正常试用

**Comment by elfman** [comment]
所以这个错误是因为21版本的viewHolder没有getLayoutPosition()这个方法，一调用就会出错

**Comment by adu4862** [comment]
谢谢,解决了我的问题
