### ISSUE TITLE
关于进入页面时快速上滑loadmore  出现崩溃

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#403]
这个问题在#354出现过，   这种问题  BRVAH官方推荐怎么解决
[#354](https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/354)

java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6720)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6686)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6674)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1404)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
                                                                       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4061)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:605)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)

**Comment by elfman** [comment]
把你代码发一下，主要是inflate那部分

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.2'   已修复
