### ISSUE TITLE
发现一个bug.在endView之外的空白区域滑动时会空针

### ISSUE THREAD

**Issue by jestar719** [CymChad/BaseRecyclerViewAdapterHelper#429]
使用版本为2.2.3
![default](https://cloud.githubusercontent.com/assets/16207160/19594539/0b868cf4-97b8-11e6-9f07-39715389fb7f.png)

错误信息为
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground()' on a null object reference
                                                                         at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onDown(SimpleClickListener.java:81)
                                                                         at android.view.GestureDetector.onTouchEvent(GestureDetector.java:590)
                                                                         at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:475)
                                                                         at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:538)
                                                                         at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:50)
                                                                         at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2231)
                                                                         at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2277)

另外hiedLoadingMore();这个方法名写错了.应该是hide

**Comment by CymChad** [comment]
你升级为2.2.9就没有问题了。

**Comment by CymChad** [comment]
多谢提醒，方法名已改正过来了。
