### ISSUE TITLE
2.2.3  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:9).state:10

### ISSUE THREAD

**Issue by proud2008** [CymChad/BaseRecyclerViewAdapterHelper#431]
添加一个header
上滑加载有时会出现 一次只加载8条数据，1个header,共9，位置最大也就8呀
adapter = new BaseQuickAdapter(getActivity(), new ArrayList<NiceHttpEntityAlbum>());
加载到网络数据
 if (page == 1) {
                adapter.setNewData(mDataAlbumEntityList);
            } else {
                adapter.addData(mDataAlbumEntityList);
            }
            page++;
异常Log
FATAL EXCEPTION: main
  Process: com.yll.zb.test, PID: 10875
  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:9).state:10
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4659)
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
      at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
      at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1538)
      at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:657)
      at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:592)
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
      at android.view.View.layout(View.java:14828)
      at android.view.ViewGroup.layout(ViewGroup.java:4631)
      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2030)
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1043)
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5652)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
      at android.view.Choreographer.doFrame(Choreographer.java:544)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5052)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
      at dalvik.system.NativeStart.main(Native Method)

**Comment by yoyiyi** [comment]
我也碰到了 你需要新建一个类 `继承LinearLayoutManager` 重写
```
 @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (IndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
```

**Comment by CymChad** [comment]
请贴出完整代码

**Comment by yuruxuan** [comment]
我也出现了这个问题，错误代码只能定位到RecyclerView

**Comment by proud2008** [comment]
猜测是因为loadingview的原因，
这么改就可以了，虽然暴力点，

    public void loadComplete() {
        mNextLoadEnable = false;
        mLoadingMoreEnable = false;
//        this.notifyItemChanged(getItemCount());
        notifyDataSetChanged();
    }

baseadapter
    public void addData(List<T> newData) {
        this.mData.addAll(newData);
        hideLoadingMore();
        notifyItemRangeInserted(mData.size() - newData.size() + getHeaderLayoutCount(), newData.size());
//        notifyDataSetChanged();
    }
notifyDataSetChanged 这行应该是多余的

对loadingview的控制还不太明白

**Comment by CymChad** [comment]
多谢，我看看。

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.3.3'  已发布 loadComplete改成了notifyDataSetChanged，addData注释了notifyItemRangeInserted，因为notifyItemRangeInserted会引发 #414

**Comment by jinvovo** [comment]
if (pageNo == 1) {
                        if (dataList != null && dataList.size() > 0)
                            list.addAll(dataList);
                        adapter.notifyDataSetChanged();
                    } else {
                        int count = list.size();
                        if (dataList != null && dataList.size() > 0)
                            list.addAll(dataList);
                        adapter.notifyItemRangeChanged(count, list.size());
                    }

  adapter.notifyItemRangeChanged(count, list.size());加载更多使用这个方法能解决这个！

**Comment by EMIN3M1986** [comment]
https://stackoverflow.com/a/47324896/4468776

**Comment by d-rahul** [comment]
I also encountered the same issue but get it resolved from
https://readyandroid.wordpress.com/java-lang-indexoutofboundsexception-inconsistency-detected-invalid-item-position-android-recyclerview/
Nice blog with Android tricks: https://readyandroid.wordpress.com/
