### ISSUE TITLE
自定义多item布局怎么获取itemType？

### ISSUE THREAD

**Issue by qzgyw** [CymChad/BaseRecyclerViewAdapterHelper#458]
> mRecyclerView.addOnItemTouchListener(new OnItemChildClickListener() {
            @Override
            public void SimpleOnItemChildClick(BaseQuickAdapter baseQuickAdapter, View view, int i) {
                Toast.makeText(Aty_main.this, multipleItemAdapter.getItemViewType(i), Toast.LENGTH_SHORT).show();
            }
});

multipleItemAdapter.getItemViewType(i)  和  multipleItemAdapter.getItem(i).getItemType() 都会报错

**Comment by CymChad** [comment]
报错？

**Comment by qzgyw** [comment]
@CymChad 是的  我上边的获取方法没问题吧？Activity里边点击事件中获取这个itemType，一点击就崩溃了

**Comment by CymChad** [comment]
没问题，itemType是绑定在数据上面的，拿到当前数据就可以拿到当前的itemType，请贴出crash日志。

**Comment by qzgyw** [comment]
> E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: android.content.res.Resources$NotFoundException: String resource ID #0x2
                        at android.content.res.Resources.getText(Resources.java:331)
                        at android.widget.Toast.makeText(Toast.java:287)
                        at com.jinbeier.o2o.Aty.Aty_main$2.SimpleOnItemChildClick(Aty_main.java:54)
                        at com.chad.library.adapter.base.listener.OnItemChildClickListener.onItemChildClick(OnItemChildClickListener.java:28)
                        at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SimpleClickListener.java:121)
                        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
                        at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:475)
                        at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:538)
                        at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:50)
                        at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2424)
                        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2552)
                        at android.view.View.dispatchTouchEvent(View.java:9940)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                        at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)

**Comment by qzgyw** [comment]
@CymChad  实体类里边的其它属性是可以拿到的，只有itemType和spanSize取不到，应用会crash

**Comment by CymChad** [comment]
我通过以下方式可以拿到
```java
mRecyclerView.addOnItemTouchListener(new OnItemClickListener() {
            @Override
            public void SimpleOnItemClick(BaseQuickAdapter adapter, View view, int position) {
                MultipleItem multipleItem = (MultipleItem) adapter.getData().get(position);
                Toast.makeText(MultipleItemUseActivity.this,multipleItem.getItemType()+"",Toast.LENGTH_LONG).show();
            }
        });
```
