### ISSUE TITLE
关于自定义控件ID  点击其他位置崩溃的BUG

### ISSUE THREAD

**Issue by yuruxuan** [CymChad/BaseRecyclerViewAdapterHelper#459]
我有一个自定义的组合控件，其中id是这样设置的
```
private void init() {
       for (int i = 0; i < 9; i++) {
           ImageView imageView = new ImageView(getContext());
           int id = getContext().getResources().getIdentifier("smart_image_view_item_"+i,"id",getContext().getPackageName());
           imageView.setId(id);
           imageViewList.add(imageView);
       }
   }
```

其中引用的id文件是res里面创建的  文件名是ids.xml内容如下：
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
   <item name="smart_image_view_item_0" type="id" />
   <item name="smart_image_view_item_1" type="id" />
   <item name="smart_image_view_item_2" type="id" />
   <item name="smart_image_view_item_3" type="id" />
   <item name="smart_image_view_item_4" type="id" />
   <item name="smart_image_view_item_5" type="id" />
   <item name="smart_image_view_item_6" type="id" />
   <item name="smart_image_view_item_7" type="id" />
   <item name="smart_image_view_item_8" type="id" />
   <item name="smart_image_view_item_9" type="id" />
</resources>
```

然后我在BRVAH里进行绑定
```
//9图
       for (int i = 0; i < 9; i++) {
           int id = mContext.getResources().getIdentifier("smart_image_view_item_" + i, "id", mContext.getPackageName());
           baseViewHolder.addOnClickListener(id);
       }
```

然后效果就是这些image点击是可以响应的，但是点击其他东西都会崩溃，崩溃日志如下：
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                        at com.chad.library.adapter.base.listener.SimpleClickListener.inRangeOfView(SimpleClickListener.java:207)
                                                                        at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SimpleClickListener.java:113)
                                                                        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
                                                                        at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:475)
                                                                        at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:538)
                                                                        at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:50)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2261)
                                                                        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2389)
                                                                        at android.view.View.dispatchTouchEvent(View.java:9306)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2820)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                        at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4262)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4128)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3814)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3871)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)

```
我个人觉得  id找不到的话是不是应该return   而不应该抛异常………………

**Comment by AllenCoder** [comment]
你绑定了一个空id ，肯定是会有问题的

**Comment by yuruxuan** [comment]
@AllenCoder 这个id不是空啊，我在代码里面设置了

```
ImageView imageView = new ImageView(getContext());
           int id = getContext().getResources().getIdentifier("smart_image_view_item_"+i,"id",getContext().getPackageName());
           imageView.setId(id);
```

**Comment by AllenCoder** [comment]
你是哪个版本？

**Comment by AllenCoder** [comment]
请更新至最新版本重试

**Comment by yuruxuan** [comment]
@AllenCoder 难道只能绑定xml里面Android：id=“@+id/...” 这种形式？？那就太不灵活了，而且现在的现象是  我这样绑定的控件  点击是可以响应的  但是其他子控件会爆上面的问题包括itemclick也是一样的

**Comment by AllenCoder** [comment]
这个     int id = getContext().getResources().getIdentifier("smart_image_view_item_"+i,"id",getContext().getPackageName()); 
能通过itemview 的findViewById找到吗？ 如果不能找到，肯定是会报空指针错误，只能绑定itemview里面的控件

**Comment by yuruxuan** [comment]
现在是compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.2'

**Comment by AllenCoder** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/416 这个issue应该跟你的一样

v2.2.2需要升级

**Comment by yuruxuan** [comment]
@AllenCoder 好的  我升一下试试

**Comment by yuruxuan** [comment]
@AllenCoder 不可以  问题依然存在  我录一个小视频吧   发到陈总邮箱

**Comment by yuruxuan** [comment]
@AllenCoder 是我这里逻辑的问题   不是框架的事儿    真是不好意思    浪费您的时间了……
