### ISSUE TITLE
Crash when clicking on header

### ISSUE THREAD

**Issue by jameltheone** [CymChad/BaseRecyclerViewAdapterHelper#474]
Hi, i'm using the last version of this library and I get a crash when clicking on the header view. Unfortunately I were not able to reproduce the bug, it occurred only once.

Below is the stack trace:
 
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(int)' on a null object reference
	at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:233)
	at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:31)
	at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SimpleClickListener.java:112)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
	at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
	at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
	at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:50)
	at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2504)
	at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2550)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
	at android.view.View.dispatchPointerEvent(View.java:10243)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by CymChad** [comment]
library version is?

**Comment by jameltheone** [comment]
2.4.5

**Comment by AllenCoder** [comment]
@jameltheone  Recyclerview version and device is ?

**Comment by jameltheone** [comment]
@AllenCoder Recyclerview version is v7:25.0.0 and device is nexus 5X running under android 7.1.1
Please notice that i only had the crash once.

**Comment by AllenCoder** [comment]
maybe sometime recyclerview adapter is be release 。 I will improve the code and use it more securely。

**Comment by jameltheone** [comment]
Great! Thank you

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.4.7'
