### ISSUE TITLE
自定义的ViewHolder继承了你的BaseViewHolder导制无法转换报错

### ISSUE THREAD

**Issue by akingyin1987** [CymChad/BaseRecyclerViewAdapterHelper#535]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.akingyin.androidbase.multimedia.MultimediaViewHolder
                                                                              at com.akingyin.androidbase.multimedia.MultimediaAdapter.convert(MultimediaAdapter.java:41)
                                                                              at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:582)
                                                                              at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:56)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6067)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6100)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5282)

**Comment by CymChad** [comment]
和 #536 一样
