### ISSUE TITLE
自定义的ViewHolder继承了你的BaseViewHolder导制无法转换报错

### ISSUE THREAD

**Issue by akingyin1987** [CymChad/BaseRecyclerViewAdapterHelper#536]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.akingyin.androidbase.multimedia.MultimediaViewHolder
                                                                              at com.akingyin.androidbase.multimedia.MultimediaAdapter.convert(MultimediaAdapter.java:41)
                                                                              at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:582)
                                                                              at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:56)
                                                                              at 

android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6067)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6100)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5282)

**Comment by akingyin1987** [comment]
刚看了源码，确实是不可以用自定义ViewHolder 的，我建议，创建ViewHolder 可以抽象出来，要不就不太方便了，因为我这个比较复杂在自定义里面加了很多的功能

**Comment by CymChad** [comment]
收到我看看

**Comment by akingyin1987** [comment]
可以解决了，重写方法createBaseViewHolder  就可以实现

**Comment by elfman** [comment]
现在已经能自定义ViewHolder了啊，但需要继承BaseViewHolder，并重写`createBaseViewHolder(view)`方法来创建ViewHolder，具体参考demo里DataBindingUseAdapter的代码
