### ISSUE TITLE
com.chad.library.adapter.base.BaseViewHolder cannot be cast to XXXViewHolder

### ISSUE THREAD

**Issue by p8499** [CymChad/BaseRecyclerViewAdapterHelper#540]
我遇到11-20 22:12:58.290 3432-3432/com.p8499.lang E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.p8499.lang, PID: 3432
                                                              java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to com.p8499.lang.comp.erv_articles.ErvArticlesViewHolder
                                                                  at com.p8499.lang.comp.erv_articles.ErvArticlesAdapter.convert(ErvArticlesAdapter.java:11)
                                                                  at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:607)
                                                                  at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:57)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1319)
                                                                  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:817)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                              	at android.os.Handler.dispatchMessage(Hand

																
看了源代码，我发现BaseQuickAdapter.java Line:423
protected K createBaseViewHolder(View view)
这个方法是否应该设为abstract?这样让子类直接提供ViewHolder实例，否则出来的都是BaseViewHolder。当然，用户可以Override这个方法，但是我觉得abstract更好一些，要不然大家看源代码才能发觉问题。
以上拙见大师看下

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/Use-Custom-BaseViewHolder
这是文档，abstract会让所有的adapter需要重写，很多使用者都不需要自定义ViewHolder。
解决问题，应当按照 #499 流程来。
