### ISSUE TITLE
loadmore setNewData() show indexOutOfBoundsException.

### ISSUE THREAD

**Issue by ytrjp** [CymChad/BaseRecyclerViewAdapterHelper#583]
Process: com.xiangkan.android, PID: 24090
                                                                      java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{e5507ea position=53 id=-1, oldPos=15, pLpos:15 scrap [attachedScrap] tmpDetached no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4858)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4989)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                          at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1556)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:666)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:598)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3266)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3122)

**Comment by ytrjp** [comment]
![image](https://cloud.githubusercontent.com/assets/1198711/20858580/d2bc1bfe-b982-11e6-868e-311b0fbf277a.png)

**Comment by ytrjp** [comment]
![image](https://cloud.githubusercontent.com/assets/1198711/20858710/88b1e40e-b986-11e6-9ee4-e14c092ec590.png)
![image](https://cloud.githubusercontent.com/assets/1198711/20858711/8e29f372-b986-11e6-9fa4-f25b016fea61.png)

**Comment by 1109993488** [comment]
newData should be a new object，show you the calling code
