### ISSUE TITLE
refresh 不使用handle.postdelay出现问题如下。

### ISSUE THREAD

**Issue by ytrjp** [CymChad/BaseRecyclerViewAdapterHelper#589]
Process: com.chad.baserecyclerviewadapterhelper, PID: 6494
                                                                                      java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                                                          at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2397)
                                                                                          at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4634)
                                                                                          at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:10472)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:6248)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.addData(BaseQuickAdapter.java:342)
                                                                                          at com.chad.baserecyclerviewadapterhelper.PullToRefreshUseActivity.onLoadMoreRequested(PullToRefreshUseActivity.java:74)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.autoLoadMore(BaseQuickAdapter.java:916)
                                                                                          at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:463)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5017)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                                          at android.view.View.layout(View.java:16653)
                                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)

**Comment by ytrjp** [comment]
使用的时候感觉坑还是不少，能把坑和使用的地方说一下不？

**Comment by CymChad** [comment]
恩，这一块我们后续会在文档上补上说明，多谢提醒。

**Comment by CymChad** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper/wiki/%E4%B8%8A%E6%8B%89%E5%8A%A0%E8%BD%BD  文档上面使用是有的，但是没有特殊说明，这是我们的问题，

**Comment by CymChad** [comment]
已修改

**Comment by ytrjp** [comment]
好的，已经看到
