### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by ytrjp** [CymChad/BaseRecyclerViewAdapterHelper#590]
代码：

switch (event.getOperationType()) {
            case NearbyActionCreator.ACTION_REFRESH: {
                recyclerView.post(new Runnable() {
                    @Override
                    public void run() {
                        mList = store.getVideoData().list;
                        after = store.getVideoData().after;
                        mAdapter.setNewData(mList);
                        swipeRefreshLayout.setRefreshing(false);
                        mAdapter.setEnableLoadMore(true);
                    }
                });
            }
                break;
            case NearbyActionCreator.ACTION_LOAD_MORE: {
                recyclerView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        List<Video> datas = store.getVideoData().list;
                        after = store.getVideoData().after;
//                        mList.addAll(list);
                        mAdapter.addData(datas);
                        if (datas.size() < 5/*Constant.DEF_PAGE_SIZE*/ || after == null || after.length() == 0) {
                            mAdapter.loadMoreEnd();
                        } else {
                            mAdapter.loadMoreComplete();
                        }
                        swipeRefreshLayout.setEnabled(true);
                    }
                }, 1000);
            }
                break;
            case NearbyActionCreator.ACTION_ERROR:
                mAdapter.loadMoreFail();
                break;

**Comment by ytrjp** [comment]
crash: 
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{7dfde5a position=53 id=-1, oldPos=15, pLpos:15 scrap [attachedScrap] tmpDetached no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4858)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4989)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                          at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1556)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:666)
                                                                          at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:598)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3266)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3122)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16653)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                      	at android.widget.Linear

**Comment by ytrjp** [comment]
使用以下方式，但是数据回来后，数据有闪烁，好像是重新加载了一次。
public class WrapperStaggerLayoutManager extends StaggeredGridLayoutManager{
    public WrapperStaggerLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public WrapperStaggerLayoutManager(int spanCount, int orientation) {
        super(spanCount, orientation);
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (IndexOutOfBoundsException e) {
            Log.e("TAG", "meet a IOOBE in RecyclerView");
        }
    }
}

**Comment by ytrjp** [comment]
这个问题有人跟一下不？

**Comment by CymChad** [comment]
你的版本号是？

**Comment by 1109993488** [comment]
你的mList在其他地方做了clear操作吗？RecyclerView的版本用的多少？

**Comment by ytrjp** [comment]
@CymChad 是必现的。

**Comment by ytrjp** [comment]
@1109993488  没有clear.     版本：compile 'com.android.support:recyclerview-v7:24.0.0'

**Comment by 1109993488** [comment]
switch之外还有操作代码吗？switch里哪个case出错了？

**Comment by ytrjp** [comment]
@1109993488  没有了

**Comment by ytrjp** [comment]
@1109993488  在ACTION_LOAD_MORE 加载更多，报java.lang.IndexOutOfBoundsException: Inconsistency detected。

**Comment by 1109993488** [comment]
能贴出完整能出错的代码吗

**Comment by ytrjp** [comment]
public class NearbyFragment extends BaseFragment implements BaseQuickAdapter.RequestLoadMoreListener, SwipeRefreshLayout.OnRefreshListener {
    private static final String TAG = NearbyFragment.class.getSimpleName();

    @BindView(R.id.recycler_view)
    RecyclerView recyclerView;
    @BindView(R.id.swipe_refresh_layout)
    SwipeRefreshLayout swipeRefreshLayout;

    private NearbyVideoAdapter mAdapter;
    private Dispatcher dispatcher;
    private NearbyStore store;
    private NearbyActionCreator actionCreator;
    private String after = Constant.DEF_AFTER;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initDependencies();
    }

    @Override
    public void onStart() {
        super.onStart();
        dispatcher.register(this, store);
    }

    @Override
    public void onStop() {
        super.onStop();
        dispatcher.unregister(this, store);
    }

    @Override
    protected int createView() {
        return R.layout.nearby_fragment;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        swipeRefreshLayout.setOnRefreshListener(this);
        recyclerView.setLayoutManager(new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL));
        recyclerView.addItemDecoration(new DividerGridItemDecoration(getResources().getDimensionPixelOffset(R.dimen.dp_10)));
        initAdapter();
    }

    @Override
    public void onBackPressed() {

    }

    private void initDependencies() {
        dispatcher = Dispatcher.get();
        actionCreator = new NearbyActionCreator(dispatcher);
        store = new NearbyStore();
    }

    private void initAdapter() {
        mAdapter = new NearbyVideoAdapter(null);
        mAdapter.setOnLoadMoreListener(this);
        mAdapter.setAutoLoadMoreSize(3);
        recyclerView.setAdapter(mAdapter);
    }

    @Override
    public void onRefresh() {
        mAdapter.setEnableLoadMore(false);
        actionCreator.refresh();
    }

    @Override
    public void onLoadMoreRequested() {
        recyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                swipeRefreshLayout.setEnabled(false);
                actionCreator.loadMore(after);
            }
        }, 100);

    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void OnStoreChange(NearbyStore.NearbyStoreEvent event) {
        switch (event.getOperationType()) {
            case NearbyActionCreator.ACTION_REFRESH: {
                mAdapter.setNewData(store.getVideoData().list);
                after = store.getVideoData().after;
                swipeRefreshLayout.setRefreshing(false);
                mAdapter.setEnableLoadMore(true);
            }
            break;
            case NearbyActionCreator.ACTION_LOAD_MORE: {
                List<Video> datas = store.getVideoData().list;
                String offset = store.getVideoData().after;
                mAdapter.addData(datas);
                if (datas.size() < 5/*Constant.DEF_PAGE_SIZE*/ || offset == null || offset.length() == 0 || offset.equals(after)) {
                    mAdapter.loadMoreEnd();
                } else {
                    mAdapter.loadMoreComplete();
                }
                after = store.getVideoData().after;
                swipeRefreshLayout.setEnabled(true);
            }
            break;
            case NearbyActionCreator.ACTION_ERROR:
                mAdapter.loadMoreFail();
                break;
        }
    }
}

**Comment by 1109993488** [comment]
看代码没问题，麻烦你描述下crash触发操作，以及`store.getVideoData().list`怎么赋值的

**Comment by CymChad** [comment]
@ytrjp 问题解决了没？

**Comment by AllenCoder** [comment]
实际测试，我的app在最近一版也大规模上报了这个bug，查找多方资料，是Google 的recyclerview bug。目前没有有效的处理办法，只要一个兜底办法就是将recyclerview出现的异常捕获 。https://code.google.com/p/android/issues/detail?id=77846#c63

自定义  LinearLayoutManager 捕获这个异常
```java
/*
******************************* Copyright (c)*********************************\
**
**                 (c) Copyright 2015, Allen, china, shanghai
**                          All Rights Reserved
**
**                          
**                         
**-----------------------------------版本信息------------------------------------
** 版    本: V0.1
**
**------------------------------------------------------------------------------
********************************End of Head************************************\
*/
package com.wattforex.base;

import android.content.Context;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import com.wattforex.util.MLog;

/**
 * 文 件 名: CustomLayoutManager
 * 创 建 人: Allen
 * 创建日期: 16/12/9 15:36
 * 邮   箱: AllenCoder@126.com
 * 修改时间：
 * 修改备注：
 */
public class CustomLayoutManager extends LinearLayoutManager {
    private String TAG="CustomLayoutManager";

    public CustomLayoutManager(final Context context) {
        super(context);
    }

    @Override
    public void onLayoutChildren(final RecyclerView.Recycler recycler, final RecyclerView.State state) {
        try {
            super.onLayoutChildren(recycler, state);
        } catch (Exception e) {
            MLog.e(TAG, "onLayoutChildren: "+e.getLocalizedMessage() );
            e.printStackTrace();
        } finally {
        }
    }
}

```

改善代码后，在50ms内定时不间断刷新滑动，没有在出现崩溃，同时日志确实捕获到了改异常。
