### ISSUE TITLE
你好，在使用多布局时出现了如下空指针异常

### ISSUE THREAD

**Issue by qq781548819** [CymChad/BaseRecyclerViewAdapterHelper#597]
java.lang.NullPointerException
                                                                        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:52)
                                                                        at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:48)
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:507)
                                                                        at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5833)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5057)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:541)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
                                                                        at android.view.View.measure(View.java:16497)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                        at android.view.View.measure(View.java:16497)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                        at android.view.View.measure(View.java:16497)
                                                                        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                        at android.widget.ScrollView.onMeasure(ScrollView.java:326)
                                                                        at android.view.View.measure(View.java:16497)

**Comment by qq781548819** [comment]
不好意思，搞错了，没有给data添加对应的ItemType，好强大，哈哈

**Comment by CymChad** [comment]
感谢你的使用
