### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jameltheone** [CymChad/BaseRecyclerViewAdapterHelper#617]
Hi,

From crashlytics i've some users having a bug. Unfortunately, i can't reproduce it but i thought that sharing here could improve the library.

I'm using library version 2.6.0

Here is the stack trace

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at com.chad.library.adapter.base.listener.SimpleClickListener.onItemClick(SourceFile:244)
       at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onSingleTapUp(SourceFile:117)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
       at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(SourceFile:479)
       at android.support.v4.view.GestureDetectorCompat.onTouchEvent(SourceFile:542)
       at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SourceFile:51)
       at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(SourceFile:2539)
       at android.support.v7.widget.RecyclerView.onTouchEvent(SourceFile:2667)
       at android.view.View.dispatchTouchEvent(View.java:9306)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:790)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
       at android.view.View.dispatchPointerEvent(View.java:9526)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4262)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4128)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3814)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3871)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5954)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5928)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5889)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6057)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by AllenCoder** [comment]
thanks your report 。The crash may be that your view is recycled ，or your add childviewid is not in your item view 。

**Comment by jameltheone** [comment]
Thank you for your reply. Unfortunately i don't have any information about which view is causing this.
If i have any information, i'll get back to you.
