### ISSUE TITLE
我更新的版本2.6.6，出现了一个问题。

### ISSUE THREAD

**Issue by z2045217** [CymChad/BaseRecyclerViewAdapterHelper#634]
作者可以复现下。当adapter，清空数据Adapter.getData().clear()之后。在添加数据Adapter.addData(List<Object>)使出现了崩溃。之前在2.1的版本上面没有的。个人认为是notifyItemRangeInserted(this.mData.size() - newData.size() + this.getHeaderLayoutCount(), newData.size())这个出现的问题。

**Comment by z2045217** [comment]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{406e998 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4247)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4378)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
                                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                                      at android.view.View.layout(View.java:16065)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5234)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2544)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2234)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1331)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6792)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:607)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:576)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
                                                                                      at android.os.Handler.handleCallback(Handler.java:815)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                      at android.os.Looper.loop(Looper.java:224)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5911)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:

**Comment by 1109993488** [comment]
```
int size=mQuickAdapter.getData().size();
mQuickAdapter.getData().clear();
//主要少下面这句
mQuickAdapter.notifyItemRangeRemoved(mQuickAdapter.getHeaderLayoutCount(),size);
mQuickAdapter.addData(list);
```
以前用的是`notifyItemRangeChanged()`(错误处理)

**Comment by CymChad** [comment]
@z2045217 问题解决没？
