### ISSUE TITLE
在OnResume中再次初始化头部的时候会出现下面错误？？？？？？版本：2.6.6

### ISSUE THREAD

**Issue by mrchenmo** [CymChad/BaseRecyclerViewAdapterHelper#649]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{2fde25c7 position=0 id=-1, oldPos=-1, pLpos:-1}
                                                                   at android.support.v7.widget.RecyclerView$4.attachViewToParent(RecyclerView.java:581)
                                                                   at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:212)
                                                                   at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1003)
                                                                   at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:2911)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2711)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                   at android.view.View.layout(View.java:16112)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5185)
                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2525)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2217)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6673)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5826)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)

**Comment by mrchenmo** [comment]
2.6.3版本是没有问题的，升级到2.6.6就不行了，老是崩溃

**Comment by mrchenmo** [comment]
2.2是没问题的升级到2.6.6就出现这个问题，这很蛋疼啊

**Comment by 1109993488** [comment]
麻烦贴一下代码

**Comment by mrchenmo** [comment]
private void inflaterHeaderView() {
        //初始化头布局,现在要区分登录和未登录状态
        if (hView != null) {
            homeAdapter.removeHeaderView(hView);
            hView = null;
        }
        if (LoginState.LOGIN_ING.equals(RSAuthManager.getDefault().getRSLoginState())) {
            if (hView == null) {
                hView = getActivity().getLayoutInflater().inflate(R.layout.list_header, (ViewGroup) lv_chips_home.getParent(), false);
                mBanner = (Banner) hView.findViewById(R.id.image_url);
                for (int i = 0; i < bannerUrl.size(); i++) {
                    mBanner.addItem(bannerUrl.get(i), null);
                }
                homeAdapter.addHeaderView(hView);
            }
        } else if (LoginState.UNLOGIN.equals(RSAuthManager.getDefault().getRSLoginState())) {
            if (hView == null) {
                hView = getActivity().getLayoutInflater().inflate(R.layout.header_none_login, (ViewGroup) lv_chips_home.getParent(), false);
                ImageView mProduct_none_login = (ImageView) hView.findViewById(R.id.product_none_login);
                mProduct_none_login.setOnClickListener(this);
                homeAdapter.addHeaderView(hView);
            }
        }
    }
在OnResume中再次调用这个方法

 if (!mLoginState.equals(RSAuthManager.getDefault().getRSLoginState())) {
                //如果两次登录状态不一样，更新本地持有的状态，以便下次比较使用
                mLoginState = RSAuthManager.getDefault().getRSLoginState();
                inflaterHeaderView();
            }
就会报错

**Comment by 1109993488** [comment]
removeHeaderView和addHeaderView一起调用会有问题
你可以在addHeaderView 后面加上notifyDataSetChanged()解决

**Comment by mrchenmo** [comment]
@1109993488 那你会在之后的版本把这个解决吗？如果我不Remove的话，会出现多个HeaderView，在这之前的2.2版本是可以的，我对比了两个版本的代码，代码是改动了的。我会先使用这个临时方案解决。

**Comment by 1109993488** [comment]
恩，后续户优化

**Comment by mrchenmo** [comment]
@1109993488 谢谢，你能尽快把代码提交吗?我最近要上一个版本，我想更新下，麻烦了。

**Comment by 1109993488** [comment]
你可以先用这个临时方案解决，目前还没有好的解决办法

**Comment by mrchenmo** [comment]
@1109993488好的，老版本的代码可以服用的啊.2.2版本的这部分逻辑是没有问题的

**Comment by 1109993488** [comment]
BaseQuickAdapter的notify操作不一样，2.2应该是notifyDataSetChanged()

**Comment by CymChad** [comment]
恩，如果修复了会回复你的

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.6.8'  新增setHeaderView方法。

**Comment by CymChad** [comment]
可以让你不用调用
```java
if (hView != null) {
homeAdapter.removeHeaderView(hView);
hView = null;
}
```
直接`addHeaderView`改成`setHeaderView`。
