### ISSUE TITLE
很棒的库，网络断开就崩溃了。

### ISSUE THREAD

**Issue by focus2846** [CymChad/BaseRecyclerViewAdapterHelper#72]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                   at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getLayoutId(BaseMultiItemQuickAdapter.java:44)
                                                                   at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.onCreateDefViewHolder(BaseMultiItemQuickAdapter.java:40)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:401)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:32)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                   at com.qcwl.dsdj.utils.WrapContentLinearLayoutManager.onLayoutChildren(WrapContentLinearLayoutManager.java:24)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                   at com.qcwl.dsdj.percent.PercentLinearLayout.onLayout(PercentLinearLayout.java:76)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1091)
                                                                   at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:801)
                                                                   at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:126)
                                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
                                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                   at com.qcwl.dsdj.percent.PercentLinearLayout.onLayout(PercentLinearLayout.java:76)
                                                                   at android.view.View.layout(View.java:15671)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                               	at android.widget.FrameLayout.onLayout(FrameLayout.java:514

- 

1.

**Comment by focus2846** [comment]
不好意思啊 ，是我忽略了缓存的数据，已经解决了o(╯□╰)o

**Comment by CymChad** [comment]
好的，感谢使用！
