### ISSUE TITLE
快速滑动StaggeredGridLayoutManager布局，会崩溃

### ISSUE THREAD

**Issue by huwencheng** [CymChad/BaseRecyclerViewAdapterHelper#739]
备注：三星s6edge手机才会出现这个崩溃问题，在小米手机快速滑动不会出现这个问题

错误信息如下：java.lang.IllegalArgumentException: Pixel distance must be non-negative
                                                                              at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.addPosition(GapWorker.java:110)
                                                                              at android.support.v7.widget.StaggeredGridLayoutManager.collectAdjacentPrefetchPositions(StaggeredGridLayoutManager.java:2109)
                                                                              at android.support.v7.widget.GapWorker$LayoutPrefetchRegistryImpl.collectPrefetchPositionsFromView(GapWorker.java:94)
                                                                              at android.support.v7.widget.GapWorker.buildTaskList(GapWorker.java:213)
                                                                              at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:343)
                                                                              at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

recyclerview是25.1.0
![image](https://cloud.githubusercontent.com/assets/8435177/22181165/b726f07a-e0c0-11e6-8c57-5f27ecef5880.png)

**Comment by CymChad** [comment]
http://blog.csdn.net/msn465780/article/details/53907772

**Comment by CymChad** [comment]
这是RecyclerView的bug

**Comment by CymChad** [comment]
你换个版本试试
