### ISSUE TITLE
convert method has abnormal changes ?

### ISSUE THREAD

**Issue by AruLNadhaN** [CymChad/BaseRecyclerViewAdapterHelper#751]
I have 4 items in `selectedItems`. But 8 items BackgroundColor is being changed. I don't know why ?
I have checked it in my convert method by adding a log. But that log is printed only 4 times. 
Is this issue is due to scrolling ? Please guide me...

```
	class BrowseAdapter extends BaseQuickAdapter<Product, BrowseAdapter.ShotViewHolder> {

    private List<Product> mItems;
    private ClickListener mClickListener;
    Context mContext;
    private Map<String, String> selectedItems = new HashMap<>();


    public BrowseAdapter(List<Product> items, Context context) {
        super(R.layout.item_shot, items);
        mContext = context;
        mItems = items;
    }

    public void setCart(Map<String, String> cartItems) {
        this.selectedItems = cartItems;
        for (Map.Entry<String, String> entry : cartItems.entrySet()) {
            String key = entry.getKey();
            String values = entry.getValue();
            Timber.d("Key = " + key + " Values = " + values);
        }
    }

    public void setClickListener(ClickListener clickListener) {
        mClickListener = clickListener;
    }

    @Override
    protected ShotViewHolder createBaseViewHolder(View view) {
        return new ShotViewHolder(view);
    }

    Double getPrice(Product item) {
        if (item.productDisplayPrice().isEmpty())
            return Double.valueOf(item.productMRP());
        else
            return Double.valueOf(item.productDisplayPrice());
    }

    @Override
    protected void convert(ShotViewHolder shotViewHolder, Product item) {

        shotViewHolder.mItem = item;
        shotViewHolder.prodName.setText(StringUtils.capitalize(item.productName()));
        shotViewHolder.prodPrice.setText("₹ " + String.format("%.2f", getPrice(item)));
        shotViewHolder.prodUnit.setText(item.productUnit());
        if (selectedItems.containsKey(item.productID())) {
            String count = selectedItems.get(item.productID());
            shotViewHolder.mAddCart.setVisibility(View.GONE);
            shotViewHolder.mPickerView.setVisibility(VISIBLE);
            Timber.d("Current Product ID > " + item.productID());
            shotViewHolder.mHeader.setBackgroundColor(Color.CYAN);
            shotViewHolder.mPicker.setValue(Float.parseFloat(count));
        } else {
            shotViewHolder.mPickerView.setVisibility(View.GONE);
            shotViewHolder.mAddCart.setVisibility(View.VISIBLE);
        }

        Glide.with(shotViewHolder.itemView.getContext()).load(item.productImage())
                .placeholder(R.drawable.com_facebook_button_icon_blue).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(shotViewHolder.prodImage);

        shotViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mClickListener != null) {
                    mClickListener.onShotClick(shotViewHolder.mItem);
                }
            }
        });

    }

    public class ShotViewHolder extends BaseViewHolder {

        ImageView prodImage;
        TextView prodPrice;
        TextView prodName;
        TextView prodUnit;
        View mAddCart;
        View mPickerView;
        View mHeader;
        IncDecImageButton mPicker;
        Product mItem;

        public ShotViewHolder(View itemView) {
            super(itemView);
            prodImage = (ImageView) itemView.findViewById(R.id.image_shot);
            prodPrice = (TextView) itemView.findViewById(R.id.text_price);
            prodName = (TextView) itemView.findViewById(R.id.text_title);
            prodUnit = (TextView) itemView.findViewById(R.id.text_unit);
            mPickerView = (View) itemView.findViewById(R.id.quantity_picker);
            mHeader = (View) itemView.findViewById(R.id.layout_header);
            mPicker = (IncDecImageButton) itemView.findViewById(R.id.incdec);
            mAddCart = (View) itemView.findViewById(R.id.add_cart);

            mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
                    IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
            mPicker.setupValues(1, 20, 1, 1);
            mPicker.enableLongPress(true, true, 200);
        }
    }

    static class ProgressViewHolder extends BaseViewHolder {
        @BindView(R.id.progress)
        ProgressBar progress;

        public ProgressViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }
    }
}
```

**Comment by CymChad** [comment]
I'm sorry, just saw your problem, you can stick your code all let me simulation?

**Comment by CymChad** [comment]
`convert` method Is actually `onBindViewHolder` method

**Comment by CymChad** [comment]
I guess the question may be: data problem or cache problem

**Comment by CymChad** [comment]
Problems still exist?

**Comment by AruLNadhaN** [comment]
Solved it by changing the color back  to normal in the else statement!

**Comment by AruLNadhaN** [comment]
When I setNewData, I'm getting a lot of loading progress bar in my list. How can I Solve this ??  

```
    @Override
    public void updateItems(List<Product> items, Map<String, String> cartItems) {
        mBrowseAdapter.setNewData(items);
        mBrowseAdapter.setCart(cartItems);
        mBrowseAdapter.notifyDataSetChanged();
    }
```

![loading issue](https://cloud.githubusercontent.com/assets/5804413/22726499/ab2f0adc-edf9-11e6-897d-00ade9ee114e.png)

**Comment by 1109993488** [comment]
Please show your code.

**Comment by AruLNadhaN** [comment]
This problem only occur when I refresh the data through `updateItems` method.
You can refer the `BrowseAdapter` code in the Question.

BrowseFragment
```
    private void setupViews() {
        mLayoutManager = new GridLayoutManager(getActivity(), 2);
        mItemRecycler.setLayoutManager(mLayoutManager);
        mItemRecycler.setAdapter(mBrowseAdapter);
        mItemRecycler.addItemDecoration(new GridSpacingItemDecoration(2, 15, false));
    }

    @Override
    public void showItems(List<Product> items, Map<String, String> cartItems) {
        mBrowseAdapter = new BrowseAdapter(items, getActivity());
        mItemRecycler.setAdapter(mBrowseAdapter);
        mBrowseAdapter.setCart(cartItems);
        mBrowseAdapter.setClickListener(this);
        mItemRecycler.setVisibility(View.VISIBLE);
    }

    @Override
    public void updateItems(List<Product> items, Map<String, String> cartItems) {
        mBrowseAdapter.setNewData(items);
        mBrowseAdapter.setCart(cartItems);
        mBrowseAdapter.notifyDataSetChanged();
    }
```

**Comment by CymChad** [comment]
Set the item is wrong view Settings, set to load the view?

**Comment by CymChad** [comment]
Please show me your adapter all code.

**Comment by CymChad** [comment]
Better code to let us help you find the problem more quickly

**Comment by AruLNadhaN** [comment]
I have added all the code. The problem only occurs when I setNewData with List of 4 to 20 items. If it is over 20 items. I don't have this Issue. Sometimes it crashes!   

**ADAPTER**

```
class BrowseAdapter extends BaseQuickAdapter<Product, BrowseAdapter.ShotViewHolder> {

    private List<Product> mItems;
    private ClickListener mClickListener;
    Context mContext;
    private Map<String, String> selectedItems = new HashMap<>();

    public BrowseAdapter(List<Product> items, Context context) {
        super(R.layout.item_shot, items);
        mContext = context;
        mItems = items;
    }

    public void setCart(Map<String, String> cartItems) {
        this.selectedItems = cartItems;
        for (Map.Entry<String, String> entry : cartItems.entrySet()) {
            String key = entry.getKey();
            String values = entry.getValue();
        }
    }

    @Override
    public int getItemCount() {
        return mItems.size();
    }

    public void setClickListener(ClickListener clickListener) {
        mClickListener = clickListener;
    }

    @Override
    protected ShotViewHolder createBaseViewHolder(View view) {
        return new ShotViewHolder(view);
    }

    Double getPrice(Product item) {
        if (item.getProductDisplayPrice().isEmpty())
            return Double.valueOf(item.getProductMRP());
        else
            return Double.valueOf(item.getProductDisplayPrice());
    }

    @Override
    protected void convert(ShotViewHolder shotViewHolder, Product item) {
        shotViewHolder.mItem = item;
        shotViewHolder.prodName.setText(StringUtils.capitalize(item.getProductName()));
        shotViewHolder.prodPrice.setText("₹ " + String.format("%.2f", getPrice(item)));
        shotViewHolder.prodUnit.setText(item.getProductUnit());
        if (selectedItems.containsKey(item.getProductID())) {
            shotViewHolder.badge.setVisibility(VISIBLE);
            String count = selectedItems.get(item.getProductID());
            shotViewHolder.mAddCart.setVisibility(View.GONE);
            shotViewHolder.mPickerView.setVisibility(VISIBLE);
            shotViewHolder.mPicker.setValue(Float.parseFloat(count));
        } else {
            shotViewHolder.badge.setVisibility(View.GONE);
            shotViewHolder.mPickerView.setVisibility(View.GONE);
            shotViewHolder.mAddCart.setVisibility(VISIBLE);
        }

        Glide.with(shotViewHolder.itemView.getContext()).load(item.getProductImage())
                .placeholder(R.mipmap.ic_launcher).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(shotViewHolder.prodImage);

        shotViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mClickListener != null) {
                    mClickListener.onShotClick(shotViewHolder.mItem);
                }
            }
        });

        shotViewHolder.mAddCart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mClickListener != null) {
                    String Email = PrefUtils.getFromPrefs(mContext, "Email", null);
                    if (Email == null) {
                        mClickListener.onCartLogin();
                    } else
                        itemAdded(shotViewHolder);
                }
            }
        });

        shotViewHolder.mPicker.setOnValueChangeListener(new IncDecImageButton.OnValueChangeListener() {
            @Override
            public void onValueChange(IncDecImageButton view, float oldValue, float newValue) {
                itemQuantity(shotViewHolder, newValue);
                if (newValue == 0.0) {
                    itemRemoved(shotViewHolder);
                }
            }
        });

    }

    private void itemRemoved(ShotViewHolder shotViewHolder) {
        mClickListener.onCartRemove(shotViewHolder.mItem, shotViewHolder.getAdapterPosition());
        shotViewHolder.mPickerView.setVisibility(View.GONE);
        shotViewHolder.mAddCart.setVisibility(VISIBLE);
    }

    private void itemAdded(ShotViewHolder shotViewHolder) {
        mClickListener.onCartAdd(shotViewHolder.mItem, shotViewHolder.getAdapterPosition());
        shotViewHolder.mAddCart.setVisibility(View.GONE);
        shotViewHolder.mPickerView.setVisibility(VISIBLE);
        shotViewHolder.mPicker.setValue(1);
    }

    private void itemQuantity(ShotViewHolder shotViewHolder, float quantity) {
        mClickListener.onItemQuantity(shotViewHolder.mItem, quantity, shotViewHolder.getAdapterPosition());
    }

    public class ShotViewHolder extends BaseViewHolder {

        ImageView prodImage;
        TextView prodPrice;
        TextView prodName;
        TextView prodUnit;
        View mAddCart;
        View mPickerView;
        View mHeader;
        IncDecImageButton mPicker;
        Product mItem;
        MaterialBadgeTextView badge;

        public ShotViewHolder(View itemView) {
            super(itemView);
            prodImage = (ImageView) itemView.findViewById(R.id.image_shot);
            prodPrice = (TextView) itemView.findViewById(R.id.text_price);
            prodName = (TextView) itemView.findViewById(R.id.text_title);
            prodUnit = (TextView) itemView.findViewById(R.id.text_unit);
            mPickerView = (View) itemView.findViewById(R.id.quantity_picker);
            mHeader = (View) itemView.findViewById(R.id.layout_header);
            mPicker = (IncDecImageButton) itemView.findViewById(R.id.incdec);
            mAddCart = (View) itemView.findViewById(R.id.add_cart);
            badge = (MaterialBadgeTextView) itemView.findViewById(R.id.badge);

            mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
                    IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
            mPicker.setupValues(1, 20, 1, 1);
            mPicker.enableLongPress(true, true, 200);
        }
    }

    interface ClickListener {
        void onShotClick(Product item);

        void onCartAdd(Product item, int position);

        void onCartRemove(Product item, int position);

        void onCartLogin();

        void onItemQuantity(Product item, float quantity, int position);
    }
}
```
**FRAGMENT**

```
 @Override
    public View onCreateView(LayoutInflater inflater,
                             ViewGroup container,
                             Bundle savedInstanceState) {
        View fragmentView = inflater.inflate(R.layout.fragment_browse, container, false);
        ButterKnife.bind(this, fragmentView);
        setupViews();
        initBoomButton();
        return fragmentView;
    }

    private void setupViews() {
        mLayoutManager = new GridLayoutManager(getActivity(), 2);
        mItemRecycler.setLayoutManager(mLayoutManager);
        mItemRecycler.setAdapter(mBrowseAdapter);
        mItemRecycler.addItemDecoration(new GridSpacingItemDecoration(2, 15, false));
        mItemRecycler.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {

                if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                    int visibleItemCount = mLayoutManager.getChildCount();
                    int totalItemCount = mLayoutManager.getItemCount();
                    int pastVisibleItems = mLayoutManager.findFirstVisibleItemPosition();
                    if (pastVisibleItems + visibleItemCount >= totalItemCount) {
                        bmb.setVisibility(View.GONE);
                        Timber.d("SCROLLED TILL THE LAST in IDLE STATE >>>>>>> ");
                    } else {
                        bmb.setVisibility(View.VISIBLE);
                        Timber.d("IDLE STATE >>>>>>>");
                    }
                }

                super.onScrollStateChanged(recyclerView, newState);
            }
        });
    }

    @Override
    public void showItems(List<Product> items, Map<String, String> cartItems) {
        mBrowseAdapter = new BrowseAdapter(items, getActivity());
        mItemRecycler.setAdapter(mBrowseAdapter);
        mBrowseAdapter.setCart(cartItems);
        mBrowseAdapter.setClickListener(this);
        mItemRecycler.setVisibility(View.VISIBLE);
        cartCount = cartItems.size();
        ((BrowseActivity) getActivity()).setNotifCount(cartCount);
    }

    @Override
    public void updateItems(List<Product> items, Map<String, String> cartItems) {
        mBrowseAdapter.setNewData(items);
        mBrowseAdapter.setCart(cartItems);
        mBrowseAdapter.notifyDataSetChanged();
    }

```

**CRASH LOG CAT**

```
02-09 09:16:01.524 21919-21919/me.arulnadhan.shopper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: me.arulnadhan.shopper, PID: 21919
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hariofspades.incdeclibrary.IncDecImageButton.setConfiguration(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter$ShotViewHolder.<init>(BrowseAdapter.java:171)
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.createBaseViewHolder(BrowseAdapter.java:64)
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.createBaseViewHolder(BrowseAdapter.java:31)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:548)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:527)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                           at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                           at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                           at android.view.View.layout(View.java:15686)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                           at android.view.View.layout(View.java:15686)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                           at android.view.View.layout(View.java:15686)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                           at android.view.View.layout(View.java:15686)

```

**Comment by 1109993488** [comment]
```
//    @Override
//    protected BaseViewHolder createBaseViewHolder(View view) {
//        return  new ShotViewHolder(view);
//    }

    public class ShotViewHolder extends BaseViewHolder {

        ImageView prodImage;
        TextView prodPrice;
        TextView prodName;
        TextView prodUnit;
        View mAddCart;
        View mPickerView;
        View mHeader;
        IncDecImageButton mPicker;
        Product mItem;
        MaterialBadgeTextView badge;

        public ShotViewHolder(View itemView) {
            super(itemView);
//            prodImage = (ImageView) itemView.findViewById(R.id.image_shot);
//            prodPrice = (TextView) itemView.findViewById(R.id.text_price);
//            prodName = (TextView) itemView.findViewById(R.id.text_title);
//            prodUnit = (TextView) itemView.findViewById(R.id.text_unit);
//            mPickerView = (View) itemView.findViewById(R.id.quantity_picker);
//            mHeader = (View) itemView.findViewById(R.id.layout_header);
//            mPicker = (IncDecImageButton) itemView.findViewById(R.id.incdec);
//            mAddCart = (View) itemView.findViewById(R.id.add_cart);
//            badge = (MaterialBadgeTextView) itemView.findViewById(R.id.badge);
//
//            mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
//                    IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
//            mPicker.setupValues(1, 20, 1, 1);
//            mPicker.enableLongPress(true, true, 200);
        }
    }

    @Override
    protected ShotViewHolder onCreateDefViewHolder(ViewGroup parent, int viewType) {
        ShotViewHolder holder = super.onCreateDefViewHolder(parent, viewType);
        holder.prodImage = (ImageView) holder.itemView.findViewById(R.id.image_shot);
        holder.prodPrice = (TextView) holder.itemView.findViewById(R.id.text_price);
        holder.prodName = (TextView) holder.itemView.findViewById(R.id.text_title);
        holder.prodUnit = (TextView) holder.itemView.findViewById(R.id.text_unit);
        holder.mPickerView = (View) holder.itemView.findViewById(R.id.quantity_picker);
        holder.mHeader = (View) holder.itemView.findViewById(R.id.layout_header);
        holder.mPicker = (IncDecImageButton) holder.itemView.findViewById(R.id.incdec);
        holder.mAddCart = (View) itemView.findViewById(R.id.add_cart);
        holder.badge = (MaterialBadgeTextView) holder.itemView.findViewById(R.id.badge);

        holder.mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
                IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
        holder.mPicker.setupValues(1, 20, 1, 1);
        holder.mPicker.enableLongPress(true, true, 200);
        return holder;
    }
```

**Comment by AruLNadhaN** [comment]
@1109993488 The App crashes after the code change.

```
02-09 10:07:59.225 24334-24334/me.arulnadhan.shopper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: me.arulnadhan.shopper, PID: 24334
                                                                       java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to me.arulnadhan.shopper.browse.BrowseAdapter$ShotViewHolder
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.onCreateDefViewHolder(BrowseAdapter.java:149)
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.onCreateDefViewHolder(BrowseAdapter.java:32)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:539)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
```

**Comment by 1109993488** [comment]
```
    @Override
    protected BaseViewHolder createBaseViewHolder(View view) {
        return  new ShotViewHolder(view);
    }

```

**Comment by AruLNadhaN** [comment]
@1109993488 The crashing has been stopped. But I am still getting the loading issue at the end of the list!

**Comment by 1109993488** [comment]
You don't have to rewrite the `getItemCount()` method.

**Comment by AruLNadhaN** [comment]
Thanks! That solved the Issue...

**Comment by AruLNadhaN** [comment]
@CymChad @1109993488 It Crashes still on devices which run below Android 5.0

**ADAPTER CODE**

```
class BrowseAdapter extends BaseQuickAdapter<Product, BrowseAdapter.ShotViewHolder> {

    private List<Product> mItems;
    private ClickListener mClickListener;
    Context mContext;
    private Map<String, String> selectedItems = new HashMap<>();

    public BrowseAdapter(List<Product> items, Context context) {
        super(R.layout.item_shot, items);
        mContext = context;
        mItems = items;
    }

    public void setCart(Map<String, String> cartItems) {
        this.selectedItems = cartItems;
    }

    public void setClickListener(ClickListener clickListener) {
        mClickListener = clickListener;
    }

    @Override
    protected ShotViewHolder createBaseViewHolder(View view) {
        return new ShotViewHolder(view);
    }

    Double getPrice(Product item) {
        if (item.getProductDisplayPrice().isEmpty())
            return Double.valueOf(item.getProductMRP());
        else
            return Double.valueOf(item.getProductDisplayPrice());
    }

    @Override
    protected void convert(ShotViewHolder shotViewHolder, Product item) {
        shotViewHolder.mItem = item;
        shotViewHolder.prodName.setText(StringUtils.capitalize(item.getProductName()));
        shotViewHolder.prodPrice.setText("₹ " + String.format("%.2f", getPrice(item)));
        shotViewHolder.prodUnit.setText(item.getProductUnit());
        if (selectedItems.containsKey(item.getProductID())) {
            shotViewHolder.badge.setVisibility(View.VISIBLE);
            String count = selectedItems.get(item.getProductID());
            shotViewHolder.mAddCart.setVisibility(View.GONE);
            shotViewHolder.mPickerView.setVisibility(View.VISIBLE);
            shotViewHolder.mPicker.setValue(Float.parseFloat(count));
        } else {
            shotViewHolder.badge.setVisibility(View.GONE);
            shotViewHolder.mPickerView.setVisibility(View.GONE);
            shotViewHolder.mAddCart.setVisibility(View.VISIBLE);
        }

        Glide.with(shotViewHolder.itemView.getContext()).load(item.getProductImage())
                .placeholder(R.mipmap.ic_launcher).diskCacheStrategy(DiskCacheStrategy.SOURCE).into(shotViewHolder.prodImage);

        shotViewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            p
```ublic void onClick(View v) {
                if (mClickListener != null) {
                    mClickListener.onShotClick(shotViewHolder.mItem);
                }
            }
        });

        shotViewHolder.mAddCart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mClickListener != null) {
                    String Email = PrefUtils.getFromPrefs(mContext, "Email", null);
                    if (Email == null) {
                        mClickListener.onCartLogin();
                    } else
                        itemAdded(shotViewHolder);
                }
            }
        });

        shotViewHolder.mPicker.setOnValueChangeListener(new IncDecImageButton.OnValueChangeListener() {
            @Override
            public void onValueChange(IncDecImageButton view, float oldValue, float newValue) {
                itemQuantity(shotViewHolder, newValue);
                if (newValue == 0.0) {
                    itemRemoved(shotViewHolder);
                }
            }
        });

    }

    private void itemRemoved(ShotViewHolder shotViewHolder) {
        mClickListener.onCartRemove(shotViewHolder.mItem, shotViewHolder.getAdapterPosition());
        shotViewHolder.mPickerView.setVisibility(View.GONE);
        shotViewHolder.mAddCart.setVisibility(View.VISIBLE);
        shotViewHolder.badge.setVisibility(View.GONE);
    }

    private void itemAdded(ShotViewHolder shotViewHolder) {
        mClickListener.onCartAdd(shotViewHolder.mItem, shotViewHolder.getAdapterPosition());
        shotViewHolder.mAddCart.setVisibility(View.GONE);
        shotViewHolder.mPickerView.setVisibility(View.VISIBLE);
        shotViewHolder.badge.setVisibility(View.VISIBLE);
        shotViewHolder.mPicker.setValue(1);
    }

    private void itemQuantity(ShotViewHolder shotViewHolder, float quantity) {
        mClickListener.onItemQuantity(shotViewHolder.mItem, quantity, shotViewHolder.getAdapterPosition());
    }

    @Override
    protected ShotViewHolder onCreateDefViewHolder(ViewGroup parent, int viewType) {
        ShotViewHolder holder = super.onCreateDefViewHolder(parent, viewType);
        holder.prodImage = (ImageView) holder.itemView.findViewById(R.id.image_shot);
        holder.prodPrice = (TextView) holder.itemView.findViewById(R.id.text_price);
        holder.prodName = (TextView) holder.itemView.findViewById(R.id.text_title);
        holder.prodUnit = (TextView) holder.itemView.findViewById(R.id.text_unit);
        holder.mPickerView = (View) holder.itemView.findViewById(R.id.quantity_picker);
        holder.mHeader = (View) holder.itemView.findViewById(R.id.layout_header);
        holder.mPicker = (IncDecImageButton) holder.itemView.findViewById(R.id.incdec);
        holder.mAddCart = (View) holder.itemView.findViewById(R.id.add_cart);
        holder.badge = (MaterialBadgeTextView) holder.itemView.findViewById(R.id.badge);

        holder.mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
                IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
        holder.mPicker.setupValues(1, 20, 1, 1);
        holder.mPicker.enableLongPress(true, true, 200);
        return holder;
    }

    public class ShotViewHolder extends BaseViewHolder {

        ImageView prodImage;
        TextView prodPrice;
        TextView prodName;
        TextView prodUnit;
        View mAddCart;
        View mPickerView;
        View mHeader;
        IncDecImageButton mPicker;
        Product mItem;
        MaterialBadgeTextView badge;

        public ShotViewHolder(View itemView) {
            super(itemView);
//            prodImage = (ImageView) itemView.findViewById(R.id.image_shot);
//            prodPrice = (TextView) itemView.findViewById(R.id.text_price);
//            prodName = (TextView) itemView.findViewById(R.id.text_title);
//            prodUnit = (TextView) itemView.findViewById(R.id.text_unit);
//            mPickerView = (View) itemView.findViewById(R.id.quantity_picker);
//            mHeader = (View) itemView.findViewById(R.id.layout_header);
//            mPicker = (IncDecImageButton) itemView.findViewById(R.id.incdec);
//            mAddCart = (View) itemView.findViewById(R.id.add_cart);
//            badge = (MaterialBadgeTextView) itemView.findViewById(R.id.badge);
//
//            mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
//                    IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
//            mPicker.setupValues(1, 20, 1, 1);
//            mPicker.enableLongPress(true, true, 200);
        }
    }

    interface ClickListener {
        void onShotClick(Product item);

        void onCartAdd(Product item, int position);

        void onCartRemove(Product item, int position);

        void onCartLogin();

        void onItemQuantity(Product item, float quantity, int position);
    }
}

**CRASH LOGCAT**

```
02-26 14:48:22.208 11413-11413/me.arulnadhan.shopper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       android.view.InflateException: Binary XML file line #98: Error inflating class com.hariofspades.incdeclibrary.IncDecImageButton
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1025)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:662)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:658)
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.onCreateDefViewHolder(BrowseAdapter.java:141)
                                                                           at me.arulnadhan.shopper.browse.BrowseAdapter.onCreateDefViewHolder(BrowseAdapter.java:27)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:539)
                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                           at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                           at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                           at android.view.View.layout(View.java:13754)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                           at android.view.View.layout(View.java:13754)
                                                                       	at android.view.Vi
```
