### ISSUE TITLE
setNewData 问题

### ISSUE THREAD

**Issue by fuxianwen** [CymChad/BaseRecyclerViewAdapterHelper#782]
setnewData（）的时候  mLoadMoreEnable 设置了为true，建议删除这一句，一般是否加载更多都有判断不需要这一句，而有的情况 如基类封装加载更多 有的列表不需要加载更多  setnewdata赋值就会打开加载更多

**Comment by 1109993488** [comment]
在下拉刷新的时候关闭加载更多，获取到数据后开启更多（这个是为了防止下拉刷新的时候加载更多也会回调）

**Comment by fuxianwen** [comment]
但是我们列表一般会写基类，有点列表我们不需要加载更多，有了这个就要子后面再添加了，然而下拉刷新了   都会判断 是否加载 更多撒  所以这个没必要

**Comment by 1109993488** [comment]
这个只在demo里调了，你可以不调

**Comment by fuxianwen** [comment]
这样setnewdata的作用就小了很多了啊..

**Comment by 1109993488** [comment]
之前回答的问题好像不是你提的问题，如果你不需要加载更多不设置setOnLoadMoreListener这个方法，即使setNewData是不会回调加载更多的

**Comment by fuxianwen** [comment]
主要是 基类封装问题 我下拉刷新 和加载更多封装在基类里的 有的界面不需要下载更多 但是基类实现了那个接口  setNewData就 让我打开了加载更多..

**Comment by 1109993488** [comment]
你不能给你的基类穿个参数是否开启加载更多吗？

**Comment by fuxianwen** [comment]
默认我就是设置的不加载更多啊  setNewData 的时候就打开了

**Comment by fuxianwen** [comment]
写一个 方法设置不搞监听 也是可以， 但是纠结的不是 不能实现啊，你不觉得加了那句话麻烦多了吗，每次添加数据的时候本来就要判断是否可以加载更多

**Comment by CymChad** [comment]
看下你的封装思路 @fuxianwen

**Comment by fuxianwen** [comment]
@Override
    protected void initDatas() {
        mRecycler.setLayoutManager(getLayoutManager());
        if (getDividerItemDecoration() != null)
            mRecycler.addItemDecoration(getDividerItemDecoration());
        mRefreshSwipe.setOnRefreshListener(this);
        mRefreshSwipe.setColorSchemeColors(ContextCompat.getColor(mContext, R.color.colorPrimary));
        mBaseQuickAdapter = getAdapter();
        if (mBaseQuickAdapter != null) {
            mBaseQuickAdapter.setOnLoadMoreListener(this);
            mBaseQuickAdapter.setEnableLoadMore(false);
            mBaseQuickAdapter.openLoadAnimation();
            mRecycler.setAdapter(mBaseQuickAdapter);
        }
    }


    @Override
    public void onRefresh() {
        isRefresh = true;
        if (mBaseQuickAdapter != null) {
            mBaseQuickAdapter.setEnableLoadMore(false);
        }
    }

    @Override
    public void onLoadMoreRequested() {
        isRefresh = false;
        mRefreshSwipe.setEnabled(false);
    }
 我是这样的 上面那个人的意思     mRefreshSwipe.setOnRefreshListener(this);  这里判断一下，但是 有加载更多的情况时，一般我们一个接口请求完了都会判断一下是否加载更多，而我们的判断 就必须在setnewdata（）后面了 ，不然加载更多就是打开的 ，这个也很容易出问题，不熟的时候就是这出问题，
而setnewdata 里面的mLoadMoreEnable  本来就是重复设置了

**Comment by CymChad** [comment]
在没有更多的时候，就算进了onLoadMoreRequested回调，然后把上拉关闭掉，这样会出现什么问题吗？因为现在多数用户遇到的问题是，滑到了底部关闭了上拉，但是下次下拉的时候数据就不会开启上拉功能了，因为之前已经关闭了。你指的容易出问题，具体是什么问题？我们现在的设计是让所有的处理全部在onLoadMoreRequested里面去处理，默认都会进onLoadMoreRequested，如：第一页不满足一页的情况，错误的情况，没有数据的情况，有更多数据的情况。

**Comment by fuxianwen** [comment]
您的意思是 在onLoadMoreRequested 判断是否加载数据额 那是否关闭开启都 不用写了额

**Comment by CymChad** [comment]
恩 是的，不需要在额外的关闭开启，因为设置了setOnLoadMoreListener就默认开启了。

**Comment by fuxianwen** [comment]
好吧  回调里面判断 好像更方便

**Comment by fuxianwen** [comment]
-  @Override
    public void onLoadMoreRequested() {
        super.onLoadMoreRequested();
        if (mAdapter == null)
            return;
        if (mAdapter.getData().size() < PAGE_COUNT)
            mAdapter.loadMoreComplete();
        else {
            requestHttp();
        }
    }
没有滚动的时候回报错额
        java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                                   at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2530)
                                                                   at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4895)
                                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:11113)
                                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:11104)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:6604)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.loadMoreComplete(BaseQuickAdapter.java:203)
                                                                   at com.yd.circle.ui.BaseRefreshFragment.onLoadMoreRequested(BaseRefreshFragment.java:54)
                                                                   at com.yd.circle.ui.home.LovelyFragment.onLoadMoreRequested(LovelyFragment.java:113)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.autoLoadMore(BaseQuickAdapter.java:996)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:507)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5459)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                                   at android.view.View.layout(View.java:17684)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5631)

**Comment by CymChad** [comment]
这个是因为你操作数据的时候要放在mRecyclerView.post(里面)。

**Comment by fuxianwen** [comment]
什么数据，我这是加载更多的时候 判断是否请求加载更多啊，不加载关闭加载框

**Comment by fuxianwen** [comment]
算了我就在外面判断   难得纠结着问题了  能行就成0.0

**Comment by CymChad** [comment]
就是adddata 这个操作。

**Comment by fuxianwen** [comment]
不得行的

**Comment by fuxianwen** [comment]
得行..  这是为啥子...

**Comment by fuxianwen** [comment]
Process: com.yd.circle, PID: 27025
                                                               java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                                   at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2530)
                                                                   at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4895)
                                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:11113)
                                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:11104)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:6604)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.loadMoreComplete(BaseQuickAdapter.java:203)
                                                                   at com.yd.circle.ui.home.LovelyFragment.onLoadMoreRequested(LovelyFragment.java:120)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.autoLoadMore(BaseQuickAdapter.java:996)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:507)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5459)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
 不得行 还是这错

**Comment by 1109993488** [comment]
你是封装的BaseAcitivty吗？是否是分页在加载数据前能知道还是需要请求完接口才知道？

**Comment by fuxianwen** [comment]
功能我能实现，之前说setnewdata 里面    mLoadMoreEnable = true;  又把加载更多开启了就不好封装了
群主说 直接在 加载更多回调里面 判断， 我在回调里面关闭加载更多 会报错

**Comment by fuxianwen** [comment]
肯定是提前就知道是否需要分页撒 @1109993488

**Comment by 1109993488** [comment]
```
    @Override
    protected void initDatas() {
        mRecycler.setLayoutManager(getLayoutManager());
        if (getDividerItemDecoration() != null)
            mRecycler.addItemDecoration(getDividerItemDecoration());
        mRefreshSwipe.setOnRefreshListener(this);
        mRefreshSwipe.setColorSchemeColors(ContextCompat.getColor(mContext, R.color.colorPrimary));
        mBaseQuickAdapter = getAdapter();
        if (mBaseQuickAdapter != null) {
            if(openLoadMore()) {
                mBaseQuickAdapter.setOnLoadMoreListener(this);
            }
            mBaseQuickAdapter.setEnableLoadMore(false);
            mBaseQuickAdapter.openLoadAnimation();
            mRecycler.setAdapter(mBaseQuickAdapter);
        }
    }

    protected boolean openLoadMore(){
        return true;
    }
```

**Comment by fuxianwen** [comment]
n你这是 不用加载更多的时候啊 要了的 时候 是否开启加载更多 你还是得写在newdata 后面

**Comment by fuxianwen** [comment]
没遇到过 根本不知道 必须写在他后面才能关闭

**Comment by 1109993488** [comment]
难道你的界面一会分页一会不分页？ 
```
adapter.setNewData(list);
if(没有更多数据){
    adapter.loadMoreEnd(true);
}
```

**Comment by fuxianwen** [comment]
数据不够的时候 就不加载更多了撒 多请求一次干嘛？难道你们接口返回数据了 随便返回多少条你都去加载更多一次吗？  特别是未满屏时 你  在请求一次用户都看得到 很不好吧

**Comment by fuxianwen** [comment]
都能实现功能 ，只是感觉setnewdata 里面 **mLoadMoreEnable = true 感觉没必要  返回数据了本来就会判断是否打开**

**Comment by 1109993488** [comment]
现在不好改，可能会出兼容问题

**Comment by CymChad** [comment]
感谢你的建议，已添加到优化项中。
