### ISSUE TITLE
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by kpioneer123** [CymChad/BaseRecyclerViewAdapterHelper#801]
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:694)
	at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:682)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:678)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:555)
	at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:61)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
	at android.support.v7.widget.RecyclerView$Recycler.get

**Comment by CymChad** [comment]
版本

**Comment by CymChad** [comment]
请更新至最新版
