### ISSUE TITLE
文档自定义viewholder问题

### ISSUE THREAD

**Issue by pye52** [CymChad/BaseRecyclerViewAdapterHelper#805]
文档上使用自定义viewholder的话需要重写这个方法
```java
// 当使用自定义的BaseViewHolder时，需要重写此函数以创建ViewHolder
protected K createBaseViewHolder(View view) {
    return (K) new BaseViewHolder(view);
}
```
如果我的viewholder这样写的话
```java
 private class MyViewHolder extends BaseViewHolder implements CompoundButton.OnCheckedChangeListener, View.OnClickListener {
        private MyViewHolder (View itemView) {
            super(itemView);
            CheckBox cb = (CheckBox) itemView.findViewById(R.id.rv_item_cb);
            itemView.setOnClickListener(this);
            cb.setOnCheckedChangeListener(this);
        }
        ......
}
```
使用headerview之类的话会报错，源码部分截取如下
```java
switch (viewType) {
            case LOADING_VIEW:
                baseViewHolder = getLoadingView(parent);
                break;
            case HEADER_VIEW:
                baseViewHolder = createBaseViewHolder(mHeaderLayout);
                break;
            case EMPTY_VIEW:
                baseViewHolder = createBaseViewHolder(mEmptyLayout);
                break;
            case FOOTER_VIEW:
                baseViewHolder = createBaseViewHolder(mFooterLayout);
                break;
            default:
                baseViewHolder = onCreateDefViewHolder(parent, viewType);
        }
```
可见viewtype匹配到headerview等等布局的时候会调用`createBaseViewHolder`这个方法，传入了mHeaderLayout时就会找不到相应的控件而报错(如我的viewholder会给checkbox绑定一个事件)，所以应该是要重写`onCreateDefViewHolder(ViewGroup parent, int viewType)`这个方法才对
```java
protected K onCreateDefViewHolder(ViewGroup parent, int viewType) {
    return (K) new onCreateDefViewHolder(getItemView(yourLayoutId, parent));
}
```

**Comment by elfman** [comment]
现在已经改为不用修改createBaseViewHolder也行了，但文档忘了改过来了。
你这种情况应该是你在MyViewHolder的构造函数里自行判断是否是HeaderView或其他View，再确定做什么操作。因为父类createBaseViewHolder只允许一种ViewHolder，你重定义了K的泛型类型，HeaderView的ViewHolder也得使用你的MyViewHolder才行，否则类型不匹配

**Comment by pye52** [comment]
@elfman 额，现在应该怎么写呢？

**Comment by elfman** [comment]
itemView.findViewById()后先判断返回值是否有效，以此确定是否是itemview，再操作

**Comment by pye52** [comment]
@elfman 那这样不也需要重写createBaseViewHolder么。我重写了onCreateDefViewHolder的话连判断都不用了，还是说会有什么特殊情况会匹配到default的viewtype导致报错？

**Comment by elfman** [comment]
现在已经利用反射来构造ViewHolder了，`createBaseViewHolder`和`onCreateDefViewHolder `都不需要重写了

**Comment by elfman** [comment]
按你的做法default时的viewHolder是搞定了，但HeaderView这些的ViewHolder怎么构造？

**Comment by pye52** [comment]
@elfman default时调用的是`onCreateDefViewHolder`，headerview调用的`createBaseViewHolder`，所以不会有影响。按照文档的方式是重写了'createBaseViewHolder'，这才没办法构造headerview的viewholder。

**Comment by elfman** [comment]
HeaderView也得使用你的MyViewHolder才行啊，否则你想将HeaderView放到哪个类型的ViewHolder里去？

**Comment by pye52** [comment]
是这样的，我重写完之后，default的时候`onCreateDefViewHolder`会`new myviewholder()`。不是default的时候是`new BaseViewHolder()`。即headerview会调用自带的baseviewholder，不会走我的那个viewholder构造方法。
我觉得反射也是有性能损耗的，而看源代码发现有一个暴露出来的`onCreateDefViewHolder`没有地方用上，猜想是设计的时候就考虑到让用户自定义viewholder去重写这个方法，可能后来忘了。

**Comment by elfman** [comment]
Recyclerview的Adapter只接受一种ViewHolder泛型，而且父类是不能转化为子类的，即baseviewholder不能转为MyViewHolder
反射是有性能损耗，但Recyclerview会复用ViewHolder，`createBaseViewHolder`被调用的次数有限，这种损耗基本可以忽略，如果你觉得性能损耗很大可以直接重写`createBaseViewHolder`。
`onCreateDefViewHolder`是以前残留下的，现在可以说是多余的了，很快就会删了它

**Comment by pye52** [comment]
myviewholder是继承baseviewholder的，所以不需要从baseviewholder转到myviewholder，而是myviewholder转为baseviewholder
看一下这个图片可能更清晰点
![img](http://7xqnkw.com1.z0.glb.clouddn.com/Adapter.png)

**Comment by pye52** [comment]
我觉得原本的这个设计很合理…为什么要去掉，只是文档写得不太清晰…

**Comment by elfman** [comment]
你这是另一种做法，跟我的思路不一样，你这种做法就需要每次使用ViewHolder时都要做一次类型转换，比起create时只判断一次，更显麻烦

**Comment by pye52** [comment]
@elfman 尝试了下反射的方式，需要在构造方法内判断view是否为空，其实有时也是一个麻烦…如果不判断的话，会抛异常，而且界面会卡一下。
建议不要删除`onCreateDefViewHolder`。。。如果直接重写`createBaseViewHolder`的话需要对每个itemview都判断一下，更麻烦

**Comment by elfman** [comment]
不判断时抛出的异常发我看下

**Comment by pye52** [comment]
[demo]( https://github.com/pye52/AdapterDemo)
```java
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createGenericKInstance(BaseQuickAdapter.java:719)
W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:700)
W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.getLoadingView(BaseQuickAdapter.java:565)
W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:544)
W/System.err:     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:62)
W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
W/System.err:     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
W/System.err:     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
W/System.err:     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
W/System.err:     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
W/System.err:     at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6114)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
W/System.err:     at com.kanade.adapterdemo.MyAdapter$MyViewHolder.<init>(MyAdapter.java:27)
W/System.err: 	... 21 more
```

**Comment by elfman** [comment]
more下面的也发一下

**Comment by pye52** [comment]
那个more没办法展开了……我贴一下adapter的代码吧，就是idTv这个TextView找不到了
```java
public class MyAdapter extends BaseQuickAdapter<User, MyAdapter.MyViewHolder> {
    public MyAdapter(List<User> list) {
        super(R.layout.item, list);
    }

    @Override
    protected void convert(MyViewHolder helper, User item) {
        helper.setText(R.id.user_id, item.id + "")
                .setText(R.id.user_name, item.name);
    }

    public class MyViewHolder extends BaseViewHolder {
        public MyViewHolder(View itemView) {
            super(itemView);
            TextView idTv = (TextView) itemView.findViewById(R.id.user_id);
            idTv.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    Log.d("MainActivity", mData.get(getAdapterPosition()).name);
                }
            });
        }
    }
}
```

**Comment by elfman** [comment]
那不还是你一开始就提的问题吗。。。

**Comment by pye52** [comment]
是啊。。。所以采用反射的话我要加`if(idTv != null)`，如果只是复写`onCreateDefViewHolder`的话不就需要了…

**Comment by elfman** [comment]
解决的方法我上面也说了。
我还是推荐你照我的思路来做，在构造方法里判断一次就行了。比起以后每次使用时都要转化一次要方便得多，因为你可能会在很多方法里使用到viewHolder，如convert、拖拽、设置listener等，并且这些方法调用的次数远远大于create

**Comment by pye52** [comment]
我将两种方式结合了下提了个PR
反射其实没问题，只是在headerview这些自带的viewholder就应该直接new就好了，只有用户有自定义viewholder时才需要用到反射，因此viewtype匹配到default的时候才走反射的create方式。
这样既不需要重写任何方法，也不需要判断是否为空。
