### ISSUE TITLE
Adapter添加头布局的时候异常

### ISSUE THREAD

**Issue by magic0908** [CymChad/BaseRecyclerViewAdapterHelper#854]
我首先初始化adapter，然后再addHeaderView的时候报异常了，我贴一下我的代码，麻烦作者有时间看看
mLayoutManager = new LinearLayoutManager(mActivity);
        mLayoutManager.setOrientation(OrientationHelper.VERTICAL);
        mRecyclerView.setLayoutManager(mLayoutManager);
        mCooperAllAdapter = new CooperAllAdapter(mActivity,mListData);
        mRecyclerView.setAdapter(mCooperAllAdapter);
        mCooperAllAdapter.removeAllHeaderView();
        mCooperAllAdapter.addHeaderView(headView());
        mRecyclerView.addItemDecoration(new InnerItemDecoration(15));
比较奇葩的是，上面的代码，我在其他的fragment里面写，一模一样，但是其他的fragment就不会有异常，我也没找到原因。
然后下面是异常信息：
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{c34ed8e position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                                  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5249)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5431)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)

**Comment by magic0908** [comment]
我知道是什么问题了，假如list=0的时候，我设置了一个空布局，但是没有写mCooperAllAdapter.removeAllHeaderView();所以抛了异常。
另外还想问一下，就是我设置了一个头布局，但是list=0 的时候，我要保留头布局，然后在头布局下面显示没有列表数据？

**Comment by 1109993488** [comment]
setHeaderAndEmpty(true)这个方法

**Comment by magic0908** [comment]
ok了，谢谢
