### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hu499019771** [CymChad/BaseRecyclerViewAdapterHelper#856]
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                               at java.util.ArrayList.get(ArrayList.java:310)
                                                                               at com.chad.library.adapter.base.BaseMultiItemQuickAdapter.getDefItemViewType(BaseMultiItemQuickAdapter.java:35)
                                                                               at com.chad.library.adapter.base.BaseQuickAdapter.getItemViewType(BaseQuickAdapter.java:462)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener.isHeaderOrFooterPosition(SimpleClickListener.java:233)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener.access$300(SimpleClickListener.java:31)
                                                                               at com.chad.library.adapter.base.listener.SimpleClickListener$ItemTouchHelperGestureListener.onLongPress(SimpleClickListener.java:160)
                                                                               at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:809)
                                                                               at android.view.GestureDetector.access$200(GestureDetector.java:46)
                                                                               at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:305)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by hu499019771** [comment]
item点击事件中,偶尔出现以上异常,能帮忙找下原因吗

**Comment by AllenCoder** [comment]
索引越界，应该是你的数据结构发生了变化，没有及时同步更新给adapter ？是否是多线程刷新了数据，没有及时提交到adapter？
