### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by chenyesheng** [CymChad/BaseRecyclerViewAdapterHelper#858]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
                                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1140)
                                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:683)
                                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:679)
                                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:556)
                                                                                           at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:62)
                                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6321)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5509)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                           at android.view.View.layout(View.java:15718)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2129)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1103)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5949)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:601)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:571)
                                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)

**Comment by CymChad** [comment]
什么版本？bug复现步骤？

**Comment by chenyesheng** [comment]
2.8.4版本。最简单的使用，装载数据就报这个错误。

**Comment by chenyesheng** [comment]
找到问题了。是我的item布局文件出现问题

**Comment by CymChad** [comment]
哦，问题解决就好了。

**Comment by qq471077336** [comment]
我的是View写成view，如果有人遇到就看下

**Comment by ljf1172361058** [comment]
@qq471077336 谢谢 我的也是 哈哈
