### ISSUE TITLE
请问对数据的懒加载如何处理

### ISSUE THREAD

**Issue by tsunamilx** [CymChad/BaseRecyclerViewAdapterHelper#9]
举个典型的栗子，一开始要网络请求加载数据，然后在显示。

你的Adapter一开始就要指定data，虽然有add的方法，但是似乎不是很方便，而且容易报OutOfIndexException。
我看你的关于刷新加载更多的源码（PullToRefreshUseActivity），是每次重新实例个Adapter，重新设置给RecyclerView，这样做是不是高效？

请指教。

**Comment by CymChad** [comment]
恩，好的，感谢提出的问题，今天内给你答复。

**Comment by CymChad** [comment]
感谢提出来的问题，今天内给你答复。

**Comment by githubzaibao** [comment]
你好，你说的这个重新实例个Adapter与clear()哪个更好，我认为应该视情况而定，因为clear()也就是遍历里面元素然后置Null，你重新实例一个也要考虑重新实例对象是比较耗费资源的，当你data集合的size()不是很大时，clear()相信会是个更好的选择，你提出的异常我们会及时查找并修复，希望能提供下异常的报错信息，方便我们及时修复，谢谢你的反馈

**Comment by githubzaibao** [comment]
你一开始如果无data的话，可以指定为null，后面我们会提供一个不需要制定data的构造方法

**Comment by tsunamilx** [comment]
IndexOutOfBoundsException：
```
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.add(ArrayList.java:147)
at com.chad.library.adapter.base.BaseQuickAdapter.add(BaseQuickAdapter.java:146)
at com.example.ArticlesFragment.addArticle(ArticlesFragment.java:78)
```

我一开始在初始化Adapter的时候给了null的data，报了这个错，然后给了个size为20的ArrayList，还是抱这个错
```java
private class ArticlesAdapter extends BaseQuickAdapter<Article> {

    public ArticlesAdapter(Context context) {
        super(context, R.layout.article_item, new ArrayList<Article>(20));
        openLoadAnimation();
    }

    @Override
    protected void convert(BaseViewHolder helper, Article article) {
        helper.setText(R.id.article_title, article.getTitle());
    }
}
```

我是对数据进行逐一添加的：
```java
@Override
public void addArticle(int position, Article article) {
    // 这个会导致 IndexOutOfBoundsException
    adapter.add(position, article);

    // 我目前是这样解决的:
    adapter.getData().add(article);
    adapter.notifyItemInserted(position);
}
```

**Comment by tsunamilx** [comment]
哦，抱歉，犯了个低级错误，IndexOutOfBoundsException是我ArrayList使用不当...:flushed::flushed::flushed:

**Comment by githubzaibao** [comment]
已修复，新增了API，
