### ISSUE TITLE
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to 

### ISSUE THREAD

**Issue by mgjnana** [CymChad/BaseRecyclerViewAdapterHelper#903]
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to xxx

   at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:657)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:58)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:260)
                                                                     at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:229)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                                     at android.view.View.layout(View.java:15529)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:4870)
                                                                 	at android.view.ViewRootImpl.performLayout(V

**Comment by mgjnana** [comment]
use BaseMultiItemQuickAdapter in databinding project.

public class xxx extends BaseViewHolder {
        public xxx(View view) {
            super(view);
        }
        public ViewDataBinding getBinding() {
            return DataBindingUtil.bind(getConvertView());
        }
}

**Comment by CymChad** [comment]
更新至最新版本

**Comment by mgjnana** [comment]
多少？

**Comment by mgjnana** [comment]
谢谢，更新到新版本，已解决，如果使用旧版本需要重写onCreateDefViewHolder，但这样addItemType就意义不大了。

**Comment by ZhuTingyu** [comment]
debug打包下正常，release加混淆，报该错误，使用的最新的版本

**Comment by aZyreTech** [comment]
Getting same error.

I am using     implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.11"

can you please help ?

**Comment by cxydnxs** [comment]
You can check whether the confusion is configured correctly, may be you can  try use "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.11" (see this:https://mvnrepository.com/artifact/com.github.CymChad/BaseRecyclerViewAdapterHelper/2.9.22, It's show 3.0.11 is new version, )
or 
"implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02""(https://gitcode.net/mirrors/CymChad/BaseRecyclerViewAdapterHelper/-/tree/master/readme)

**Comment by cxydnxs** [comment]
> Getting same error.
> 
> I am using implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.11"
> 
> can you please help ?

You can check whether the confusion is configured correctly, may be you can try use "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.11" (see this:https://mvnrepository.com/artifact/com.github.CymChad/BaseRecyclerViewAdapterHelper/2.9.22, It's show 3.0.11 is new version, )
or
"implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02""(https://gitcode.net/mirrors/CymChad/BaseRecyclerViewAdapterHelper/-/tree/master/readme)

**Comment by cxydnxs** [comment]
> > Getting same error.
> > I am using implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.11"
> > can you please help ?
> 
> You can check whether the confusion is configured correctly, may be you can try use "com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.11" (see this:https://mvnrepository.com/artifact/com.github.CymChad/BaseRecyclerViewAdapterHelper/2.9.22, It's show 3.0.11 is new version, ) or "implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta02""(https://gitcode.net/mirrors/CymChad/BaseRecyclerViewAdapterHelper/-/tree/master/readme)

Hope this works for you！

**Comment by aZyreTech** [comment]
still getting same error

**Comment by cxydnxs** [comment]
> 

I can help you debug it, my telegram is: @shoanry, just a favor, if you need it
