### ISSUE TITLE
执行代码 loadMoreEnd()报错

### ISSUE THREAD

**Issue by duomaidragon** [CymChad/BaseRecyclerViewAdapterHelper#913]
loadMoreEnd()会触发java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;

**Comment by duomaidragon** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                        at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:514)
                                                                        at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:321)
                                                                        at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
                                                                        at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3275)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3088)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:614)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1766)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:633)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:568)
                                                                        at android.view.View.layout(View.java:15912)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5108)
                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2467)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2159)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1284)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6490)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:802)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:605)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:574)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:788)
                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                    	at

**Comment by duomaidragon** [comment]
loadMoreEnd()注释掉就不崩了，但是找不到原因~

**Comment by 1109993488** [comment]
加载更多是用的默认的吗?你把RecyclerView的ItemAnimator设置为空试试

**Comment by 1109993488** [comment]
提示类找不到，v4包不全？

**Comment by JueShouGitHub** [comment]
我上次就出现这个问题，高了一天也没搞好，我就重新迁移了一个新项目，然后就好了。。。
就是 AnimatorCompatHelper 这个类不存在，很蛋疼。。。

**Comment by 1109993488** [comment]
直接在类中引用这个类能找到？

**Comment by duomaidragon** [comment]
删除掉compile 'com.android.support:support-v4:+'这个就好了...这个思路要感谢上面让我确认v4包不全，和试图找AnimatorCompatHelper 这个类是否存在的同学。也感谢参与问题讨论的童鞋~~~

**Comment by 7hundeR** [comment]
我也初现了这个问题，add Data的时候和notifyItemChanged的时候

**Comment by caocao123** [comment]
compile('cn.qqtheme.framework:WheelPicker:xxxx') {
    exclude group: 'com.android.support'
}

重要：  exclude group: 'com.android.support'
cn.qqtheme.framework:WheelPicker这个是我用的别人的第三方的项目

**Comment by Demarcia-cn** [comment]
试试这个
https://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3/42957234#42957234

还有CSDN上的方案
http://blog.csdn.net/xx326664162/article/details/71488551
