### ISSUE TITLE
.setNestView(R.id.gv_images) 报错

### ISSUE THREAD

**Issue by keluokeda** [CymChad/BaseRecyclerViewAdapterHelper#926]
错误信息：
java.lang.RuntimeException: Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead
                                                                        at android.widget.AdapterView.setOnClickListener(AdapterView.java:800)
                                                                        at com.chad.library.adapter.base.BaseViewHolder.addOnClickListener(BaseViewHolder.java:359)
                                                                        at com.chad.library.adapter.base.BaseViewHolder.setNestView(BaseViewHolder.java:380)
                                                                        at com.ufind.recycler.MainActivity$1.convert(MainActivity.java:32)
                                                                        at com.ufind.recycler.MainActivity$1.convert(MainActivity.java:29)

项目中代码：
`        BaseQuickAdapter<Integer,BaseViewHolder> baseQuickAdapter = new BaseQuickAdapter<Integer, BaseViewHolder>(R.layout.item_content,list) {
            @Override
            protected void convert(BaseViewHolder helper, Integer item) {
                helper.setNestView(R.id.gv_image)
                        .setText(R.id.tv_content,String.valueOf(item));
            }
        };
        recyclerView.setAdapter(baseQuickAdapter);`

版本：
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.1'

测试项目地址：
https://github.com/keluokeda/recycler

**Comment by AllenCoder** [comment]
这个api当初的设计是为了recyclerview嵌套recyclerview的点击事件设计的，所以嵌套gridview可能会出现一些类型异常的bug ，现在升级到2.9.2版本之后，新增的点击api，可以避免这类嵌套bug了

**Comment by dazeGitHub** [comment]
为啥我把这行注释了发现也没事啊？
