### ISSUE TITLE
Expandable 加载更多

### ISSUE THREAD

**Issue by treycc** [CymChad/BaseRecyclerViewAdapterHelper#974]
Expandable的是适配器有类似addData的方法吗？
比如我有两个Level0Item同级的
1.直接从adapter.addData的话，再collsape的话，新增的数据还在外面。
2.从adapter.getdata找到其中一个的Level0Item，然后addSubItem，然后再addData。再collsape的话，就会报错，好像是notifyItemRangeRemoved报的错
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 10(offset:5).state:11
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                             at android.view.View.layout(View.java:17637)`
3.直接addItem的话，不addData的话，界面上不会显示
效果类似知乎日报的评论列表

**Comment by elfman** [comment]
1. 在item已经展开后，subItem与mData是没有关联的，你要添加数据就得两边都要加才行，否则在折叠时就会出现遗漏
2. 你试试调用collapse(pos, false, false)来折叠看看还有没有报错？
3. 与第一点原因相同

**Comment by treycc** [comment]
你好，折叠和收起都是用的(pos，false)没有动画的确实不报错了，显示也正确。用三个参数的话界面上没有任何效果，但是isExpanded却变化了，不知道是不是bug
还有就是默认展开这个需求还是很正常的，比如音乐的歌单，股票的各种排行榜都是像ExpandableListView一样可以默认展开的

**Comment by elfman** [comment]
现在expand功能的实现方式我不知道将默认展开的操作放在哪里比较合适。因为当item展开和折叠时，会改变Adapter内mData的值，如果在setData时就展开会让数据集加入了所有子项，如果在setData之后还有其它操作就会比较难操作，我也没想到其它好的操作点。所以我只加了个expandAll()方法让你们自己决定什么时候展开全部

**Comment by elfman** [comment]
我测试动态加item没有什么问题啊，我的代码如下

```Java
button.setOnClickListener(new View.OnClickListener(){
    @Override
    public void onClick(View v) {
        List<MultiItemEntity> list = adapter.getData();
        for (int i = 0; i < list.size(); i++) {
            MultiItemEntity obj = list.get(i);
            if (obj instanceof Person && ((Person)obj).name.equals("Bruce")) {
                Person person = new Person("Witcher", 99);
                adapter.addData(i + 1, person);
                MultiItemEntity parent = adapter.getData().get(adapter.getParentPosition(obj));
                ((Level1Item)parent).addSubItem(person);
                break;
            }
       }
   }
});
```

**Comment by treycc** [comment]
我是根据isExpand状态动态设置setOnLoadMoreListener
1.一开始我先这样设置的
![qq 20170408180918](https://cloud.githubusercontent.com/assets/15090153/24827974/8aac46a6-1c86-11e7-827e-56824acc6c0b.png)
然后在然后在动态设置setEnableLoadMore
![qq 20170408180829](https://cloud.githubusercontent.com/assets/15090153/24827977/90102b9e-1c86-11e7-8ea7-082a3b28e827.png)
然后发现界面上还会响应loadmore。这种界面效果就是折叠外面还是有数据。但是开始设置的LoadMoreViewcount是0.
2.然后我就改成了这样就好了
**@Subscribe()
    public void getExpandStatus(ExpandEvent expandEvent) {
        if (expandEvent.isExpanded) {
            commentsAdapter.setOnLoadMoreListener(requestLoadMoreListener, commentRecyclerView);
        } else {
            commentsAdapter.setEnableLoadMore(false);
        }
        KLog.a(commentsAdapter.getLoadMoreViewCount());
    }**
之前报错用的是
**commentsAdapter.setOnLoadMoreListener(null, commentRecyclerView);**
而不是
**commentsAdapter.setEnableLoadMore(false);**

**Comment by treycc** [comment]
关于setEnableLoadMore
就是我用一开始设置adapter传的是null，请求下来数据用的setNewData设置数据
我看setnewData源码
**this.mData = data == null ? new ArrayList<T>() : data;
        if (mRequestLoadMoreListener != null) {
            mNextLoadEnable = true;
            mLoadMoreEnable = true;
            mLoading = false;
            mLoadMoreView.setLoadMoreStatus(LoadMoreView.STATUS_DEFAULT);
        }
        mLastPosition = -1;
        notifyDataSetChanged();**
意思是只要监听不为空就会设置loadmore为true，但是我个人理解setNewData的是重新设置数据不知道对不对，判断loadmore应该用setEnableLoadMore而不是用是否有监听

**Comment by 1109993488** [comment]
@treycc 当时只是想的这样就不用自己设置开启加载更多了，不过现在不好改，可能会影响之前的代码

**Comment by CymChad** [comment]
但是想解决的问题就是上拉完毕后，会关闭上拉的flag。这样会导致下拉刷新上也无法开启上拉监听，所以当初就把下拉刷新会调用的`setNewData`函数加入了开启上拉的代码.
