### ISSUE TITLE
在Android 4.2 手机 BaseQuickAdapter报错

### ISSUE THREAD

**Issue by maimingliang** [CymChad/BaseRecyclerViewAdapterHelper#978]
android.view.InflateException: Binary XML file line #2: Error inflating class LinearLayout
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1072)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:682)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:678)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:555)
                                                                     at com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:61)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5833)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5057)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:541)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)

**Comment by FrankKwok** [comment]
XML布局贴一下

**Comment by CymChad** [comment]
@maimingliang 按照 @FrankKwok 的要求给出代码谢谢
