### ISSUE TITLE
PullToRefresh下拉后快速上拉会下标越界

### ISSUE THREAD

**Issue by 386534312** [CymChad/BaseRecyclerViewAdapterHelper#982]
04-09 22:02:56.622 12775-12775/com.chad.baserecyclerviewadapterhelper E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.chad.baserecyclerviewadapterhelper, PID: 12775
                                                                                        java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{4212a7b8 position=28 id=-1, oldPos=28, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5251)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5433)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
                                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                            at android.view.View.layout(View.java:14963)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:4650)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2148)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1860)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1076)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5913)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:601)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
                                                                                        	at android.os.Handler.handleCallbac

**Comment by shoushuai** [comment]
@386534312 我也曾遇到过java.lang.IndexOutOfBoundsException: Inconsistency detected.我的解决方法是通过刷新时禁止上拉那么一点时间

**Comment by CymChad** [comment]
版本号？

**Comment by 386534312** [comment]
@CymChad 用的demo里的功能报的错

**Comment by CymChad** [comment]
代码是你什么时候拉的？

**Comment by 386534312** [comment]
@CymChad 昨天的

**Comment by CymChad** [comment]
理论上下拉还没完毕是在处理数据，你再上拉会数据会出现问题。
但是demo中做过了`setEnableLoadMore`的处理
```java
 public void onRefresh() {
        pullToRefreshAdapter.setEnableLoadMore(false);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                pullToRefreshAdapter.setNewData(DataServer.getSampleData(PAGE_SIZE));
                isErr = false;
                mCurrentCounter = PAGE_SIZE;
                mSwipeRefreshLayout.setRefreshing(false);
                pullToRefreshAdapter.setEnableLoadMore(true);
            }
        }, delayMillis);
    }
```

**Comment by Jiiiiiin** [comment]
```bash
 --------- beginning of crash
2019-04-09 16:59:33.771 8120-8120/com.csii.emobilebank E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.csii.emobilebank, PID: 8120
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{f1efbb3 position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{ddd27c9 VFED..... ......I. 0,0-1080,1626 #7f090257 app:id/rv_list}, adapter:com.csii.mobilebank.ynrcc.delegate.main.HomeMultipleItemQuickAdapter@7bf5ece, layout:android.support.v7.widget.GridLayoutManager@cb251ef, context:com.csii.emobilebank.MainActivity@b1ca9ba
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:684)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1644)
        at android.support.v7.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1498)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
2019-04-09 16:59:33.773 8120-8120/com.csii.emobilebank E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

@CymChad 
大佬帮忙看看呗
