### ISSUE TITLE
使用setNewData 报错java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by sj853** [CymChad/BaseRecyclerViewAdapterHelper#988]
我使用下拉刷新的时候 是 setNewData方法   第一次刷新OK 
第二次 就报错了  版本是 2.9.9  感觉之前的版本不会报错
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 16(offset:17).state:31
                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)`

**Comment by sj853** [comment]
2.9.9 2.9.8 会出现这种问题    2.9.7就是正常

**Comment by CymChad** [comment]
收到，你是不是add了head？

**Comment by sj853** [comment]
恩 是有head

**Comment by CymChad** [comment]
收到

**Comment by CymChad** [comment]
compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.11'
